### ISSUE TITLE
As of now we can't fully rely on css-tree for parsing filter etc functional values

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio#1016]
See https://github.com/csstree/csstree/issues/246

That's why we have chrome only fallback on `CSSStyleValue.parse`

See https://github.com/webstudio-is/webstudio-designer/blob/23140f2f01e9d673f7db66479bc6303cd6709796/apps/designer/app/designer/features/style-panel/shared/parse-css-value.ts#L34

After we have known behavior of the issue above we need to think about the removal of `CSSStyleValue`.

**Comment by TrySound** [comment]
We parse these separately
