### ISSUE TITLE
Custom domains for published applications

### ISSUE THREAD

**Issue by andrasbacsai** [webstudio-is/webstudio#113]
Users are able to use their own domain for published websites.

## Solution
~~- [ ] Setup [Cloudflare SSL for SaaS](https://developers.cloudflare.com/ssl/ssl-for-saas/getting-started/) for wstd.io.~~
~~- [ ] Deploy the worker version of Webstudio.~~
Moved these to [here](https://github.com/webstudio-is/webstudio-designer/issues/117).

- [ ] Create a field in settings for the user to enter the custom domain.
- [ ] Create a function that calls Cloudflare API, and sets the right custom domain in the [SSL for SaaS API](https://developers.cloudflare.com/ssl/ssl-for-saas/).
- [ ] Create a detailed process (in the documentation and in Webstudio) for the user to setup the right `CNAME` entry in their own DNS provider.
- [ ] Store and retrieve the relationship between the `projectId` and `custom domain` available for Webstudio. In KV store for edge and in PostgreSQL for self-hosted.
- [ ] Create a function for querying this relationship on request and proxies the request to the right `project`.

**Comment by kof** [comment]
>  Create a field in settings for the user to enter the custom domain.

We already have a domain that is currently a subdomain, we should probably just set the new domain there?

> Create a detailed process (in documentation and in Webstudio) for the user to setup the right CNAME entry in their own DNS provider.

I would prefer if we find a very good article we can link to

**Comment by kof** [comment]
I would also split this issue in 2:

1. Make sure the current subdomain of wstd.io works with workers
2. Enable user to enter their own TLD and make that work with workers

**Comment by andrasbacsai** [comment]
Opened [this](https://github.com/webstudio-is/webstudio-designer/issues/117).
