### ISSUE TITLE
CSS optimisation

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio#1188]
Currently, on webstudio.is we have 30kb+ gzip/brotli css.
I have measured and in case we will use non-random ids this file will be just 10kb gzip/brotli.

The idea is to convert random ids to sequential ids on `publish` step.  In that case, we preserve random ids for the Builder (good for collaboration) and don't have issues with compression on published sites.

cc @TrySound

**Comment by kof** [comment]
is this duplicate of https://github.com/webstudio-is/webstudio/issues/1835 ?
