### ISSUE TITLE
Color control

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#1244]
The input component has a couple of visual issues:

- [x] Can the color swatch be focused? If yes, please tell me how. If no, please make it focusable according to the design of the Color Swatch component.

- [x] Color swatch is not aligned consistently with the design. Notice that in the design there is equal distance between the edges of the swatch and the edges of the input, but not so in prod.

Design:
<img width="262" alt="Screenshot 2023-03-14 at 4 07 49 PM" src="https://user-images.githubusercontent.com/86495896/225161869-1ac136cb-64e0-46e6-8d15-15d3ec01bace.png">

Prod:
<img width="58" alt="Screenshot 2023-03-14 at 4 09 05 PM" src="https://user-images.githubusercontent.com/86495896/225162036-03173d18-f6e0-4e40-8cec-d6af65b4a8ee.png">
<img width="61" alt="Screenshot 2023-03-14 at 4 09 22 PM" src="https://user-images.githubusercontent.com/86495896/225162073-1c22cb19-7665-48cc-af7d-cc34c09c4aec.png">

- [x] Dropdown arrow looks black in prod, but in design it's token: foreground.subtle

- [x] On the Backgrounds color input, the color swatch sometimes has a blue border. Please remove this as it is not part of the design.
<img width="67" alt="Screenshot 2023-03-14 at 4 15 13 PM" src="https://user-images.githubusercontent.com/86495896/225162848-ae3a5932-7dce-4c7b-ae98-5f87fd56a3b1.png">

**Comment by kof** [comment]
Regarding focusing:

1. you don't want to use tab to focus prefix/suffix in the input. Reason: it would make you tab up to 3 times to switch to the next value. Normally you would want to use arrow keys for this.
2. When your caret is in the input field, you can't use arrow keys either. 

My suggestion is: bind both arrow keys and an arrow key + modifier. On a prefix/suffix user would be able to use arrow key like everywhere else, but when in input modifier would help.

Which modifier? 
- we can't use shift, since that's for text selection
- `command` on mac is also used to jump at the beginning of the input, but we could use it for our purpose because that's probably not an often used thing in our specific case
- `option` on mac is used to jump over the words, its a viable option as well
- `control` doesn't seem to do anything on mac with arrow keys - maybe the best option? 

Don't know what windows does on those.

Generally, this is a separate issue around accessibility of TextField component, not specific to color use case. 

@rpominov need your thoughts on this. Please transfer it to a new issue if we haven't created one.

**Comment by rpominov** [comment]
Color Input is not updated in general as far as I know. I've renamed issue to "Update Color Input".

Regarding focus, I've no strong opinion on tab vs arrows, but want to point out downsides of arrows:

- user needs to guess / discover arrows
- almost no one will discover modifier probably
- tab is easier to implement probably

But I understand that we want some consistency on how focus works in such cases. Maybe the rule should be: 
 - if there's just one focusable child, then it should be just tabable; 
 - if there're 2+, use arrows.

**Comment by rpominov** [comment]
> Dropdown arrow looks black in prod, but in design it's token: foreground.subtle

@taylornowotny I don't understand what arrow you refer to. There's no arrow in "Color Input". Do you mean arrow in "Input Field"?

Input Field is also not updated yet: https://github.com/webstudio-is/webstudio-builder/issues/614

I want to do it next after my current issue.

**Comment by kof** [comment]
1. The rule is: when you can focus the element itself, then focusable children should be focusable using arrows.
2. Yes it's unfortunate this can't be made accessible and easy to discover. I am open to ideas on how to make it more discoverable. This is a difficult scenario with input and quite unique too.

**Comment by taylornowotny** [comment]
yes @rpominov I am referring to the Input component. Understood that you're still working on this.

Regarding focus management, I don't have a strong opinion either, just that there needs to be a way to focus the color swatch or else it's inaccessible by keyboard. We also don't have a way to focus nested menu triggers so that's the same issue.

If you can confirm that you're tracking all of this as part of another issue I will close this one.
- fix alignment of color swatch
- remove unintended highlight color on the color swatch
- add a way to focus-within inputs

**Comment by rpominov** [comment]
There're couple other issue about Color Input:

- https://github.com/webstudio-is/webstudio-builder/issues/1092 — tracks the last one from your list
- https://github.com/webstudio-is/webstudio-builder/issues/1247

I think we need just one issue with the goal to bring Color Input up to date with Figma. And only split if there some particular extra difficult sub-task.

I'd keep this one as the main issue.

**Comment by rpominov** [comment]
@kof 

> `control` doesn't seem to do anything on mac with arrow keys - maybe the best option?

`control + down/up` does something with app window in MacOS.

Why we can't use up/down without a modifier:

 - In `textarea` it moves cursor
 - In `input` it moves cursor to start/end
 - In `combobox` it opens menu
 - In something like number input it changes the value

If we're not in a list with nested controls, we can just ignore up/down, not support it for focus at all. But in a list not sure what we can do.


So cases we 


Looks like we can't use any of the modifier keys consistently :(

Hopefully we'll never have textarea with nested controls.


 
<img width="492" alt="Screenshot 2023-03-17 at 12 35 10" src="https://user-images.githubusercontent.com/825702/225854004-71cfe10e-faab-4af6-85f4-4a86d05fd0a1.png">

**Comment by rpominov** [comment]
Turned out `onKeyDown` is not called at all on `control + any arrow` :(

**Comment by rpominov** [comment]
Issue with `option` and `command`: 

For some reason `:focus-visible` is not set when calling `.focus()` form a `option/command + arrow` event

**Comment by kof** [comment]
huh, any other options?

**Comment by rpominov** [comment]
Not sure. Going to look into it more later. Maybe I'll figure out why `:focus-visible` is not set and fix/workaround it somehow.

Was going to add support for this in current PR, but decided to work on this later when I have a case with an input.

**Comment by TrySound** [comment]
Maybe consider switching to great https://omgovich.github.io/react-colorful along with updating?

**Comment by kof** [comment]
I think its quite a separate effort to change the picker, in addition we want the next version to be much better and support  a number of new modes
