### ISSUE TITLE
Heading outline quirk

### ISSUE THREAD

**Issue by ghost** [webstudio-is/webstudio#125]
Sometimes outlines on "Headings" manifest a quirk where the outline isn't rendering in the correct bounding-rectangle of the Heading. 

Screenshots:

<img width="381" alt="Screenshot_2022-07-09_at_7 39 20_PM" src="https://user-images.githubusercontent.com/105234327/178115173-ec456373-122c-4a07-aaa4-733457dbdab0.png">

<img width="639" alt="Screenshot_2022-07-09_at_7 44 40_PM" src="https://user-images.githubusercontent.com/105234327/178115183-a4f46159-c42b-4229-972a-a77b84ace362.png">

Screen Recording:

https://user-images.githubusercontent.com/105234327/178115460-6ce84093-29d0-4929-808f-fa4673eb39df.mp4

**Comment by kof** [comment]
Issue was closed because its the result of a line-height that is smaller than the font-size and browser will report based on that line-height from getBoundingClientRect()
