### ISSUE TITLE
Cleanup Avatar's `size` prop situation

### ISSUE THREAD

**Issue by Andarist** [webstudio-is/webstudio#1357]
typeof hides real type and Number.parseInt.
Ideally just define correct type in props.

_Originally posted by @TrySound in https://github.com/webstudio-is/webstudio-builder/pull/1345#discussion_r1155233311_

**Comment by kof** [comment]
FYI Avatar component is a copy-paste from an old radix-ui demo, that is not designed by @taylornowotny nor was ever properly rewritten. Most of the stuff it contains we don't even use or need. We should 
1. redesign it
2. rewrite it
