### ISSUE TITLE
Component settings system

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio#1528]
We want to have a settings system similar to props: 
 - also defined in meta, 
 - also renders controls in the panel based on meta, 
 - the main difference: settings are not passed to components and not sent to the frontend at all, they're only available in builder and at the backend of the published site.
 
 Use case is sensitive information or stuff that makes sense only in builder like instance label.

- [ ] Express from component meta available settings, similar to props
- [ ] UI in settings for settings is reusing props controls
- [ ] We create a state tree JSON just like props
- [ ] We make sure settings are never exposed to the UI
- [ ] Move label to settings
- [ ] First practical use case is to allow providing an email for forms to be sent to that email instead of site owner 

More context: https://discord.com/channels/955905230107738152/1100515833593221150

**Comment by kof** [comment]
outdated
