### ISSUE TITLE
Reimplement style info computing for style panel

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio#1536]
Since initial implementation style info computing became very complex.
We need new version based considering all new requirements and data structures

- support "inherit" keyword
- support "currentColor" keyword without looking into browser style

Here are all sources of styles we have now
- initial style from mdn-data
- html style from browsers default stylesheets
- preset styles from component meta
- inherited styles from ancestor instances
- cascaded styles from previous breakpoints
- remote styles from previous style sources
- local styles from current style source

**Comment by istarkov** [comment]
The other thing we need to iterate/find ancestor node with specific styles
<img width="231" alt="image" src="https://github.com/webstudio-is/webstudio-builder/assets/5077042/ae221fce-3e74-4e88-b7d4-c2c16cb4fa57">


And we need computedStyle for inherit keyword.
Use case - detect current node real style if `inherit` is set, needed in cases like show `Position`.

Both needs recursion or top/down algorithm of building current style.

**Comment by istarkov** [comment]
I think this is already too hard to read, we need some model like DOM.

```
node.parentNode
node.style
getComputedStyle(node)
```

Ability to use model with minimal knowledge of all that internal atoms. Without relying on React hooks.

**Comment by kof** [comment]
@istarkov be careful with "like DOM" DOM is slow partially because of the model.

**Comment by istarkov** [comment]
I don't mind if it will be not the full model but only parent iterator or `getStyle(instanceId)` call. As of now to do anything with styling you need to know all the internals we use. That's bad.

**Comment by istarkov** [comment]
I also think that tests we have should be rewritten in readable format.
For now they are fully unreadable.
It will be much better to understand what style shoud element have if our test input would be jsx like (we can use own jsx)
```
const blablaStyleSource = { width: 20px };
const blubluStyleSource = { height: 20px }
<div style={{ width: 10px, inheritedProp: blabla }} styleSources={['local', blablaStyleSource, blublu]}>
<selected style={} styleSources={['local']} selectedStyleSourceIndex={2} />
</div>

expect (selected.style.local).tobe(xxx);
expect (selected.style.value).tobe(xxx);
expect (selected.style.computed).tobe(xxx);
expect (selected.parent.style).tobe(xxx);
```

**Comment by TrySound** [comment]
Jax doesn't work for us because component names have pascal case and require such components to be in scope.
