### ISSUE TITLE
Link text pasting bug

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio#1697]
Pasting link text while in text edit mode gives you link text with a blank href.
(In the video I talk about what URLs are visible when hovering over the link text, those URLs were not captured by the screencapture software)

https://github.com/webstudio-is/webstudio-builder/assets/122043657/8f70c6ea-4e14-441f-98c1-cfb22b74a017

**Comment by kof** [comment]
@markxtang can't reproduce, when you copied from notion, show the content of your buffer by pasting it into any plain text editor.

It is supposed to have a markdown link. When I paste into paragraph in text editing mode, it pastes as expected that plain markdown, that looks something like this:

```
Some features that we have included are WebP-optimized images, a [workers-based](https://workers.cloudflare.com/) cloud, and efficient rendering thanks to [Remix](https://remix.run/). This Open Source React framework is designed to optimize rendering and progressively enhance [React-based](https://react.dev/) sites.
```

**Comment by markxtang** [comment]
Reproduced the bug:

https://github.com/webstudio-is/webstudio-builder/assets/122043657/9b267014-b9bc-4c27-a989-f6b4fa68076b

**Comment by kof** [comment]
Strange, when you paste it into paragraph it shouldn't even have a link at all. I can't repro it on mac, maybe it's on windows? 

can you repro it on a blank site?

**Comment by markxtang** [comment]
https://github.com/webstudio-is/webstudio-builder/assets/122043657/98f9006c-366e-4373-889c-03b1c366cc49

**Comment by blair49** [comment]
Hi @markxtang ,
From where did you add that 'Markdown Area'? I am not able to find it in the components.

**Comment by markxtang** [comment]
@blair49 'Markdown Area' isn't a component, it's a name I gave to a box. 

Last I checked, if you click on a paragraph from e.g Notion and paste the whole thing in Webstudio, the link text copies over fine. It's only when highlighting text that the link isn't copied over.

@kof can we just decide that this is expected behavior and close the issue or is this something we should solve?

**Comment by kof** [comment]
Just tested again, seems like it was fixed, please confirm
