### ISSUE TITLE
Decide how to handle image optimization and loading

### ISSUE THREAD

**Issue by SaraVieira** [webstudio-is/webstudio#171]
Since we have no control about what images the users will upload to our servers we have to make sure their websites stay fast, we have a couple of options:

- Save a buffer on the db of the same image but in much smaller format and have that as the first loaded image blurry
- Save a spectrum of colors used on that image and create a gradient that will be there until the image loads
- Save a base64 in the kv

**Comment by kof** [comment]
Idea: after uploading the image, we can make an Image instance, load it, render on canvas element, get the color data

**Comment by kof** [comment]
Apparently there is a js library that implements this kind of beautiful blur algorithmically 

https://github.com/flozz/StackBlur

**Comment by kof** [comment]
Here is a screenshot how it can be used
![](https://cdn.discordapp.com/attachments/993229517164380261/1000013468067446864/unknown.png)

**Comment by kof** [comment]
An example of such usage is here https://godly.website/website/835-solana-summer-camp-hackathon

I would try to make the colors match more closely to the original image so that the transition to the image is more soft on the eye

**Comment by SaraVieira** [comment]
My only question is what is that "lib/file"?

**Comment by kof** [comment]
Also an interesting article on LQIP https://medium.com/@imgix/lqip-your-images-for-fast-loading-2523d9ee4a62

**Comment by kof** [comment]
What we are doing here is a more beautiful version of lqip that is using SVG and scales nicely to any resolution

**Comment by kof** [comment]
Just saw this https://twitter.com/ascorbic/status/1630686697464758272
https://github.com/ascorbic/unpic-placeholder

Image placeholder using CSS like I always wanted
