### ISSUE TITLE
Support tooltips in controls without label

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio#1787]
Many our controls do not have label though we need to show for them tooltips with description and reset button

<img width="229" alt="image" src="https://github.com/webstudio-is/webstudio-builder/assets/5635476/fab93d00-d09f-406b-903d-724f52aa0838">

<img width="229" alt="image" src="https://github.com/webstudio-is/webstudio-builder/assets/5635476/b4819832-b625-4e30-bbbe-9e6109a71dab">

<img width="227" alt="image" src="https://github.com/webstudio-is/webstudio-builder/assets/5635476/4b3f3c34-1cf5-408e-bfa9-97f233da17ec">

**Comment by ajaxbo360** [comment]
i would love to take on this issue , if no one is assigned to it

**Comment by kof** [comment]
@ajaxbo360 its a bit complex, and is part of the work @TrySound has already started doing on tooltip

**Comment by ajaxbo360** [comment]
It’s ok thanks

**Comment by kof** [comment]
done
