### ISSUE TITLE
Generate sitemap

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#1827]
Todo

- [ ] generate a sitemap for search engines
- [ ] add a way to exclude a page from the sitemap (requested feature[user](https://www.youtube.com/watch?v=FO8PNlM5jt4&lc=UgwXlywBhcyndxNo5354AaABAg) )

**Comment by kof** [comment]
Question: why is excluding a page from sitemap is even relevant? Crowlers will find the page if it is linked anyways, sitemap is only helpful to find pages that aren't directly linked. 

Is this the case when you created a page that is not linked anywhere, but it would land in the sitemap if you don't actively exclude it? 

If the goal is to create a page without public access, it should have some password protection instead of being protected by not being linked and excluded from sitemap.

**Comment by tomhaerter** [comment]
Perhaps a `robots.txt` would be more suitable intended for the use case?
