### ISSUE TITLE
Add new tooltip component to controls that don't have it yet

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#1832]
- [x] Nested icon label
<img width="132" alt="Screenshot 2023-06-21 at 9 30 12 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/7749901e-a7c6-4b8a-a47b-64695b775c7e">

- [x] Spacing controls
<img width="245" alt="Screenshot 2023-06-21 at 9 31 56 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/7c78f4bb-24f8-491a-9d89-df1e17ba8a4d">

- [x] Toggle Group Buttons (These are values so the CSS will include the property + value)
<img width="142" alt="Screenshot 2023-06-21 at 9 32 58 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/9d8c7677-5c02-4902-a0d7-26b87bff3ce4">

- [x] Add panel cards (Just the title and description since these are not in the style panel)
<img width="110" alt="Screenshot 2023-06-21 at 9 35 26 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/f301f46e-d8ab-4dbe-bdbe-d49000385007">

- [x] Tabs
<img width="52" alt="Screenshot 2023-06-21 at 9 39 35 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/6a69acd2-ae79-4c51-9eb0-2706ed75b355">

- [x] Small Icon Buttons. These do not represent CSS so they don't need a reset button or value source, but they do need tooltips to describe what the control does, e.g. "Remove background" or "Hide layer".
<img width="249" alt="Screenshot 2023-06-21 at 9 40 47 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/8cee59af-e21d-450e-8645-e423c212c23c">

- [x] Everywhere else. Even if there's not tooltip content defined, let's make sure that the whole UI is using the new tooltips component so that we can add content when we are ready to.
<img width="58" alt="Screenshot 2023-06-21 at 9 36 34 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/4863a61c-afba-4395-b0d8-ff903efe110c">

**Comment by taylornowotny** [comment]
Relevant: #2027

**Comment by kof** [comment]
done

**Comment by taylornowotny** [comment]
Are we sure this is done? There are many places where the new tooltips are
not being used, like the Components panel and properties.

**Comment by kof** [comment]
@taylornowotny please check where specifically, I was of the impression its already everywhere
