### ISSUE TITLE
Ability to mark some properties as "secure" and do not expose them at the client

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio#1834]
The obvious property is Form `action`, which can have secrets etc inside.
To do that we can add secure attribute for some properties and do filtering for client-side data.

**Comment by kof** [comment]
This also falls under discussion for settings. Should it really be a property still? What if its a setting? As an external concept that doesn't mean its going through props interface and hence ins't going to be exposed?

**Comment by kof** [comment]
See https://github.com/webstudio-is/webstudio-builder/issues/1528

**Comment by kof** [comment]
So the reason you wanted this to be a prop is because in case of a Form component, you want the normal action prop to be marked as secure and not exposed to the client, so user can paste a hook in there!

Now I see the point.

**Comment by TrySound** [comment]
Action as resource will do the thing
