### ISSUE TITLE
Make css id "compressable"

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio#1835]
Currently our css can be reduced 3x in gzip/brotli by just using compressable ids.
That can be done during publish step, by simple algorithm like

```javascript
const uncompressable2Compressable = {};

for(const style of styles) {
  uncompressable2Compressable[style.id] =   uncompressable2Compressable[style.id] ?? `a${counter++}`;
  newStyles.push([uncompressable2Compressable[style.id], style.value])
}



```

PS:
Why publish step and not use compressable initially - because if we want collaborative editing we need some random ids, they can be not random but like `{user_id}_{compressable_style_id}` but above solution looks easier vs changing id generation

**Comment by kof** [comment]
- There might be a thing in between counters and long super long hashes - using only part of the hash or a different hash that is just 4-5 characters long, it has to be collision free even for a large site though
- You also need to update the ids on instances because those are in data-ws-id

**Comment by kof** [comment]
with atomic we don't really need to optimize ids
