### ISSUE TITLE
Why does the text on tab triggers look different than section titles?

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#1848]
<img width="246" alt="Screenshot 2023-06-23 at 12 28 04 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/e3627776-8952-4a7a-a57e-cf7b817a3d1a">

According to what I can tell from dev tools, these are both using 12px Inter at 700 weight which is correct. In the design they both use the same text style: "Titles".

But to my eyes it looks like the tab triggers are more bold. Is there a difference that I am missing? Or is it just me?

**Comment by kof** [comment]
-webkit-font-smoothing: antialiased;
seems to be fixing it
