### ISSUE TITLE
Add pgbouncer config

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio#1878]
- [ ] - Get connstring from supabase for pgbouncer. 
- [ ] - Add ?pgbouncer to connstring (prisma extracts it to know that it works through pgbouncer)
- [ ] - Migrations MUST USE previous connstring (migrations don't work with pgbouncer)

https://discord.com/channels/955905230107738152/955907841070346300/1123871708277907487

**Comment by alceil** [comment]
Can I work on this ? @istarkov

**Comment by istarkov** [comment]
Yes in env variables on deploy exists following conn string
`PGBOUNCER_URL=postgres://postgres:[PASSWORD]@[DBHOST]:6543/postgres`

The only thing I would ask to highly document all changes and give sources why its done like this.
