### ISSUE TITLE
box-shadow section fixes

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#1889]
There are some issues with the Box Shadow section from #1634 

- [x] Padding on the floating panel is wrong. In #1634 I asked for the top padding to be 8px instead of 16px to match the design and instead all padding was changed to 8px. Left, right, and bottom padding for ALL floating panels should always be 16px with no exceptions. I suggest making this a part of the floating panel component in code as it is in design so this doesn't come up again.
<img width="326" alt="Screenshot 2023-07-02 at 11 35 10 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/8f849c89-6bdc-498e-a090-022a49a6af95">

- [x] Remove the black border on the color thumbnail. This is not in the design.
- [x] Hide the "hide" and "remove" small icon buttons on the default state as designed and requested in #1634
<img width="555" alt="Screenshot 2023-07-02 at 11 40 34 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/8998b142-5f3d-41d8-a743-07c533485edc">

- [x] There should not be gaps between list items. This is an issue with Backgrounds also.
<img width="317" alt="Screenshot 2023-07-02 at 11 42 31 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/bfe9097d-5398-4e49-b5b1-f1a9b264d6f3">

**Comment by kof** [comment]
@taylornowotny the ColorThumb component is using the same component that color control is using, I don't remember the exact reaons but I think @istarkov should know why there was a border needed there

**Comment by kof** [comment]
> Hide the "hide" and "remove" small icon buttons on the default state

This was done, hide/remove buttons only visible on hover/active, seems like you looked at wrong pr

<img width="230" alt="Screenshot 2023-07-02 at 21 29 09" src="https://github.com/webstudio-is/webstudio-builder/assets/52824/c91bcb76-2dd9-494a-930d-eebded380394">

**Comment by taylornowotny** [comment]
The backgrounds color thumb doesn’t have the border and neither does the
design. Should be removed.

**Comment by istarkov** [comment]
I don't see any border on background layers

<img width="297" alt="image" src="https://github.com/webstudio-is/webstudio-builder/assets/5077042/d2f67366-a82d-4442-9fe9-471a44a73177">

I see it inside color selection which looks like a bug

**Comment by kof** [comment]
Then we should be able to remove that border from all the ColorThumb items and use it everywhere consistently
