### ISSUE TITLE
Tooltips use full width when Value section or Reset button shows

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#1892]
Tooltips should expand to 100% of the max-width of 208px when the "Value comes from section" and the Reset button are included.

This is a design improvement that was not in the original design docs. It will help with consistent appearances and prevent tooltips from being awkwardly skinny and tall if there's not a description.

**Comment by kof** [comment]
- set the container width to 208px (using token) that holds "Value comes from section" and the Reset button

**Comment by ditorodev** [comment]
I can take this one! @kof @taylornowotny 

I would need a bit more context tho on where exactly is this happening, is this regarding the editor? Or a component thats used inside the canvas?

**Comment by kof** [comment]
extremely sorry for ignoring this pr, seems like it got fixed in the meantime
