### ISSUE TITLE
Properties - string should be vertical layout so there's room for long property names

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#1904]
I don't know how this was broken but it might have been part of the update that made inputs turn into text areas dynamically.

A small text area on the right side looks bad. A vertical layout is appropriate here. I think this will make the dynamic text input even more functional and will not require a layout shift when changing from an input to a text area.

There is not enough room for the property label when they are side by side. This is exactly why I designed the vertical layout for string properties.
<img width="240" alt="Screenshot 2023-07-05 at 12 37 21 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/e37fd9e9-b893-44d9-bf46-f79f20baf287">

Also, long strings can overflow the container on both sides. This makes it very hard to see the value if it's long. Ideally if a string reaches the end of the input it would convert to a text area if possible. 
<img width="247" alt="Screenshot 2023-07-05 at 12 39 51 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/5f4f652c-9dd5-48e8-93c9-f5324e7fc775">

Design:
<img width="368" alt="Screenshot 2023-07-05 at 12 44 59 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/5f66e77f-abcc-415c-8fd4-0eb2db63e999">

<img width="831" alt="Screenshot 2023-07-05 at 12 45 10 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/f298335f-8774-4229-8469-d2d15d7c624b">

Figma: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=6107%3A55336&mode=design&t=ekYIsY6U5e9WjuKN-1
.

To do:
- [ ] Use the vertical layout in the design for string properties
- [ ] Fix issue of long strings overflowing the input (if not fixed by the layout change)

**Comment by kof** [comment]
was fixed long time ago
