### ISSUE TITLE
Site settings and favicon

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#1915]
- [ ] We need ability to change favicon
- [ ] Default favicon on a published site should be a different one than inside builder to see the difference

### If anyone is looking for a quick workaround until we have this feature built:

Add HTML Embed component to the canvas (put it inside a slot if you want it on every page and copy the slot instance on those pages)

How to use slots
https://webstudio.is/blog/slot-component

Put this inside slot Code property, it will set a favicon, replace the url with your own .

```html
<script>
Array.from(document.querySelectorAll('link')).map((link) => {
  if (link.rel.includes('icon') === false) {
    return
  }
  link.href = 'https://abs.twimg.com/favicons/twitter-pip.2.ico';
})
</script>
```

## Design 

https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=8349-2962&mode=design&t=8mOamUNyZBGb4gXB-0

**Comment by taylornowotny** [comment]
We don't currently have a UI for project-wide settings, only per-page settings.

Do you think we should start making a settings page outside of the Builder UI, similar to Webflow,

or do you want this to be a part of the Builder UI? Maybe a tab on the left toolbar if so. 

I would like @markxtang 's help with designing this UI so I can work on the other designs like the space/position section redesign and the bindings UI.

**Comment by kof** [comment]
I am open to suggestions. To me it feels like it should be inside builder, not sure where though.

**Comment by kof** [comment]
@taylornowotny what if we have all global project settings directly in the left side panel as a tab after pages tab?

**Comment by taylornowotny** [comment]
Sounds good to me. @markxtang can you take this from here?

**Comment by kof** [comment]
I am guessing we should consider different categories inside settings, favicon could go into "General"

**Comment by albertfourage** [comment]
You could also add website meta data for SEO: Name, Title in browser, Description, Thumbnail

**Comment by kof** [comment]
@albertfourage this issue is about favicon, title and description is already implemented in page settings, meta and social graph are described in this issue https://github.com/webstudio-is/webstudio-builder/issues/408

**Comment by markxtang** [comment]
@kof Happy to take this on, just want to know:
1. What content to include in this Global Settings tab
2. What's the prio for this issue?

**Comment by kof** [comment]
I will set it to prio:2 since its not directly part of the current Project to launch Webstudio components

**Comment by markxtang** [comment]
Updated the [Site Settings](https://www.figma.com/file/EfzZ2w94KpmUviZJSBgxCd/%F0%9F%92%AD-Webstudio-Design-Work?type=design&node-id=6062%3A31677&mode=design&t=0cFRd2W8IfVMR1ox-1) in Figma. Addressed the problem of too many save buttons with by putting it at the bottom of the panel.

Here's a video walkthrough of the prototype (sound on)
https://github.com/webstudio-is/webstudio/assets/122043657/a97e83cb-ec56-493d-83b1-0387e076099e

**Comment by kof** [comment]
Wouldn't it be more consistent if saving is done automatically like with everything else in the builder without save button? What's the reason for save button?

**Comment by taylornowotny** [comment]
> Wouldn't it be more consistent if saving is done automatically like with everything else in the builder without save button? What's the reason for save button?
> 
> Also once favicon is uploaded its probably automatically saved already, otherwise it's gonna be a bit weird logic to have it somewhere temporarily saved until its actually saved.

Got it, will proceed with autosave.

@markxtang the sticky footer is a good solution if we need to use manual saving anywhere. We will probably need this for things like content editing becuase that should be a deliberate action.

@markxtang Here's a UX question for you to solve - do we need any design for autosave? Like a "saving... saved!" indicator or something? Currently we only have the network status indicator in the top bar which only shows when there is a problem. Check out what other programs are doing with autosave designs.

**Comment by kof** [comment]
We have a fundamental philosophy in builder that everything is saved all the time, if you try to close window and its not saved it won't let you. If connection is broken - it will show you with status on the top. Assume local app behavior. We even save if connection is not stable as soon as we get connection.

**Comment by kof** [comment]
More so this behavior will at some point into a true local-first behavior, meaning we will always be able to save and sync once online. Right now if browser crashes you can loose some changes that haven't been saved or if you forcefully close it.

**Comment by markxtang** [comment]
I suppose there's no reason to have a save button. I updated the [Figma ](
https://www.figma.com/file/EfzZ2w94KpmUviZJSBgxCd/%F0%9F%92%AD-Webstudio-Design-Work?type=design&node-id=6062%3A31677&mode=design&t=g1D6fkjNLMCVDEtu-1)with the saved button removed. 

In cases where there's an error with the custom code, I figure the behavior could be the same as with the existing code text boxes (e.g. background panel / drop shadow): Give the box/text a destructive color to indicate that there's something wrong with the code.

![image](https://github.com/webstudio-is/webstudio/assets/122043657/a3c60368-3ab4-40b7-8d9e-50d3066c4211)

**Comment by taylornowotny** [comment]
Good use of the destructive variant of the text area component

I'd still like to hear your ideas for a comprehensive autosave UX. Or are you saying that you think the network indicator is enough and we don't need any more design for this?

**Comment by markxtang** [comment]
I don't think we need more design for this. I think the autosave is self-evident considering the rest of the builder works the same way.

**Comment by kof** [comment]
@markxtang open builder, disconnect internet, wait a few seconds the you will see

**Comment by markxtang** [comment]
I see

![image](https://github.com/webstudio-is/webstudio/assets/122043657/b0dd0a16-5484-4e2b-af30-411f4dc1697c)
