### ISSUE TITLE
Support styles theming

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio#1946]
Here's the idea

1. Theme object is stored in data source variable

```js
const dataSource = {
  id: '...',
  type: 'variable',
  name: 'theme',
  value: themeObject
}
dataSources.set(dataSource.id, dataSource)
```

2. Theme values are accessed with member expression.

```js
const dataSource = {
  id: '...',
  type: 'expression',
  name: 'theme.colors.bgColor',
  code: `$ws$dataSource$dataSourceId.colors.bgColor`
}
dataSources.set(dataSource.id, dataSource)
```

3. Expressions are bound to styles as unparsed values.

Since expressions can be used for props, styles and instances
Store them as string and when bind to style use unparsed type
to delegate the job to style panel.

4. Data source values are rendered as css custom properties in `:root`

Css custom properties allow us to render actual values in the root without additional styles traversing every time user changes anything.

```
:root {
  --ws-data-source--data-source-id: red;
}
```

Things to implement
- [ ] binding data source to styles with css custom properties
- [ ] member expression syntax

**Comment by istarkov** [comment]
What about color-scheme support etc ?
```
@media (prefers-color-scheme: dark) {
:root {
}
}
```

**Comment by kof** [comment]
the new plan is to use css variables and most likely to define them in a UI for all kinds of variables
