### ISSUE TITLE
Visualize bindings

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#1956]
As a user I want to see when a property is bound and see and explainer.

https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=6449-1666&mode=design&t=SASpAB8YDoak5VWy-0

1. property bound to a variable is readonly and has an info icon with tooltip
2. property that exposes a value to a variable TBD

**Comment by taylornowotny** [comment]
Design is done.

Note: This UI is for the initial release of components. The purpose is simply to make components usable in time for this release. 
This UI will be replaced in the future by the Bindings/Variables feature which is much more complex, beautiful, and will take a while before it is fully designed and implemented.

**Comment by taylornowotny** [comment]
<img width="805" alt="Screenshot 2023-08-10 at 4 07 37 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/6422be01-8897-408b-8cfe-cdfee1b26ad8">

Details explained in Figma

Figma: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=6762-5213&mode=design
