### ISSUE TITLE
Share link name saves even when the link name is empty

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [webstudio-is/webstudio#1966]
Steps:

- Click on share
- It generates a link with a `custom` name.
- Try to edit the name, and keep the name as ampty
- On `Escape` the model closes and sets the name to empty

More info can be found in the screen-recording below.

https://github.com/webstudio-is/webstudio-builder/assets/11075561/38bdc29b-2878-45e5-a0f1-06289e8fdfd3

**Comment by JayaKrishnaNamburu** [comment]
Happens on `backspace` too. Not just escape.

**Comment by kof** [comment]
Good catch, happy to merge a fix
