### ISSUE TITLE
Changing an image automatically sets an aspect ratio style, even on tokens

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio#1984]
Changing or assigning an image to an image component automatically sets an aspect ratio style.

https://github.com/webstudio-is/webstudio-builder/assets/122043657/eec9e4ec-44f3-47c9-babf-d433e499306e

**Comment by kof** [comment]
This was implemented to avoid having layout shifts automatically, so user doens't have to set widht/height on each image, but the question here is where the aspect ratio should be applied, probably on a local style source and not token, wdyt @markxtang, @istarkov ?

**Comment by markxtang** [comment]
I did an experiment to check if having the aspect ratio set fixes the layout shift (spoiler: it doesn't)

https://github.com/webstudio-is/webstudio-builder/assets/122043657/8fe5a4de-6298-445a-b7c8-17b4bd383ff1

**Comment by kof** [comment]
@markxtang the reason it doesn't work in your case is because you don't have width specified and you don't have a layout that would give the image some width, so aspect ratio doesn't know how to calculate the height

**Comment by kof** [comment]
also @markxtang can you share the view link pls?

**Comment by kof** [comment]
You don't have some flex layout in any parent element, do you?

**Comment by markxtang** [comment]
> This was implemented to avoid having layout shifts automatically, so user doens't have to set widht/height on each image

The only thing I was trying to test was whether having the aspect ratio set by default is able to "avoid having layout shifts automatically"

There is no styling applied in the parent element. As much as possible, I left things unchanged. 

Here's the build link: https://apps.webstudio.is/builder/3723efef-d68d-4700-912f-e6419236bc82?authToken=b493683d-37aa-4c2b-bef5-fd4179dd41a9&mode=edit

**Comment by kof** [comment]
fixed
