### ISSUE TITLE
Prevent self nesting by default

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2030]
Currently all components except Form allow nesting another of the same component inside. In most cases this should not be allowed, so we should make self nesting impossible by default and only allow specific components to self nest.

Note: An error state and toast UX for navigator items will be designed very soon

The error message should be: "A [component name] can not be nested inside another [component name]”
The component name should be formatted as seen in the Components panel. 
e.g. A link can not be nested inside another link

EXCEPTIONS:
(These components should allow self nesting, as far as I can tell, but feel free to contradict if you believe otherwise)
- Box
- List
- Slot
- Text
- Blockquote
- Tabs

**Comment by TrySound** [comment]
> In most cases this should not be allowed

Can be nested

1. Box
1. List
1. List Item
1. Slot
1. Text
1. Blockquote
1. Dialog
1. Popover
1. Tooltip
1. Collapsible
1. Tabs

Cannot be nested

1. Link
1. Code Text
1. Heading
1. Paragraph
1. Form
1. Button
1. Input Label

**Comment by taylornowotny** [comment]
I amended my list above to add:
- Text
- Tabs
- Blockquote

These should not be self nestable:
- List item

These I would like a second opinion on. It seems like there might be unintended problems if we have a tooltip within a tooltip, for example. @kof does it make sense to allow self nesting for:
- Dialog
- Popover
- Tooltip
- Collapsible

Also, Webflow blocks self nesting for text and block quotes. I'm not sure why but it's worth mentioning.

**Comment by TrySound** [comment]
```
List
  ListItem
    List
      ListItem
```

> response of response
> > response
> > > message

**Comment by taylornowotny** [comment]
Yes I agree that pattern should be possible. But that doesn't look like self nesting to me, that looks like a List is nested in a List Item which is totally fine. 

This is the pattern that doesn't make sense:

```
List
    List Item
        List Item
```

**Comment by kof** [comment]
So we kinda have to distinguish direct child self-nesting and decendants, button can not be nested in either way but  a list item can be nested if its not direct child ...

maybe we are better off defining on each how it is supposed to behave relative to self ... closing this, we have everything we need but we need to go over all components and see where we forgot to forbid nesting
