### ISSUE TITLE
Add checkboxes to domains in publish dialog

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio#2034]
It would be nice if we could select between domains to publish on and unpublish on a domain, without removing it from the list.

Like inside Webflow:
![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/6b7f39c2-0424-4688-bb31-82053a13f96a)
![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/1f737dc4-f48b-4cf8-bf03-e9664e76a4e6)

Figma Link: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=4452-50221&mode=design

**Comment by kof** [comment]
We are aware and need to think about this more carefully as part of the future AB testing workflow.

**Comment by johnsicili** [comment]
added https://github.com/webstudio-is/webstudio/pull/4143
