### ISSUE TITLE
Preview Shortcut shows Print Window

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio#2043]
There is an issue with our Preview shortcut (Ctrl+Shift+P) on a Windows PC and it is most likely appearing on Macs as well. It brings up the Print window.. 

The problem is that this is the same shortcut in Webflow but it does not do that there.. This automatic popup disturbs the UX (cant touch anything on screen without closing it)

I am attaching two short Videos to show what happens when I use the Preview shortcut in Webstudio and Webflow. 

Webstudio Preview Shortcut Result:
[Webstudio Preview Result.webm](https://github.com/webstudio-is/webstudio-builder/assets/136603139/d72cbdc8-0eac-4fcf-9c78-ac90dfdfaef5)

Webflow Preview Shortcut Result:
[Webflow Preview Result.webm](https://github.com/webstudio-is/webstudio-builder/assets/136603139/386e82de-c9ad-4175-ae29-cb2f9d31493a)

**Comment by kof** [comment]
Seems like its not preventhing the default, I think we could prevent the default on all shortcuts just in case @istarkov wdyt?

**Comment by kof** [comment]
there is options.preventDefault = true we can set but we don't atm, @TrySound you see any problems by setting it to true for all shorthands?

**Comment by TrySound** [comment]
Checked in both safari and chrome on Mac OS. Only Cmd+p triggers print. cmd+shift+p works fine. I guess the issue specific to windows.

**Comment by TrySound** [comment]
Looks like it
https://github-production-user-asset-6210df.s3.amazonaws.com/136603139/258567504-386e82de-c9ad-4175-ae29-cb2f9d31493a.webm

**Comment by kof** [comment]
was fixed
