### ISSUE TITLE
Image Settings detail disappears on images in Asset Panel

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio#2048]
Only in Webstudio main site:

When I select an image in the Assets Panel from Settings, it shows details/remove option in a label but then disappears abruptly.. it is a little frustrating when you are trying to read file names or delete images.

NOTE: This only happens when I try to access Asset Panel from Source in image settings. and it only happens in the Webstudio Site.

Works fine when accessed directly in main Asset Panel.

Attaching video to showcase.

Inside personal site:
[Assets Panel in Personal Site.webm](https://github.com/webstudio-is/webstudio-builder/assets/136603139/0a2aa353-10d3-491b-9436-e69eab19c094)

Inside Webstudio site:
[Assets Panel in WS site.webm](https://github.com/webstudio-is/webstudio-builder/assets/136603139/ce8e136b-bd62-491d-ba58-59b0a4d403bc)

**Comment by kof** [comment]
Can't reproduce in production. Please write bug description step by step instead of sentences
1. click x
2. hover y
