### ISSUE TITLE
Sign in section is not replaced even after user has signed in

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio#2051]
Even after I sign in to my WS account, the "Sign in" button does not go away. This is not line with behaviour on other sites. It could change to an avatar or some link taking us to WS Templates or things people have built with Webflow.

For instance Webflow replaces their "Log in" button with "#MadeInWebflow" after the user has logged in.

**Comment by kof** [comment]
We are aware, this requires a custom signin component that will check the login status and render depending on it. This requires custom code components feature OR a universal external api component that would be able to make an http call, verify signin status and return the result + binding on the text
