### ISSUE TITLE
Update Twitter logos on Webstudio

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio#2052]
The Twitter Bird Logo is dead. Change it to the new logo on Webstudio, for example on team page?

![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/64356cd7-8052-4079-8f31-c63f24a126ef)

**Comment by kof** [comment]
yes, needs an update ... sad times ... if you do it also please make sure the asset is removed in the end
