### ISSUE TITLE
EDU - List Component

### ISSUE THREAD

**Issue by itsNintu** [webstudio-is/webstudio#2057]
# How to Create and Customize a List in Web Studio

* Lists Component is used to structure and organize content within a webpage. Inside a list component, you can add list items using the ListItem Component.
* You can add List and ListItem Components to the canvas from General section in Components Panel.
* By default, the Layout > Display in Style Panel for List Items is set to List Item.
* It is possible to style your list in Style Panel and change its appearance. You can change bullet point styles, numbering formats, spacing, and text properties.
* Go to Style > List Item> List Style Type to to define the appearance of the bullet points or numbering used in list items, depending on the content's context and your design choices. Refer to the end of the outline for details on each of the 11 list style types.
* List instances come with three base properties- Ordered, Reserved and Start. You can add more properties. 
* By default, list items will be in bullet points.
* The Ordered property signifies that the list should be ordered and items should be numbered. Ordered (on will convert to numbers)
* The Reversed property  reverses the order in which list items are numbered.
* The Start property is used to set the initial numbering value for the ordered list. You can begin the list at a specific number, making it useful for scenarios where numbering should start from a custom value.

### Some use cases for the three properties:

* Ordered lists are commonly used for procedures, step-by-step guides, or any content that requires a defined sequence.
* Reversed ordered lists can be effective for countdowns, rankings, or any content that benefits from a reverse order.
* The "Start" property can be utilized to customize the starting number in ordered lists, ensuring flexibility in list design.

### List Style Types in Webstudio:
- **Disc**: This style uses filled circles as bullet points.
- **Circle**: Similar to Disc, but with an unfilled circle.
- **Square**: This style employs filled squares as bullet points.
- **Decimal**: It displays numbers as the list markers, starting with 1, 2, 3, and so on.
- **Georgian**: This style uses Georgian numerals (e.g., ა, ბ, გ) as list markers.
- **Traditional Chinese Informal**: It uses informal Chinese characters (字) as list markers.
- **Kannada**: This style uses Kannada script characters (ಅ, ಆ, ಇ) as list markers.
- **None**: If you choose this option, there will be no bullet points or numbering.
- **Initial**: It takes the value from the parent element's computed value.
- **Inherit**: The list style type is inherited from the parent element.
- **Unset**: The list style type is reset to its inherited value if it was previously set; otherwise, it's set to the default value.

**Comment by kof** [comment]
This is the list types we are supposed to get, something is broken with that type select https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type

Created an issue
https://github.com/webstudio-is/webstudio-builder/issues/2060

**Comment by itsNintu** [comment]
@kof @GoharAkram Updated with new format to keep us all on the same page in regards to where things are at. 

Visual outline added for review.

**Comment by itsNintu** [comment]
@kof Updated outline. Please approve when possible.

**Comment by GoharAkram** [comment]
# How to Create and Customize a List in Web Studio

* Lists Component is used to structure and organize content within a webpage. Inside a list component, you can add list items using the ListItem Component.
* You can add List and ListItem Components to the canvas from General section in Components Panel.
* It is possible to style your list  in Style Panel and change its appearance. You can change bullet point styles, numbering formats, spacing, and text properties.
* List instances come with three base properties- Ordered, Reserved and Start. You can add more properties. 
* By default, list items will be in bullet points.
* The Ordered property signifies that the list should be ordered and items should be numbered. Ordered (on will convert to numbers)
* The Reversed property  reverses the order in which list items are numbered.
* The Start property is used to set the initial numbering value for the ordered list. You can begin the list at a specific number, making it useful for scenarios where numbering should start from a custom value.

### Some use cases for the three:

* Ordered lists are commonly used for procedures, step-by-step guides, or any content that requires a defined sequence.
* Reversed ordered lists can be effective for countdowns, rankings, or any content that benefits from a reverse order.
* The "Start" property can be utilized to customize the starting number in ordered lists, ensuring flexibility in list design.

@kof Please review

**Comment by kof** [comment]
We used to have a few example items in the List upfront when adding a list, wf does this at least, should we fix it? @taylornowotny if yes, we can just record  the video and article as if it already is working this way and fix it before we publish them.

**Comment by taylornowotny** [comment]
Yes, I'd say it's preferable to fill a list with 3 items initially

**Comment by kof** [comment]
whats missing here entirely is list item type
<img width="226" alt="Screenshot 2023-08-30 at 02 57 16" src="https://github.com/webstudio-is/webstudio/assets/52824/ed5ff6ba-d8ad-43dd-81dd-a9a3e8a6d81b">

**Comment by itsNintu** [comment]
First video draft ready for review: https://drive.google.com/file/d/1NshgU13bGGciulta6JiDM1Qlc2oOLoZH/view?usp=sharing

**Comment by GoharAkram** [comment]
Lists Outline is updated to show List Style Types @kof 

Please check

**Comment by GoharAkram** [comment]
Issue with List Style Types: 
https://github.com/webstudio-is/webstudio/issues/2215

@kof

**Comment by GoharAkram** [comment]
Article Draft: https://www.notion.so/webstudiois/List-Component-First-Draft-d3f0fe45efd04d36bb91853efaa5043f

@kof Please check

**Comment by GoharAkram** [comment]
# Youtube Copy
YT Title: List Component

YT Description: 

The List Component is used to create lists that structure and organize content within a webpage. You can create a list in your Webstudio project with the “List” and “List Item” Components.

**Comment by GoharAkram** [comment]
## Twitter Copy

Organize your content effortlessly with Webstudio's List Component!

📋 Create structured lists.
🎨 Customize bullet styles and numbering.

📖 Guide: https://wstd.us/list-component
▶️ Video: https://wstd.us/list-component-vid

**Comment by itsNintu** [comment]
I created a couple of alternative tweets, leaving here as an in case you need (or for inspiration)

- Turn complex information into easy-to-digest points using lists. 
🎨 Tailor list and bullet styles and numbering to match your brand or message.
♿ Improve accessibility for all users, including those using screen readers. 
[thread]
📖 Guide: https://wstd.us/list-component
▶️ Video: https://wstd.us/list-component-vid

- Simplify complex data with lists. Customize list styles and numbering to reflect your brand. Enhance accessibility for all users, including those using screen readers.
[thread]
📖 Guide: https://wstd.us/list-component
▶️ Video: https://wstd.us/list-component-vid

- Transform intricate details into easy-to-understand points with lists. Personalize list designs and numbering to align with your branding. Boost accessibility for everyone, including screen reader users.
[thread]
📖 Guide: https://wstd.us/list-component
▶️ Video: https://wstd.us/list-component-vid

- Make complex information user-friendly using lists. Adapt list styles and numbering to suit your brand's aesthetic. Enhance website accessibility for all, especially those using screen readers.
[thread]
📖 Guide: https://wstd.us/list-component
▶️ Video: https://wstd.us/list-component-vid

- Break down complex data into digestible points with the power of lists! Tailor list styles and numbering to resonate with your brand identity while improving accessibility for all users.
[thread]
📖 Guide: https://wstd.us/list-component
▶️ Video: https://wstd.us/list-component-vid

- Turn complicated info into simple bullet points using lists! Customize the look and feel of your lists to match your brand while enhancing user accessibility.
[thread]
📖 Guide: https://wstd.us/list-component
▶️ Video: https://wstd.us/list-component-vid
