### ISSUE TITLE
Set alignment of drop down menu under user avatar in Dashboard

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio#2075]
The alignment of drop down menu under user avatar in Dashboard is a bit out of place. It should be a little bit to the left,

See attached vid:
[Drop-Down Menu in dashboard.webm](https://github.com/webstudio-is/webstudio-builder/assets/136603139/b3d97a49-efe0-494f-aa44-c9391e7e9927)

**Comment by faisal004** [comment]
Hi @kof can I work on this issue

**Comment by kof** [comment]
@faisal004 sure, here is the design, its a property on radix component that wasn't set https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=1322-43451&mode=design&t=k8vEmKBSBcwMK7Bx-0
