### ISSUE TITLE
Add error message when dragging is not allowed (2 conditions)

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2081]
There are two conditions when dragging is not allowed. We should show an error message in a toast for each condition. The message text should be:

1. This item is part of its parent component and can not be moved outside of the parent.
2. This item is part of its parent component and can not be moved

Related to #2080 (pri 2)

**Comment by johnsicili** [comment]
I believe this is already in the UI. Reopen if I'm wrong.

<img width="1414" alt="error" src="https://github.com/user-attachments/assets/d3632143-1136-4df4-8a76-59b4b203e011">
