### ISSUE TITLE
Add radix components

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio#2096]
- [x] Tooltip (@istarkov)
- [x] Sheet (@istarkov)
- [x] Dialog (@istarkov)
- [x] Tabs (@TrySound)
- [x] Collapsible (@TrySound)
- [x] Popover (@istarkov)
- [x] Accordion - only single (@TrySound)
- [x] Label  (@istarkov)
- [x] Select (@TrySound)
- [x] Switch (@TrySound)
- [x] Radio Group (@TrySound)
- [x] Checkbox (@TrySound)
- [ ] Slider
- [ ] ~~Progress~~
- [ ] ~~Dropdown Menu~~

Removing
- [x] Button (@istarkov)
- [x] Input (@istarkov)
- [x] Textarea (@istarkov)
- [ ] Separator

Link for testing
https://webstudio-builder-git-main-webstudio-is.vercel.app/dashboard

**Comment by kof** [comment]
Lets close this one, missing components can be added once we see demand
