### ISSUE TITLE
Assets manager future features

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#211]
Let's discuss and keep track of features that can improve the asset manager post-beta.

Definitely:
- Folders (with a great UX)
- Filters
- Communicate how images are automatically compressed/converted by WS
- Search

Maybe:

- Tags

**Comment by kof** [comment]
Big fan of tags instead of folders, this lets you essentially have the same but you can have way more flexibility with organizing them, one file can be in 2 categories at the same time, which is useful sometimes.

**Comment by kof** [comment]
cerated a
