### ISSUE TITLE
EDU - Blockquote

### ISSUE THREAD

**Issue by itsNintu** [webstudio-is/webstudio#2116]
# How to create a blockquote on your website

* Blockquote  is used to highlight quoted content within a webpage. It is useful for emphasizing text that has been taken directly from another source, such as quotes, excerpts, or references. 

* You can add blockquote to canvas from Text section in Components Panel.

* You can edit text inside the blockquote by double-clicking it.

* It is possible to style it in Style Panel and you can create a design token to reuse that style for other blockquotes.

* The "Cite" Property  attribute the quote to its rightful author or origin and maintains transparency in content.

* You can add the source's title, author, publication, URL, or any relevant information that identifies where the quote came from in the "Cite" property.

* To add a URL link as an attribution, add it inside the blockquote instance by selecting it> Properties> Cite. This will not be visible to the end-user.

* To add a Name/Title as an attribution alongside your Blockquote, add a cite element to your blockquote. Do this by adding a Text Component>Tag> Cite. 

Any value you put inside the Text>Tag>Cite will be displayed alongside your blockquote in italics

**Comment by itsNintu** [comment]
@kof Outline for review. 

@GoharAkram FYI.

**Comment by kof** [comment]
See https://github.com/webstudio-is/webstudio-builder/pull/2119 added cite prop to blockquote and cite tag to text

**Comment by GoharAkram** [comment]
# Blockquote Component (Article Outline)

what the component is and what it is used for

## How to use the Blockquote Component
1. Adding
2. Customizing

## How to attribute a Blockquote
discuss "Cite property" and

## How to reuse a Blockquote instance

slots and design token for consistent styling across project

# END

@kof Please review this outline:

1. Suggest changes/additions, if any.
2. Approve if it is okay.
3. Should we write the word "instance" in H2 headings?

**Comment by GoharAkram** [comment]
@kof Please review

First Draft of Blockquote Article: https://www.notion.so/Blockquote-Component-First-Draft-444e67d1005346f1b0de498de1522aa8

**Comment by GoharAkram** [comment]
@kof 

- [ ] Article is updated in Builder in its page and overview.
- [ ] Images are updated.

**Comment by GoharAkram** [comment]
# Youtube Copy
YT Title: Blockquote Component

YT Description: 

The Blockquote Component is used to highlight quoted content on a webpage, enhancing its impact and readability. You can use it in your Webstudio project to emphasize text that has been taken directly from another source, such as quotes, excerpts, or references.

**Comment by GoharAkram** [comment]
# Twitter Copy

The Blockquote Component is your solution for making impactful statements. 🖋️🔍

📜 Emphasize critical insights, quotes, and citations.
🎯 Direct focus within your content.
💡 Elevate your message with simplicity.
🔗 Add citations with ease using the cite property and tag.

📖 Article: https://webstudio.is/blog/blockquote-component
▶️ Video:

**Comment by itsNintu** [comment]
- Video drafted on youtube
- Video uploaded to vimeo

Updated links on twitter Copy: 

The Blockquote Component is your solution for making impactful statements. 🖋️🔍

📜 Emphasize critical insights, quotes, and citations.
🎯 Direct focus within your content.
💡 Elevate your message with simplicity.
🔗 Add citations with ease using the cite property and tag.

📖 Article: https://wstd.us/blockquote-component
▶️ Video: https://wstd.us/blockquote-component-vid

**Comment by kof** [comment]
@GoharAkram the copy is completely missing out on telling the user why they need cite attribute or cite element for. Why should user care?

**Comment by kof** [comment]
Someone posted a great article on this https://twitter.com/jen4web/status/1692174687558844630?s=20

**Comment by GoharAkram** [comment]
**It is a good practice to attribute the quoted text you use in a blockquote with the source's title, author, publication, URL, or any relevant information that identifies where the quote came from. This maintains transparency and credibility in your content. It also allows readers to verify the accuracy of the information and fosters ethical use of others' words.

You can add an attribution or citation by using the “Cite” property in your Blockquote instance settings or with the “Cite” Tag from a Text component.**

@kof I think these paragraphs sum it up well enough.. we could flip the order of the paragraphs to make it even more apparent.

* we discuss how to attribute with cite property and cite tag.
* we discuss why attribution is different.
* we discuss the different kinds of attribution and the best way to cite a source (property or tag)

**Comment by kof** [comment]
No, the text is missing the reason what the cite url is for.

**Comment by GoharAkram** [comment]
Will revise it and add some text
