### ISSUE TITLE
Product Hunt Launch Content

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2139]
PH requires us to add a description that tells them what the launch is about. It has to explain the significance of that launch, otherwise they might reject.

<img width="675" alt="Screenshot 2023-08-17 at 17 40 44" src="https://github.com/webstudio-is/webstudio-builder/assets/52824/e5234ba2-27e9-4606-bce9-2a0944ba6b9b">

**Comment by itsNintu** [comment]
@GoharAkram I've created a draft script for the launch. It might help with creating the application content. I think the main difference with my script is the "major launch" emphasis we need to present to PH.

https://www.notion.so/webstudiois/Video-Script-cdaa76002b424f19998e57c7997542f4?pvs=4

I'll connect with you tomorrow AM to answer any Q's around this too.

**Comment by GoharAkram** [comment]
Hey! Thanks for this. I start in around 3 hours. I will read up and get back to you with any questions I have.

@itsNintu

**Comment by GoharAkram** [comment]
Script looks solid! @itsNintu 

@kof How long before users can integrate any UI kits independently with Webstudio? is that the launch after this one?

**Comment by GoharAkram** [comment]
Draft: https://docs.google.com/document/d/16WCiPVY8GuT7s_t0c-8wi8nKQZZzeNWNJFhhe9uets4/edit?usp=sharing

@kof Please review

i want your initial thoughts.. wrote this over 2-3 times... but i think after your review and one more round of polishing, we should be good to go!
