### ISSUE TITLE
Show tokens autocomple menu before typing + show component tokens list always

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2156]
Problem:
Component tokens are shown in autocomplete results when a relevant value is entered in the input. The user has no way of knowing what component tokens exist, therefore they have no way of knowing what to search for. 

There should be a complete list of component tokens that the user can easily discover without prior knowledge.

Solution:
- [ ] Show the autocomplete menu before any typed value is entered - as soon as the user clicks in the input. Same appearance as when user types SPACE.
- [ ] Show the complete list of component tokens (for the selected component) in this state, when either no value or SPACE is entered in the Style Source Input. After user begins typing, then we can filter the results accordingly.

If any of this is unclear please let me know

**Comment by kof** [comment]
isn't needed, we decided to not add tokens from components
