### ISSUE TITLE
Add Tag property to Headings in components

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2206]
In the Dialog and Sheet there is a Heading component used for the title that does not have the Tag property that you would expect to see on a Heading component. This is an h2, but the user has no way of seeing that it's an h2 and without the Tag property they have no way of changing the heading level to fit their document.

If user tries to add the tag property from the props list, it is not listed.

- [ ] Add the Tag property to the initial props for the Dialog and Sheet titles. Or just replace the title with our Heading component which already has the Tag property.

**Comment by taylornowotny** [comment]
Dialog Title Settings:
<img width="237" alt="Screenshot 2023-08-28 at 11 27 57 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/a208a627-1f41-40d9-9103-1a633b321d94">

Typical Heading component Settings:
<img width="240" alt="Screenshot 2023-08-28 at 11 28 39 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/787100a0-43b5-40b4-9f68-8fc770ae0bb1">

Seems we should also provide the ID property - no reason to exclude it, right?

**Comment by ditorodev** [comment]
I can take this one 💪

**Comment by ditorodev** [comment]
Ill start working on this after the 30th of September 2023! (if i get time this week ill take a try on it)

**Comment by ditorodev** [comment]
Im solving this by reusing the current `Heading` I'll wrap it with DialogTitle as child just in case DialogTitle has anything extra or ever comes with something extra to it, also the idea to reusing Heading is to not have multiple lost implementations of a Heading element With Tag treating the current Heading as a meta-component/primitive 

Any comments? @kof @taylornowotny

**Comment by kof** [comment]
2 thoughhts: 
1. one we need to be able to reuse primitive components for reusability
2. I think @TrySound has avoided adding the base package to the dependency so far

@TrySound thoughts on this? we can't be recreating those things in every other package

**Comment by ditorodev** [comment]
> 1. one we need to be able to reuse primitive components for reusability
Is the Heading component considered a primitive?

> 2. I think @TrySound has avoided adding the base package to the dependency so far
Im Intereste on knowing why, I have toughts on it, like maybe it is good that each component is in charge of their implementations and props, without inheriting much from others, kindof how the [docs](https://webstudiois.notion.site/Webstudio-s-Architecture-an-overview-eeb35aeab1c14c7e8fa771d1c4bcceeb) talk about component libraries being independent
