### ISSUE TITLE
List Item does not inherit List Style Type value from main List Component if you set the List Item's value seperately

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio#2215]
Details:

* I set up a list with three list items.

* Then I started testing the list style types on them.

* I set the list type for the third item to Square.

* Then I set the list style type for the main "List Component" to Circle.

* It showed on the first two list items in my but not on the third one.

* To get the third list item to be "Circle", I had to first reset its value from "Square".

I think as the parent component, the value set in a list component should automatically apply to all its children once a user defines it.

Here is the video for reference:
[List Items and List Style Type.webm](https://github.com/webstudio-is/webstudio/assets/136603139/3a62f114-281f-436f-a016-5fd2e73bc68f)

**Comment by itsNintu** [comment]
If I'm understanding this correctly the behavior sounds correct, as the style of the child is more specific it overrides the styles applied to the parent. 


This is good when managing sites, keeping it easy to manage broad styles but also still be able to style individual elements.
