### ISSUE TITLE
Error pops up upon opening studio

### ISSUE THREAD

**Issue by annikorp** [webstudio-is/webstudio#2239]
It says `"Failed to execute 'querySelectorAll' on 'Document': '[data-ws-id]:has([data-ws-id="ZIeodFSq1iLdULhN4vaOx"])' is not a valid selector.` on the canvas. I try to edit the project but nothing shows up on the canvas, only this error. I've also attached the screenshot: 
![Screen Shot 2023-09-03 at 11 03 29 PM](https://github.com/webstudio-is/webstudio/assets/137914274/8c8cf1ed-64e9-475f-8d0e-cb4e80301f81)

P.S. I love that this is an open source project. Best wishes to the team!

**Comment by TrySound** [comment]
Hey. What chrome version do you use?

**Comment by istarkov** [comment]
I see the same issue only in firefox browser. Firefox is not supporting `:has` css selector.
According to this https://caniuse.com/css-has Chrome should have no issues like 1 year+. 
So yes, what Chrome version?

**Comment by kof** [comment]
It must be old chrome, we probably need to add additional check to the supported browser message and ask for an update.

**Comment by kof** [comment]
Chrome 104 that didn't have support for :has is not that old, aug 2022, so we need to expect more users having this issue and inform them using that overlay. I think its ok for us not keep not supporting it unless there is an easy alternative, also I think its an easy ask to upgrade their browser, its a good thing for users anyways

**Comment by annikorp** [comment]
> Hey. What chrome version do you use?

Hi! Apologies for the late response. I use a very old version of Chrome -- Version 103.0.5060.134 (Official Build) (x86_64)

I have an old Macbook Air bought in 2015 still on MacOS Sierra 10.12.

**Comment by kof** [comment]
@annikorp you downloaded a new chrome version and you weren't able to install it? That shouldn't be happening ...

**Comment by annikorp** [comment]
> @annikorp you downloaded a new chrome version and you weren't able to install it? That shouldn't be happening ...

Google says the new Chrome versions don't support the MacOS version this laptop has. Slack also gave up support on my browser the start of September.

**Comment by kof** [comment]
How about upgrading MacOS version?
