### ISSUE TITLE
Error in Share Link from Project Dashboard

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio#2334]
When I try to engage with the "Share Link" settings it leads to an error related to Tooltip. Also it immediately signs me out of my account.

See vid:

[tooltip error in share link.webm](https://github.com/webstudio-is/webstudio/assets/136603139/50b1fdb2-9d69-4b2e-89ce-dbcb0a81b159)

**Comment by istarkov** [comment]
Fixed in #2331
