### ISSUE TITLE
If I create a project title in sentence case, it reverts to title case in Project Dashboard.

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio#2336]
### Webflow does this:
1. Allow users to create project titles starting with either a lowercase or an uppercase start
2. No matter whether project is in lowercase or uppercase, when you delete it, you need to put in the title in all lowercases.
3. Also, when we delete a project in Webflow, spaces are replaced with hyphens (which makes a little more sense)

### In Webstudio:
1. No matter what you put in for the project title, it always goes to title case (whether it is one word or more)
2. when you delete, there is a difference:
a. If you wrote the project tittle in sentence case, you need to type that while deleting even if Webstudio rendered it as tilte case.
b. spaces need to be typed out as spaces, not hyphens

The spaces/hyphens is not the target bug but I feel using sentence case with hyphens for deleting makes more sense.

Please message below if I should make videos for all this, in case anything is unclear.

**Comment by kof** [comment]
This can be done in the same step https://github.com/webstudio-is/webstudio/issues/2335

**Comment by istarkov** [comment]
Im not getting the issue 
Delete dialog has protection and shows name in exact case.
`Confirm by typing hElLo wOrlD below`

<img width="376" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/396570ba-6ada-4730-8441-30187017a9ca">

**Comment by istarkov** [comment]
Im really not getting the issue, in delete dialog we can write any words etc. Its just accidental click protection. The words you need to enter is visible in dialog. The only thing I would fix is just use case insensitive comparison

**Comment by istarkov** [comment]
Just checked it already doesn't respect case. Think it can be closed
<img width="460" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/bda5009a-279d-45ca-88ef-5a0460b87de3">

**Comment by kof** [comment]
Seems like a non-issue
