### ISSUE TITLE
Syntax highlighting for HTML Embed code

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2359]
As a user, I want to see the code syntax highlighting for HTML Embed code property.

<img width="254" alt="Screenshot 2023-09-23 at 19 53 16" src="https://github.com/webstudio-is/webstudio/assets/52824/5372bd5f-69b0-4ecf-b8c6-e02bd8ae015f">

**Comment by kof** [comment]
@taylornowotny what was your idea on how to make that input easier to use for larger code chunks? e.g. opening in a dialog or something similar?

**Comment by taylornowotny** [comment]
Yes, like the Webflow code dialog that opens for their embed component.

**Comment by kof** [comment]
Webflow opens up a dialog when embed is thrown at the page, right? what if we want to allow it also be in settings and then expandable into a bigger view?

**Comment by taylornowotny** [comment]
The window can be opened again by clicking the gar icon on the embed
element. We could certainly have a button that opens this in settings.

**Comment by kof** [comment]
I think the automatic editor opening should be part of the quick settings dialog, so we have the same system for all components, if we can do that, we will need ability to expand the small code editor  into a larger one, this way we can always show a small one first, then expand if needed. 

If people just want to paste some snippet they don't need a large one, but if they are actually going to be editing, they can always expand
