### ISSUE TITLE
Update Export dialog to add more deployment targets

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2372]
<img width="387" alt="Screenshot 2023-09-25 at 3 30 32 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/680ab4df-ac92-4766-b2b8-cdaa6fc465b8">

Step 3 of the Export dialog is changed. A select menu is added to allow choosing from a list of deployment targets.

In the description for Step 3 there's a link to the documentation for the selected deployment target. The link text and link target should change to match the selected target.

[See the design in figma for details.](https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=7145-55747&mode=design)

Let me know if you have any questions.

**Comment by xstortionist** [comment]
how to export html / css? Is there way to output it via console? thanks.

**Comment by taylornowotny** [comment]
> how to export html / css? Is there way to output it via console? thanks.

Try this https://www.youtube.com/watch?v=eoyB9DfWdT8

**Comment by xstortionist** [comment]
> > how to export html / css? Is there way to output it via console? thanks.
> 
> Try this https://www.youtube.com/watch?v=eoyB9DfWdT8

thanks... that was faster then jimmy johns

**Comment by xstortionist** [comment]
getting no routes matches URL errors, what's odd is the HTML that it does build is not from the test landing page i created, it's from the very first thing I built over an hour ago. i'll investigate to see what's going on... surely I missed something along the ways.

**Comment by taylornowotny** [comment]
cc @kof

**Comment by kof** [comment]
> getting no routes matches URL errors, what's odd is the HTML that it does build is not from the test landing page i created, it's from the very first thing I built over an hour ago. i'll investigate to see what's going on... surely I missed something along the ways.

Did you publish your site? it's building what you have published

**Comment by xstortionist** [comment]
> > getting no routes matches URL errors, what's odd is the HTML that it does build is not from the test landing page i created, it's from the very first thing I built over an hour ago. i'll investigate to see what's going on... surely I missed something along the ways.
> 
> Did you publish your site? it's building what you have published

could never get it to work, moved on and started developing on grapejs.
