### ISSUE TITLE
AI copywriter

### ISSUE THREAD

**Issue by gsppe** [webstudio-is/webstudio#2374]
We want to create a feature to write new copy and edit current one with AI. The user should be able to select any instance and generate copy for that instance and all the text descendants in it.

- [x] #2314 Create AI copywriter chain and initial builder integration to insert text 

#### Dependencies

- [x] @taylornowotny to decide on final UI/UX (unified with other commands)
- [x] AI endpoints rate limiting

#### Potential future features

- [ ] ~~Add language selector - right now the language is inferred from the user prompt~~
- [ ] ~~Suggest editing tasks as prompt eg. fix spelling and grammar~~

**Comment by taylornowotny** [comment]
Question @gsppe - does the AI treat different text components differently? And should it?

What I mean is, what if the user has selected headings, paragraphs, links, buttons, labels, and list items - will they all be treated the same?

Certainly the user can adjust their prompt if they are generating these individually, but if multiple instances are selected it would look pretty strange to generate a full sentence on a button, or a marketing message on a label, for example.

**Comment by taylornowotny** [comment]
> @taylornowotny yes the AI treats them differently because I tell it **what** they are eg. Heading, Paragraph, Text.
> 
> Currently I am only allowing those exact 3 types of components but I can try to add other types and see what happens.

That's perfect, no change needed. Thanks!

**Comment by kof** [comment]
With the lists I guess you could check if item is text to decide if AI should touch it
