### ISSUE TITLE
Use mono text to display code in CLI and HTML Embed

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2388]
Code should be displayed in mono font. We have a "mono" text token for this purpose.

Example:
Design:
<img width="318" alt="Screenshot 2023-09-28 at 12 04 29 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/598def9d-8c8e-4854-885e-a3f851ea2c05">
Prod:
<img width="314" alt="Screenshot 2023-09-28 at 12 04 58 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/5c7a1331-78b2-4654-a4a7-f7fc423f65cf">

Please use mono text in these places:
- [x] CSS preview
- [x] CLI text inputs
- [x] Code property text area on the Embed component

If there are other places where code is displayed but mono is not used, please fix those too.

**Comment by faisal004** [comment]
hi @kof @TrySound can I work on this issue

**Comment by kof** [comment]
@faisal004 sure, take it, we have theme.fonts.mono in stitches.config and it can be passed to those inputs over a CSS prop
