### ISSUE TITLE
AI Operations

### ISSUE THREAD

**Issue by gsppe** [webstudio-is/webstudio#2418]
Implement an operation-based system to accomplish a number of edit tasks on a JSX+CSS representation of a selected Webstudio tree. 

* [x] Details at #2391 
* [x] Unify the ai endpoint with the copywriter feature (for copy we just detect the task and use the existing chain without operation)
* [x] depends on #2417 

* [x] Final user interface - @taylornowotny

**Comment by taylornowotny** [comment]
AI Command Bar UI design done and UX is documented - ready to start building.

Final touches forthcoming, but this should be more than enough to get started.

<img width="1083" alt="Screenshot 2023-10-05 at 6 07 46 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/4d263b7f-0023-4d49-8ecf-88a5c4532d21">

Docs in Figma:
https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=7500-40455&mode=design

**Comment by taylornowotny** [comment]
There is a new button variant used in this design -> https://github.com/webstudio-is/webstudio/issues/2422

**Comment by taylornowotny** [comment]
Updates to the AI design October 10 @istarkov :

- [ ] The AI icon was updated, please export and upload again
- [ ] Tooltips added to docs
- [ ] Voice UX docs updated to include transcription step with cancel button - please update to match the design
- [ ] Unique disabled state appearance for the AI button to make it look nicer against the dark bg -> [figma](https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=7579%3A43452&mode=design&t=duvZlua7xIqeUkmu-1)
<img width="573" alt="Screenshot 2023-10-09 at 4 23 14 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/87e72fce-ec70-4ba5-a876-10c5667dc3f0">

- [ ] Unique "pending" appearance for the AI button to show that generation is in progress, but the button is not interactive -> [figma](https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=7586%3A47789&mode=design&t=duvZlua7xIqeUkmu-1)
<img width="485" alt="Screenshot 2023-10-09 at 4 25 13 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/37c66898-66c8-4dde-88f5-da4228fc3457">

**Comment by taylornowotny** [comment]
Feedback Oct 9 @istarkov 

- [ ] Is this done? #2422 - if so, please check colors. The icon color in default state is not same as the design.
- [ ] The button in the left toolbar that opens the AI should not show an active state. See the docs in [figma](https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=7579%3A41559&mode=design&t=duvZlua7xIqeUkmu-1) 
- [ ] Voice recording should not clear existing text in the input, it should add it to the end. It's ok if it disappears temporarily to show the "Recording voice..." message, but it should come back after transcription is done.
- [ ] "prompts" is misspelled

**Comment by taylornowotny** [comment]
ref #2473
