### ISSUE TITLE
AI Command Bar changes 10/10

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2449]
- [x] I added a new state to the button component for disabled when the bg is dark. (ref #2448) Please add this to the component and use it for any disabled button in the command bar. The design docs are updated accordingly.
<img width="449" alt="Screenshot 2023-10-10 at 2 24 27 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/d2ef48a6-f22c-401e-a195-fd6a189c08fe">

- [x] We do not need a "cancel transcription" button since transcription is fast enough. We will disable the voice button instead while transcribing. In the future we will add an animation here but it's not a priority now.
<img width="441" alt="Screenshot 2023-10-10 at 2 28 35 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/ca663b9c-b95f-4205-b11b-540e860baaf3">

- [x] Remove the tooltip on the voice button - not necessary.
- [x] Do not show tooltips on disabled buttons.
- [x] Show "generating" tooltip 
<img width="662" alt="Screenshot 2023-10-10 at 2 42 42 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/8f551648-8ccc-499d-880f-cbffa9b404a3">

- [ ] Clicking the command bar while the menu is open should close the menu. 
- [x] When there are no previous prompts, hide the entire history section, including the heading and separator.
<img width="488" alt="Screenshot 2023-10-10 at 2 37 29 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/52d39b45-43d9-4ddb-80a4-14f5c75bbb13">

- [x] The AI button is now using the "primary" variant but the design calls for the "gradient" variant.
<img width="433" alt="Screenshot 2023-10-10 at 2 44 50 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/65b7e5b8-dbfd-4be2-8e53-afc8282ae817">

**Comment by istarkov** [comment]
> Clicking the command bar while the menu is open should close the menu.
Im not getting this. Why? We have a special menu item to open close. Why close should be so different from the open.

**Comment by kof** [comment]
> Clicking the command bar while the menu is open should close the menu.

I am not getting this too, it assumes one can't use the ai bar while the menu is open, but we should probably enable both, no? E.g. I might want to copy previous prompt or parts of them into the input

**Comment by taylornowotny** [comment]
This is not important to implement, just a small thing that I thought would make a smoother UX. Like when a modal closes from clicking the overlay instead of just the close button.

The idea is that if the user clicks the command bar they intend to either write a prompt, initiate voice, or submit a prompt. The menu isn't needed for any of that, so it saves them a click to close it automatically.

I don't see any reason why the user would want the menu to stay open while using the bar.

Previous prompts are part of the menu, not the command bar, so interacting with them would not close the menu.

**Comment by kof** [comment]
what if they opened the menu to see the history and wanted it to stay open, but then clicked somewhere? I think this can have all sorts of unintended effects
