### ISSUE TITLE
AI bugs

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2452]
## Fix before launch

- [x] speech always adds a space before prompt, needs a trim
- [x] after there was some error - we need to cancel everything AI bar is doing and return it to initial state
- [x] disable deleting body with "delete instance" prompt
- [x] double-sends AI requests
- [x] the AI commands bar should not be visible when Preview Mode is enabled
- [x] when no instance selected we should either show this in AI bar or automatically assume body
- [x] show user friendly errors in the toast, e.g. right now FUNCTION_INVOCATION_TIMEOUT shows "Unknown error" to the user
- [x] edit-styles operation - explore adding instructions about using square brackets notation when fulfilling custom style editing requests that are not possible with supported Tailwind classes

## Fix later

One thing worth keeping in mind is that at this stage it is only worth fixing core bugs, not trying to get better results or fix one offs (eg. the AI doesn't make a the background black with this prompt).

If you start to fix one offs you will likely break other things. Substantial improvements will have to come by overall improvements as described in "Future features" and "Core Architecture Improvements" here https://github.com/webstudio-is/webstudio/issues/2376

**Comment by taylornowotny** [comment]
I can write human error messages for the toasts if you list the possible errors for me.

**Comment by kof** [comment]
@istarkov @gsppe @istarkov  Let's aggregate a full list of error codes we need to render human readable messages for, edit this list and give it an explanation in your words

- FUNCTION_INVOCATION_TIMEOUT - API took too long and we decided to stop the request. I think we probably need to tell user to try again? @gsppe wdyt we should tell user in such cases?

**Comment by itsNintu** [comment]
I'm running into the "something went wrong" error when my prompt starts to get into detail. 

For example: 
- "Create a hero section" - This works fine. 
- " Create a hero section with two columns. On the left column, we will have a heading, a description, and a call to action button. And on the right column, we will have an image." - This fails. 

When it fails I get the following console error: 

```
Failed to load resource: the server responded with a status of 504 ()
builder.$projectId-OSZEMVGX.js:49 Error: Something went wrong
    at vN (builder.$projectId-OSZEMVGX.js:48:15805)
    at async D (builder.$projectId-OSZEMVGX.js:49:1750)
D @ builder.$projectId-OSZEMVGX.js:49

```

**Comment by itsNintu** [comment]
@gsppe thanks! 

I gave it a quick try by adding an empty box, selecting it and then asking AI but unfortunately I run into the same error.

**Comment by itsNintu** [comment]
When AI uses grid, could we add **row** and **column** values to the style source ui? The rest of the options are already there, adding these two would make it so users can also customize grids generated by ai. 
![image](https://github.com/webstudio-is/webstudio/assets/128840440/c4fafec2-7c03-4fcf-90a7-e808eab24fbd)

**Comment by kof** [comment]
That's def. doable before we get a proper UI for grid cc @taylornowotny

**Comment by itsNintu** [comment]
Yeah also pleasant surprise to me too this morning. 

Honestly, if we added the above and gap options I think it covers 90% of grid usage already, I would love this and get it early over waiting for a proper grid UI.

**Comment by kof** [comment]
- [ ]  it tried to put instances into an Image 
<img width="1278" alt="Screenshot 2023-10-13 at 12 29 41" src="https://github.com/webstudio-is/webstudio/assets/52824/e86d421a-3e6d-4113-bbe7-a7bd4a6710c3">

**Comment by TrySound** [comment]
findClosestDroppableTarget is generic fix but kinda doesn't fix into ai logic. You can try to reuse it's internal findClosestDroppableComponentIndex

**Comment by itsNintu** [comment]
With the latest prod deployment, I am getting 2x what I'm asking for. Demo: https://www.berrycast.com/conversations/968b782e-03da-59b8-b00a-e48155424cc5

**Comment by itsNintu** [comment]
Getting a new error with more complex prompts: 

Console: Unchecked runtime.lastError: The message port closed before a response was received.

Network: 
![image](https://github.com/webstudio-is/webstudio/assets/128840440/e3ac375c-f09b-48fa-9097-7e478fcedc8b)
![image](https://github.com/webstudio-is/webstudio/assets/128840440/3d1f5c5e-897e-4dc4-95d3-eb7bb7a4bd6b)
![image](https://github.com/webstudio-is/webstudio/assets/128840440/847a06a9-ab4f-4e55-8a5d-3a11d404712d)
![image](https://github.com/webstudio-is/webstudio/assets/128840440/de374858-b497-453f-88f0-62340e380ee6)

**Comment by itsNintu** [comment]
In trying to get it to generate a background image it fails but does not tell me why. Nothing seems to happen. 

This is on prod

Demo: https://www.berrycast.com/conversations/b716ed9d-411c-535d-b20f-aefa0e347c7d

**Comment by itsNintu** [comment]
Thanks @gsppe. 

Here's another one, AI seems to always target the box that is contained when asking to change the background color. 

https://www.berrycast.com/conversations/65445c85-b0d6-5577-9f2e-b4c3e52e88b2

**Comment by itsNintu** [comment]
Prompt: Create a hamburger menu using radix sheet component

Returns: 
"Error
Could not get meta for component "@webstudio-is/sdk-components-react-radix:Sheet""


Console: 
` Error: Could not get meta for component "@webstudio-is/sdk-components-react-radix:Sheet"
    at h2 (builder.$projectId-FKMCE2TI.js:33:13953)
    at b2 (builder.$projectId-FKMCE2TI.js:33:17674)
    at du (/build/_shared/chunk-UICIJ4KI.js:6:19466)
    at Ba (/build/_shared/chunk-UICIJ4KI.js:8:43659)
    at Ua (/build/_shared/chunk-UICIJ4KI.js:8:39459)
    at Vf (/build/_shared/chunk-UICIJ4KI.js:8:39390)
    at qr (/build/_shared/chunk-UICIJ4KI.js:8:39250)
    at Qo (/build/_shared/chunk-UICIJ4KI.js:8:36419)
    at pn (/build/_shared/chunk-UICIJ4KI.js:6:3250)
    at /build/_shared/chunk-UICIJ4KI.js:8:34024
c @ /build/_shared/chunk-EHX7Y6UX.js:1
 Error: Could not get meta for component "@webstudio-is/sdk-components-react-radix:Sheet"
    at h2 (builder.$projectId-FKMCE2TI.js:33:13953)
    at b2 (builder.$projectId-FKMCE2TI.js:33:17674)
    at du (/build/_shared/chunk-UICIJ4KI.js:6:19466)
    at Ba (/build/_shared/chunk-UICIJ4KI.js:8:43659)
    at Ua (/build/_shared/chunk-UICIJ4KI.js:8:39459)
    at Vf (/build/_shared/chunk-UICIJ4KI.js:8:39390)
    at qr (/build/_shared/chunk-UICIJ4KI.js:8:39250)
    at Ii (/build/_shared/chunk-UICIJ4KI.js:8:35673)
    at Qo (/build/_shared/chunk-UICIJ4KI.js:8:36474)
    at pn (/build/_shared/chunk-UICIJ4KI.js:6:3250)
c @ /build/_shared/chunk-EHX7Y6UX.js:1
 Error: Could not get meta for component "@webstudio-is/sdk-components-react-radix:Sheet"
    at h2 (builder.$projectId-FKMCE2TI.js:33:13953)
    at b2 (builder.$projectId-FKMCE2TI.js:33:17674)
    at du (/build/_shared/chunk-UICIJ4KI.js:6:19466)
    at Ba (/build/_shared/chunk-UICIJ4KI.js:8:43659)
    at Ua (/build/_shared/chunk-UICIJ4KI.js:8:39459)
    at Vf (/build/_shared/chunk-UICIJ4KI.js:8:39390)
    at qr (/build/_shared/chunk-UICIJ4KI.js:8:39250)
    at Ii (/build/_shared/chunk-UICIJ4KI.js:8:35673)
    at Qo (/build/_shared/chunk-UICIJ4KI.js:8:36474)
    at pn (/build/_shared/chunk-UICIJ4KI.js:6:3250)
xi @ /build/_shared/chunk-UICIJ4KI.js:8
 React Router caught the following error during render Error: Could not get meta for component "@webstudio-is/sdk-components-react-radix:Sheet"
    at h2 (builder.$projectId-FKMCE2TI.js:33:13953)
    at b2 (builder.$projectId-FKMCE2TI.js:33:17674)
    at du (/build/_shared/chunk-UICIJ4KI.js:6:19466)
    at Ba (/build/_shared/chunk-UICIJ4KI.js:8:43659)
    at Ua (/build/_shared/chunk-UICIJ4KI.js:8:39459)
    at Vf (/build/_shared/chunk-UICIJ4KI.js:8:39390)
    at qr (/build/_shared/chunk-UICIJ4KI.js:8:39250)
    at Ii (/build/_shared/chunk-UICIJ4KI.js:8:35673)
    at Qo (/build/_shared/chunk-UICIJ4KI.js:8:36474)
    at pn (/build/_shared/chunk-UICIJ4KI.js:6:3250) Object`

**Comment by kof** [comment]
@itsNintu reproduced it too @gsppe any chance you can fix it?

**Comment by itsNintu** [comment]
Also getting an error when trying to use the radix navigation menu: 

"Error
`NavigationMenuContent` must be used within `NavigationMenuItem`

Prompt: 
Create a navigation bar with two columns, the left column has a link and an image inside of it, the right column has a radix navigation menu and CTA link beside it.

**Comment by kof** [comment]
@itsNintu reproduced it too @gsppe @TrySound any ideas? The problem is that some components have requirements to be used as children of some other components, how can we enforce this?

**Comment by itsNintu** [comment]
I think AI broke the publishing function of my site. 

When trying to publish I get "Publish Failed"

When visiting the site it says "Worker not found"

Site url: https://waitlist-222222.wstd.io/

**Comment by istarkov** [comment]
<img width="1000" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/b76e1e15-178e-48dd-a132-5ccea3faf111">

Something with radix

**Comment by itsNintu** [comment]
> <img alt="image" width="1000" src="https://user-images.githubusercontent.com/5077042/275421860-b76e1e15-178e-48dd-a132-5ccea3faf111.png">
> Something with radix

Ah yes that makes sense. I did try to generate a menu at some point. 

In that case i think this can be ignored as we're disabling radix + ai for now.

**Comment by kof** [comment]
@TrySound @gsppe can this issue be closed or is there things we need to create separate issues for?
