### ISSUE TITLE
AI Command Bar improvements 10/13

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2473]
- [x] Add placeholder text: Welcome to Webstudio AI alpha
- [x] Remove the shortcut temporarily since we haven't decided on one.
- [x] Add new middle paragraph to Welcome message and new button: "Share feedback" (@kof where should this go? Where do you want to receive feedback?)
<img width="539" alt="Screenshot 2023-10-13 at 11 26 19 AM" src="https://github.com/webstudio-is/webstudio/assets/86495896/d121a1ef-58aa-4a7c-918b-0f36d6a2e8bf">

- [x] Change the variant of the "Cancel" button from neutral to dark-ghost for a better appearance. Design is updated in figma.
<img width="450" alt="Screenshot 2023-10-13 at 12 13 21 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/50a5d17f-c560-42d2-8c78-6ece2dec4d63">

- [x] Please show the enabled AI button while placeholder text is visible. This helps the AI feature look more interesting and discoverable. The button still won’t do anything without a prompt and will still be disabled when voice recording/transcribing or in the error state.
- [x] Please place the scroll bar centered in the margins of the menu rather than overlapping the buttons.
<img width="262" alt="Screenshot 2023-10-13 at 11 35 37 AM" src="https://github.com/webstudio-is/webstudio/assets/86495896/b9dc0b9f-3c74-4a1c-bf7a-3de29a78731c">

- [x] Display previous prompts with the newest at the top. Currently the oldest is at the top of the list.
- [x] Add a tooltip to previous prompts (not instant; normal delay)
<img width="534" alt="Screenshot 2023-10-13 at 12 24 08 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/72552243-ef19-4068-ba88-5befdbd792ff">

Figma: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=7500-40455&mode=design

**Comment by taylornowotny** [comment]
One more thing

If the user has their mic turned off in the browser, can we disable the voice button and show the "mic-off" icon?
<img width="67" alt="Screenshot 2023-10-13 at 12 35 44 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/b4ec1341-747c-4172-b34a-29452e83d4bd">

**Comment by istarkov** [comment]
> If the user has their mic turned off in the browser, can we disable the voice button and show the "mic-off" icon?

What this mean? How I van turn of mic in the browser

**Comment by istarkov** [comment]
This?
<img width="365" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/3c561f6f-1d62-4a6a-81cd-5a537eb24f2c">

**Comment by taylornowotny** [comment]
> This? <img alt="image" width="365" src="https://user-images.githubusercontent.com/5077042/275027746-3c561f6f-1d62-4a6a-81cd-5a537eb24f2c.png">

Yes. The first time the mic is accessed, the browser will ask for permission. Users might have revoked permission in the past and will need some visual indication that they need to enable it in their browser (as opposed to their OS).

**Comment by istarkov** [comment]
Until we ask we don't have this information. Moreover if user unblock mic - we don't know that mic is unblocked, we need to ask again

**Comment by taylornowotny** [comment]
> Until we ask we don't have this information. Moreover if user unblock mic - we don't know that mic is unblocked, we need to ask again

Understood, I will remove it from the design
