### ISSUE TITLE
Webstudio AI Launch List

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2490]
## Oleg

- [x] update wording on the landing ph message (we want to reflect the prompt party)
- [x] make sure we link to waitlist everywhere
- [x] write the launch tweet
- [x] adding initial prompts

## Alex

- [ ] add promo video to landing and ph
- [ ] add short demo videos channel to YT and ph

## Mark

- [ ] once Alex adds video to landing, please check them

## Artjom
- [ ] prepare list of active users for outreach on twitter
- [ ]  write the copy write email

**Comment by taylornowotny** [comment]
Oleg
- determine the keyboard shortcut for opening/closing the AI Command Bar
- (optional) determine keyboard shortcut for initiating voice recording while a text input is focused

**Comment by taylornowotny** [comment]
Oleg
- connect "Learn more" link to intended destination
- connect "Share feedback" link to intended destination

**Comment by markxtang** [comment]
Mark: 
- Create new video thumbnail image for the landing page. Planning to have a more UI focused image like on the home page
![image](https://github.com/webstudio-is/webstudio/assets/122043657/d11bff3d-65be-4a11-859d-9ee60f4c3ddd)
![image](https://github.com/webstudio-is/webstudio/assets/122043657/14ce2751-4c31-42bb-9d4c-2bbf6ead1a82)

**Comment by taylornowotny** [comment]
Taylor
- add UI to choose type: image, text, or layout
- add related instructions including slash commands, if applicable (waiting on confirmation)

**Comment by taylornowotny** [comment]
@istarkov 

- [ ] Add placeholder text from the design. Currently says: "Enter value..." but should say "Welcome to Webstudio AI alpha!"

**Comment by taylornowotny** [comment]
@istarkov 

- [ ] For each of the example prompts that are initially in the prompt history, please add this text to the beginning: "(example)" so the user can tell the difference between their prompt history and the examples so they don't get confused. This text should not be part of the prompt, just the text on the button.

**Comment by istarkov** [comment]
@taylornowotny having that we show menu initially that looks like 2 welcome, whats too much
<img width="519" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/465905be-1e78-49ed-adc0-912c691d346e">

**Comment by taylornowotny** [comment]
> @taylornowotny having that we show menu initially that looks like 2 welcome, whats too much 

Well I originally intended the menu to be closed initially, and we might revert to that, so the placeholder text was a clear way of saying "This thing is the AI". I think we should keep it unless we have a better idea.
