### ISSUE TITLE
(bug) Undo/redo does not affect adding/removing Properties

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2505]
Steps to recreate:
1. Open settings panel on an instance
2. Add a property
3. Undo -> nothing happens
4. Delete the property
5. Undo -> nothing happens

If a user accidentally removes a property they added and can't undo that action, they could lose the value that they had set for that property. Depending on the situation this could be a major frustration.

- [ ] Make undo/redo work with adding/removing properties.

**Comment by kof** [comment]
@TrySound seems like undo is actually happening, but we don't update the controls
