### ISSUE TITLE
Add duplicate page

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio#2516]
Users need to be able to duplicate pages along with body styles to setup new pages with same design faster.

**Comment by taylornowotny** [comment]
3 ways to duplicate a page with its contents:

1. Right click context menu with copy and paste options (no cut)
2. Standard C & V shortcuts with a page selected
3. Duplicate page button in page settings

Link to figma design with duplicate page button:
https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=344%3A53342&mode=design&t=CvBDli3HNPh0jxPY-1

**Comment by taylornowotny** [comment]
@kof I agree it would also be good to have an easy way to copy a page's contents to a new page

Webflow pros will often wrap their whole page in a div just to make it easy to copy/paste.

I have two solutions:
1. Implement multi-item select in the Navigator. Users can simply select everything inside the Body, copy, then paste in a new Body.
2. Allow copying the Body. When pasted, everything INSIDE the Body is pasted, but never the Body itself. No conflicts this way.

**Comment by kof** [comment]
@TrySound cmd+c/v doesn't work, when you are on a page, you have selected an instance, so copy applies to the selected instance. Additionally we can't select a page to copy it, click on page opens it and closes the pages panel.

But I think its totally ok to just use context menu for this only.

**Comment by kof** [comment]
One option could be to make the three dots to open menu first where you have copy, duplicate, paste, remove, edit and when user hits edit they see the full settings, which they see by clicking on it right now

Downside - opening settings would be 2 clicks

**Comment by kof** [comment]
> @kof I agree it would also be good to have an easy way to copy a page's contents to a new page
> 
> Webflow pros will often wrap their whole page in a div just to make it easy to copy/paste.

why are they not just duplicating the page?

> 
> I have two solutions:
> 
> 1. Implement multi-item select in the Navigator. Users can simply select everything inside the Body, copy, then paste in a new Body.

yeah, this would solve a lot of cases

> 2. Allow copying the Body. When pasted, everything INSIDE the Body is pasted, but never the Body itself. No conflicts this way.

its tricky, because body can have styles and props, if you copy it, its not clear what will happen with them, in theory they should be copied as well, but if the destination has something, it would be a weird mixture, unpredictable.

If we don't copy them - copying body basically doesn't copy body, which is weird too
