### ISSUE TITLE
Fix breakpoints shortcuts

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2520]
Issue: Breakpoints shortcuts (1, 2, 3, etc) are not changing the canvas size as expected. Clicking the buttons does correctly change the canvas size. Without the canvas change it can be very easy to not notice that a breakpoint has changed which can be disastrous, especially considering how easy it is to activate these shortcuts.

Solution: I suggest removing the KB shortcut to activate a breakpoint.
These are very easy to activate by mistake. For example, trying to type a number without an input selected. It shouldn't be so easy to unintentionally change breakpoints bc there's risk the user will not notice, then do their work on the wrong breakpoint, which leads to losing their work.

If we want to keep the shortcuts, then they should be changes to two-key shortcuts and the canvas must change size as expected when the breakpoint is changed.

**Comment by kof** [comment]
Clearly a bug

**Comment by taylornowotny** [comment]
Yes, but I also think the simple number shortcuts are too easy to mistakenly activate as I explained. I would rathter these be two-key shortcuts or not have shortcuts for BPs at all.

**Comment by kof** [comment]
I am confused, its webflow who does a simple number, we do cmd + number
