### ISSUE TITLE
Box Shadow UI

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2523]
<img width="485" alt="Screenshot 2023-10-24 at 11 10 28 AM" src="https://github.com/webstudio-is/webstudio/assets/86495896/5f3cb148-e1b2-419a-ae3a-b50426191d9e">

The Box Shadow docs have been updated. There is now a design for the menu so users can adjust their box shadows without code. Please read the new docs carefully to notice all the changes.

Most important: "The code and the UI should be synced. This will be very valuable for the user. If valid code is pasted, the UI should change to reflect the pasted values. If the UI values are changed, the code text should change to reflect the UI values."

Figma: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=4512-49938&mode=design

**Comment by kof** [comment]
@lalitkumawat1m this is a quite complex one, requires knowledge of many design system parts + CSS parser. Would you like to start contributing with something simpler?
