### ISSUE TITLE
Gitbook / User KB

### ISSUE THREAD

**Issue by itsNintu** [webstudio-is/webstudio#2541]
To help improve the onboarding experience whilst maintaining community transparency/contribution we have decided to host our knowledgebase on GitBook/Github. 

The KB will be broken down into the following sections: 

### Basics

- [x] **Overview**. Similar to what posthog does [here](https://posthog.com/docs), this page serves as a welcome/home to the KB and helps direct users to the right place. 
- [x] **Intro**: An introduction to webstudio, what it is, what we do. Kept simple and high level for maximum inclusivity
- [x] **Building your first site**: Beginner video intro that walks through the complete process from first signup to published site. 
- [x] **Roadmap & Links**: Our core links

### University: 

- [x] **Foundation**: Core learnings to use webstudio; Anatomy of the Webstudio Builder, Design Tokens, Publishing & Custom domains. 
- [x] **Core Components**: Webstudio's core components: Link, Image, List, HTML, Form, Vimeo, Blockquote, Slot. 
- [x] **Marketplace**: How-tos on all webstudio "addons"; Plugins (Webstudio AI), Templates, UI Kits (Radix), Form integrations (N8N). 
- [x] **Self-Hosting & CLI**: How to self host and use the cli; Vercel, Netlify. 
- [x] **How-Tos:** Bite sized how-to lessons. In the future this will be broken down into categories. 

### FAQs: 

- [x] **List of FAQs**

### Contributing: 

- [x] **For Designers**
- [x] **For Developers**

**Comment by scr2em** [comment]
very interesting

**Comment by itsNintu** [comment]
- [ ] add godaddy to domain tutorial

**Comment by itsNintu** [comment]
Updated Gitbook with all feedback from last call. 

Next I need to finish adding content and we are good to release

**Comment by itsNintu** [comment]
Documentation has now been launched and is live on docs.webstudio.is 

We will continue to update this as we grow educational content and with community contribution.
