### ISSUE TITLE
Memorize last selected token per instance

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2575]
In response to user feedback. Local token is selected initially when any instance is selected. If a user doesn't want to work on Local, that means they are always manually selecting the token they want. This can be tedious, especially if you're switching between instances or breakpoints frequently. It'll really slow down an otherwise quick workflow.

Solution:
- [x] memorize the last selected token on each instance

This way, the token that is initially selected will always be one that was most recently used on that instance, making it more likely to be the intended selection.

Someone who uses Local often will still have the same workflow, and people who don't use Local often will have a greatly improved workflow.

**Comment by kof** [comment]
@taylornowotny would you remember the token state too or only the selected token?

**Comment by taylornowotny** [comment]
only token selection, pseudostate should reset when instance or token is
deselected. ie. user should never see the styles of a hover state on the
canvas if they are not currently styling (or hovering).
