### ISSUE TITLE
UX fix - Make dashboard cards a single link, not two

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2601]
Currently, clicking the image on a card will open the project, but clicking the bottom of the card will open the published site if there is one.

This is not the intended UX and it is causing confusion for our users (ref: https://github.com/webstudio-is/webstudio-community/discussions/64#top).

- [ ] Make the whole dashboard card open the project. For both templates and projects.

How will the user quickly access the published site? For templates they don't need to. For projects, we will improve the card with a clear button to open the published site. It must be clearly distinct from the rest of the card which opens the project.

**Comment by kof** [comment]
Its not the entire bottom of the card, its the link to the published site, maybe it could be fixed by highlighting on hover the link specifically? Right now it doesn't have hover so it makes it look like you can click anywhere at the bottom

**Comment by taylornowotny** [comment]
Yes that would work also. We have a text link component in code iirc

**Comment by kof** [comment]
I think we just somehow broke the hover/focus state on that link
