### ISSUE TITLE
Outline Section UX improvement based on feedback

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2602]
We want to separate the Outline section from the Borders section to avoid users mixing them up. Ref: https://discord.com/channels/955905230107738152/1048308525673238558/1172577629883351101

- [x] Order the Outline section after the Effects section
- [x] Hide all properties except Style until a Style value is selected

Figma designs have been updated to reflect the last point.
<img width="331" alt="Screenshot 2023-11-11 at 9 54 45 AM" src="https://github.com/webstudio-is/webstudio/assets/86495896/a52d3e50-1426-4f35-8a04-c8720e477c39">
https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=6031-54988&mode=design

**Comment by ShyanRoyChoudhury** [comment]
can I get this issue assigned to me?

**Comment by kof** [comment]
@ShyanRoyChoudhury go for it

**Comment by JayaKrishnaNamburu** [comment]
@kof going to take this, or should i wait ?

**Comment by ShyanRoyChoudhury** [comment]
> @kof going to take this, or should i wait ?

OMG. I must have missed this. @JayaKrishnaNamburu can I complete this one.

**Comment by JayaKrishnaNamburu** [comment]
Yes, feel free to go ahead 👍🏽
