### ISSUE TITLE
Tooltip Duration Field UI Overlap

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#2620]
Radix tooltip duration field overlaps with label.

Related: https://github.com/webstudio-is/webstudio/issues/2131

<img width="236" alt="tooltip" src="https://github.com/webstudio-is/webstudio/assets/93934362/0b13175a-aa62-4b4d-885f-a281441331a4">

**Comment by JayaKrishnaNamburu** [comment]
Looks like it is fixed now, and the names and labels don't appear on the same line anymore.
![Screenshot 2024-01-11 at 18 53 31](https://github.com/webstudio-is/webstudio/assets/11075561/dc5eef3e-d66b-488d-bc18-1acbd4e72abf)
https://github.com/webstudio-is/webstudio/blob/main/apps/builder/app/builder/features/settings-panel/shared.tsx#L267-L287

```jsx
if (label.props.children.length <= 8) {
    return (
      <HorizontalLayout label={label} deletable={deletable} onDelete={onDelete}>
        {children}
      </HorizontalLayout>
    );
  }
  return (
    <VerticalLayout label={label} deletable={deletable} onDelete={onDelete}>
      {children}
    </VerticalLayout>
  );
```
