### ISSUE TITLE
🛍️ Template Marketplace

### ISSUE THREAD

**Issue by itsNintu** [webstudio-is/webstudio#2627]
The Template Marketplace for Webstudio will be a resource for finding and selling top-notch website templates. 

We're also allowing designers and developers to list their own original templates with opportunity to retain 100% of the profits from every sale. 

The goal is to create a win-win situation: users gain access to a diverse range of professional templates, while creators benefit from a direct and profitable sales channel.

**Comment by itsNintu** [comment]
Some good examples that currently exist in the market: 

- https://framermarketplace.com
- https://www.framer.com/templates/
- https://www.ycode.com/templates
- https://www.flowbase.co
- https://webflow.com/templates

Minimum requirements: 

**On catalog page:** 
- Browse templates (no categories needed for v1 launch)
- Template cards with: Featured image, Title, price
- CTA to submit a template

**On template page:** 
- Template title
- Template short description
- Template author name + link (author can select where this links)
- Template preview btn + link
- Template purchase btn + link (author can select where this links)
- Template long description
- Template features
- Template pages
- Template support info
- CTA to create your own template

**Template submissions page:** 
Two examples I like for this below
- https://www.framer.com/templates/submit/ 
- https://www.ycode.com/templates/submit

**Template submissions form:** 
- Embed a typeform (nicer experience) with all required questions.

**Comment by studiolj** [comment]
it's possible to create. feature Framer to webstudio Copy/Paste ? its will be so  amaizing ! Because i would like design irresistible website like framer :)

**Comment by irg1008** [comment]
I am sorry but where can I access this marketplace?

**Comment by TrySound** [comment]
@irg1008 
<img width="291" alt="image" src="https://github.com/user-attachments/assets/8514f491-711b-41dc-84b8-577dfd5c7439">

**Comment by irg1008** [comment]
Oh I thought so. And the templates are the ones listed there, those 4? I thought It was a marketplace to seel your own ones

**Comment by kof** [comment]
@irg1008 you can share your template from project settings
