### ISSUE TITLE
♻️ Redirects Manager

### ISSUE THREAD

**Issue by itsNintu** [webstudio-is/webstudio#2650]
The redirects manager will help in simplifying redirecting traffic from any URL to a new one, ensuring that visitors and search engines are directed to the correct pages.

**Comment by JayaKrishnaNamburu** [comment]
The initial iteration of Redirects management is added in
#2779 in the UI
#2824 for deployments

These mark all the redirects that users are adding under project settings as `301`. But we should still allow users to mark a specific redirect as `302` if needed. And it will be added in a new PR.

**Comment by kof** [comment]
Done, releasing today
