### ISSUE TITLE
Webstudio Affiliate Program

### ISSUE THREAD

**Issue by itsNintu** [webstudio-is/webstudio#2670]
I want to introduce an affiliate program and lay the foundations for influencer/UGC marketing. 

**What the program includes:** 
- Manual affiliate approval
- 50% recurring commissions for all affiliates (in line with industry)
- Works on both lifetime and MRR sales
- Integrates with our current payment setup (stripe + n8n)

**Platform:** 
After trialing many platforms I have decided to go with tolt.io
They're a stripe partner and have by far the best pricing for saas startups. 

**Steps needed for integration:** 

- [x] Setup Tolt.io account
- [x] Connect to stripe account
- [ ] Add team to account (oleg + ivan)
- [ ] Add tolt script to webstudio
- [ ] Send Referral ID to Stripe
- [ ] Test and go live
- [ ] Annonce via email + socials
- [ ] Reach out to YouTube affiliate list
- [ ] Apply to add Webstudio to popular affiliate networks like shareasale
- [ ] Apply to add Webstudio to popular influencer UGC networks like izyu

I'll need some help with the two integration steps.

**Comment by itsNintu** [comment]
@kof can you:  

- [ ] approve of tolt.io (we have discussed the platform before, this is the one you shared with me). 
- [ ] accept the invitation to join the account
- [ ] help me with integration part or assign to Ivan

As soon as this is connected I will begin rollout.

**Comment by kof** [comment]
Joined it, what needs to be done for integration?
