### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2677]
The Search feature is here! LMK if you have any questions

![image](https://github.com/webstudio-is/webstudio/assets/86495896/bbede669-ea62-47a3-b3ed-97c37f886d20)

Docs in Figma: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=9234-12138&mode=design

<img width="813" alt="Screenshot 2023-12-12 at 9 53 17 AM" src="https://github.com/webstudio-is/webstudio/assets/86495896/bea2338c-bfbc-4a49-8cdc-aa74520a4db8">

Component in Figma: https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=6979%3A6437&mode=design&t=c7CneEgQdJubU6AE-1

**Comment by kof** [comment]
duplicate https://github.com/webstudio-is/webstudio/issues/1696
