### ISSUE TITLE
[Image Component] Default image should be hidden when image src attribute have a value

### ISSUE THREAD

**Issue by ThinhVu** [webstudio-is/webstudio#2708]
<img width="303" alt="Screenshot 2023-12-21 at 11 11 59 AM" src="https://github.com/webstudio-is/webstudio/assets/8122962/c8beccfa-bd56-4c33-9474-7c140e9d31be">

**Comment by TrySound** [comment]
Please share project link

**Comment by ThinhVu** [comment]
> Please share project link

https://apps.webstudio.is/builder/a428d817-31b4-4d40-869a-93810a76d829

**Comment by TrySound** [comment]
The problem here is that you use background-image style which is not supposed to be used on Image component. See there is not source here
<img width="242" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5635476/261104cb-b29e-4584-b343-71ecee7f506a">

**Comment by ThinhVu** [comment]
So if I want to use an image as a background then I need to use it with Box component. Thank you.
