### ISSUE TITLE
Incorrect generated css

### ISSUE THREAD

**Issue by ThinhVu** [webstudio-is/webstudio#2709]
In the editor panel, even though the margin is set to 0px, max-width is 'none' but the generated css added some weird value which lead to incorrect display.

![1](https://github.com/webstudio-is/webstudio/assets/8122962/3beaec0d-917e-40cf-ab7e-182e25429a21)
![2](https://github.com/webstudio-is/webstudio/assets/8122962/d5a9a6c2-9202-4e10-a6ab-b0e2efd56144)
![3](https://github.com/webstudio-is/webstudio/assets/8122962/4cfa1954-2cd7-4c66-901c-bdbe0c7dac5a)

**Comment by TrySound** [comment]
Please share the project link so we could debug this

**Comment by ThinhVu** [comment]
> Please share the project link so we could debug this

https://apps.webstudio.is/builder/a428d817-31b4-4d40-869a-93810a76d829

**Comment by TrySound** [comment]
Please use share panel to create the link with permission
<img width="347" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5635476/037159f5-f2bb-45a9-94f0-ffd0699067f9">

**Comment by ThinhVu** [comment]
Sorry, my bad.

https://apps.webstudio.is/builder/a428d817-31b4-4d40-869a-93810a76d829?authToken=30ffa124-b185-4e1b-99d2-f6fda209f7c6&mode=preview

**Comment by TrySound** [comment]
All seem correct. You do have max-width and margin auto but not on the List but on its parent which you highlighted in devtools.
<img width="1680" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5635476/e45add44-1d16-47ca-91ab-37771fa289e7">

**Comment by ThinhVu** [comment]
Oh. It's seem like I dragged the ListItem into incorrect position (inside Text component). I don't even realize that because when I click the list item in UI, the list is selected.

Thank you for clarify it.
