### ISSUE TITLE
How to add gradient colors to Text? No option for gradients in typography

### ISSUE THREAD

**Issue by iUnknownAdorn** [webstudio-is/webstudio#2725]
I created a box, and under the box, created a heading.
I can change the color of the Text, but cannot add gradient color to the Heading text.

I am really trying to create a gradient neon effect for my headings in the larger project.

Please see the screenshot.

![Screenshot 2024-01-01 at 10 59 35 PM](https://github.com/webstudio-is/webstudio/assets/8273366/b6b9db83-f261-4d23-976f-7c251f41cc6c)

**Comment by kof** [comment]
Hi, this isn't a bug, please use discussions instead https://github.com/webstudio-is/webstudio-community/discussions

1. You don't need to create a Text instance inside the Heading, you can. write text directly in the Heading
2. To see the background gradient, you need to set color to transparent
