### ISSUE TITLE
Undo & Redo fails for `Atomic CSS` in settings.

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [webstudio-is/webstudio#2801]
## Description

Undo and Redo are currently not effecting the values in the project settings. As you can see from the repro below, the UI seem to generate patches. But it's not reflecting the same.

![Undo : Redo Bug](https://github.com/webstudio-is/webstudio/assets/11075561/21d5878c-9a96-4344-9bb1-ad603f4051ba)

**Comment by kof** [comment]
Turns out we never treated settings as something that can be updated from the outside, so we need to subscribe to the stores and treat each section or even each control as a separate form

**Comment by kof** [comment]
We decided that settings dialog doesn't need undo/redo
