### ISSUE TITLE
Error introduced by the new Dashboard thumbnails feature

### ISSUE THREAD

**Issue by simonc** [webstudio-is/webstudio#2841]
Hi,

I'm currently trying to run the project locally and successfully got a running instance but I can't create a project, getting an error page stating:

```
Error


Invalid `client.project.create()` invocation in
.../packages/project/lib/db/project.js:44:43

  41 const projectId = uuid();
  42 await authorizeProject.registerProjectOwner({ projectId }, context);
  43 const project = await prisma.$transaction(async (client) => {
→ 44   const project2 = await client.project.create(
Foreign key constraint failed on the field: `Project_previewImageAssetId_id_fkey (index)`
```

If I'm correct, this new constraint was introduced a few hours ago in #2836 (cc @kof). Maybe it works for existing projects and not new ones, or something like that.

Thanks! ❤️

**Comment by kof** [comment]
did you run migrations?

**Comment by simonc** [comment]
I did run the migrations yes 😊 Just rolling back two commits and everything works.

**Comment by kof** [comment]
thank you, luckily you caught it before it went to production

**Comment by simonc** [comment]
Glad I could be useful 😊
