### ISSUE TITLE
How to integrate Google Analytics in prod?

### ISSUE THREAD

**Issue by lyra-white** [webstudio-is/webstudio#2875]
Hello, and thank you for an awesome project. I think it saved me more than a month's time.

I have two questions:

1. How to integrate Google Analytics in the generated website? Below one fails.

From generated site, my `root.tsx` looks like this:

`export { Root as default } from "@webstudio-is/react-sdk";`

I think I should do something like:

```
// root.tsx
import { Root as OriginalRoot } from "@webstudio-is/react-sdk";

const RootWithGoogleTagManager = (props) => {
  // Add your Google Tag Manager script here
  const gtmScript = `
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-XXXXXXXX');
  `;

  // Render the original Root component and include the script
  return (
    <>
      <OriginalRoot {...props} />
      <script dangerouslySetInnerHTML={{ __html: gtmScript }} />
    </>
  );
};

export default RootWithGoogleTagManager;

```
Just tried this, but this does not work. It renders the page, and within split of a second, it turns blank.

I have added other meta tags to the pages, and probably I can add gtag as a meta as well. I also know that there exists Embed HTML block. I think I will have to do it on every page.

2. What else is needed to make the website prod quality? 

I only had to just change the favicon really, but wondering if there is any checklist for pushing the website to prod. For my hosting environment, I am going to host the website on a VPS by doing something like [this](https://stackoverflow.com/questions/76592857/basic-deployment-of-remixjs-app-using-ssr-with-nginx/77442441#77442441).
So if you have any tips for making the generated website live on VPS, I am all ears.

I apologize if advance if this is a stupid question. I am fairly new to the frontend world and this is actually my first website.

**Comment by kof** [comment]
You can't put analytics scrip into project settings?

**Comment by lyra-white** [comment]
@kof Oh dang! It was this easy. I worked on root.tsx to get it working. I feel so dumb. I did not know project settings existed and I am at the end of development. Thank you.

Do you have any tips for publishing the website to VPS? I don;t want to spend extra couple hours if there is an easier way. 

So I built a static site. And now, I am going to copy
copy `build`, `public/build`, `package.json` to my VPS.

There, I will simply `npm install && npx remix-serve build/index.js &> /dev/null &`

Do you think this will work?

I will close the issue soon.
