### ISSUE TITLE
After removing the www subdomain, the URL stay published

### ISSUE THREAD

**Issue by kecyf** [webstudio-is/webstudio#2948]
Hey, I'm on Webstudio Cloud and I think I ran into a particular issue. 

I have a website where I previously added 2 domains :

- domain.com
- www.domain.com

Seems like a bad practice because it published 2 websites with the same content. So I removed the www from Webstudio, and made a redirect to root domain with Cloudflare. I published the latest version only to root domain, which is working. 

The problem is that my previous version is still live on www with the old content (cf screen) and I have not control over it from the builder, when I publish my new homepage, the root domain updates and the www stay the same.

It looks like the DNS settings did not disconnected my www subdomain the right way ?

![CleanShot 2024-02-26 at 16 59 09](https://github.com/webstudio-is/webstudio/assets/87739453/b6b66b68-c250-4bab-bfff-aa1d127323d1)

**Comment by kof** [comment]
If its not linked, it should have been deleted after a periodic cleanup. Did it not delete it for you? Please reopen the issue if you still see it.
