### ISSUE TITLE
Code Editor improvements

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2956]
- [x] performance issues with large amount of code (attempt to edit 1mb+)
- [ ] limit our rendering  to X amount of KB?
- [ ] limit the amount of data a Resource is allowed to fetch to ensure good UX, warn the user! (same limit?) Currently users are unknowingly fetching megabytes and wondering why its slow
- [x] enable tab key
- [x] enable cmd/ctrl+a  and cmd/ctrl+c/v combination
- [x] When using the expanded expression editor to drill down into an object, the window closes when clicking on one of the auto complete options.
- [x] apparently ctrl+x on windows deletes the instance instead of text in code editor https://discord.com/channels/955905230107738152/1212607157594366002

**Comment by TrySound** [comment]
>  enable cmd/ctrl+a and cmd/ctrl+c/v combination

it always worked, can't reproduce problems with it. Only ctrl+x was broken

**Comment by kof** [comment]
@TrySound if we don't do some of these, lets decide if we need to do them later and create a separate issue so we can close this one

**Comment by kof** [comment]
remaining tasks https://github.com/webstudio-is/webstudio/issues/3625
