### ISSUE TITLE
New style panel UI controls

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2977]
- [x] filters (text version)
- [x] text shadows ui https://github.com/webstudio-is/webstudio/issues/3292
- [x] backdrop filters (text version) 
- [x] filters UI https://github.com/webstudio-is/webstudio/issues/3291
- [x] backdrop filters (ui version)

**Comment by JayaKrishnaNamburu** [comment]
Text Shadows - text version #3318 
Backdrop Filters - text version #3317

**Comment by kof** [comment]
Done
