### ISSUE TITLE
Paste styles

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3050]
As a user, I want to be able to copy/paste all styles an instance has without the instance itself. This includes tokens and local styles.
Holger from community just mentioned that photoshop has a "Paste Special" menu that allows to choose what exactly needs to be pasted.

Bringing this pattern to Webstudio, we should:

1. Add "Paste Styles" to the context menu with a shorthand (e.g. cmd+shift+V)
    <img width="216" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/9e062313-06de-41ec-81a8-2c58d7b2c3db">
2. Add a context menu in the navigator on the instance item with the same item
3. Add a context menu in the style source input with the same item

Prior art from photoshop

![image](https://github.com/webstudio-is/webstudio/assets/52824/eb971436-17c6-4bbc-b3a1-474b5f5dd418)
![image](https://github.com/webstudio-is/webstudio/assets/52824/5b1b1a90-550d-4881-aa0c-b742c606596e)
![image](https://github.com/webstudio-is/webstudio/assets/52824/a0341dcb-c213-4d46-b926-d0f2b9a996db)

**Comment by johnsicili** [comment]
Closing in favor of this issue: https://github.com/webstudio-is/webstudio/issues/3540

One of the items is " add copy context menu on instance to click Copy CSS / Paste CSS" which seems to be the same case for this issue.
