### ISSUE TITLE
Enable users to build searches and filters

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3060]
As a user, I want to be able to build a directory with search and filters. We have already enabled using URL search params as a variable inside resource, now the last piece is to enable testing that on canvas.

A typical UI for filters is a form where user can use select boxes, checkboxes and inputs to filter the collection.

To enable this, the simplest way would be to create a Form and send it with method=get, which would place all form values as part of URL search. This is the default browser behavior.

The problem is this would reload the canvas.

Lets figure out how we can submit the form without reloading canvas and allowing filter to work.

**Comment by oslogrolls** [comment]
typesense.org is nice
