### ISSUE TITLE
Binding issues

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio#3080]
- [x] - Pressing "Down" button moves focus out of dialog

upd: comes from ArrowFocus listening arrow keys while another element is focused

<img width="736" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/69718e14-1a11-4e48-98b0-98199c59ce10">

- [x] - Paste for example `system.search.blabla` into any expression editor it will not be found
<img width="502" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/7c413fc8-c460-4d00-888c-fc0f1c1b25ff">

- [x] - Clicking on variable deletes the whole text instead of insert
<img width="315" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/98f7ebe2-ec26-49c8-bdef-9dc848358cbe">

- [ ] - Variable used in bindings (I can't find where it's used)

upd: added hint with amount of usages

<img width="339" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/bad89e94-96e5-4bea-9a61-d3afb156af48">

- [ ] - ~~No expression live preview, nothing changes on the canvas during edit~~
<img width="530" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/7127c2c6-3b5d-4e1b-92bd-5b690ee5f18e">

- [ ] - If Value on Select control was changed there is no way to reset it (it's always empty string "") instead of undefined
That gives us no ability to change it at all on published site
<img width="318" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/b6908da3-7e1b-4ca7-8150-2e1a9ddad8da">

- [ ] - Select control has bug, changing defaultValue (when value is undefined) does not cause select to change, it works like input only if key is set
<img width="251" alt="image" src="https://github.com/webstudio-is/webstudio/assets/5077042/b5b68e75-ac62-46f3-9272-411ef8888a47">

**Comment by TrySound** [comment]
>  - Pressing "Down" button moves focus out of dialog

cannot reproduce
