### ISSUE TITLE
Self-hosting

### ISSUE THREAD

**Issue by fatherofinvention** [webstudio-is/webstudio#3084]
Hi team. The docs are pretty clear on how to install the webstudio CLI to link/sync/build projects from the cloud, but I can't find anything on hosting the designer/builder itself so I can create projects locally. Is that possible?

**Comment by TrySound** [comment]
Hey. We don't have clear path to self host builder at the moment. There is a lot of infrastructure to setup for it. Though you can run webstudio in development mode locally.

https://github.com/webstudio-is/webstudio-community/blob/main/docs/contributing/contributing-for-developers.md

**Comment by jo-chemla** [comment]
Would you be ok to keep this thread open while a self-hosting doc is not yet ready for the builder (pre-built images on ghcr/docker-hub + docker-compose stack)?

**Comment by johnsicili** [comment]
@jo-chemla Follow this issue: https://github.com/webstudio-is/webstudio/issues/3966

**Comment by jo-chemla** [comment]
Thanks for the link, interesting issue!
