### ISSUE TITLE
Make it easier to copy a curl example into resource

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3087]
Currently user has to copy url and headers and potentially more params individually from a curl example most platforms use, but we could actually parse a curl string and make it a single copy/paste action for the user, this way it would prevent a lot of mistakes, e.g. user copying backslash because they don't know its a new line symbol.

That paste event could work in the url input

**Comment by TrySound** [comment]
https://github.com/lukeed/mri
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText

**Comment by TrySound** [comment]
what tools support copying curl?

**Comment by kof** [comment]
apparently every api service has at least one version for each endpoint that demonstrates it with curl, starting with supabase and airtable
