### ISSUE TITLE
Use single underscore instead of two for TXT record

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3124]
Even though its totally legal to use 2 underscores, some providers like OVH don't allow it (their mistake) and we are left with users who have to deal with this.

To fix it we discussed to use single underscore and keep supporting existing two underscores naming

https://www.rfc-editor.org/rfc/rfc1464.txt

https://github.com/webstudio-is/webstudio-community/discussions/131

https://discord.com/channels/955905230107738152/1220680898245169164

**Comment by nathan-de-pachtere** [comment]
Same issue with IONOS. Glad you are working on that.
