### ISSUE TITLE
RTE Link deletion crashes canvas

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3127]
## Repro

1. Add a paragraph
1. Add a link
1. Make sure to link it to a page
1. Backspace the link inline (deleting it in the navigator works fine)

https://github.com/webstudio-is/webstudio/assets/52824/8b297092-7c6f-43e7-b656-0548c0c378a4

**Comment by TrySound** [comment]
looks like remix links do some quirky magic under the hood, we might wanna render simple anchor inside builder
