### ISSUE TITLE
Add support for min()/max() CSS functions

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3203]
Seems like the problem is in our parser https://github.com/csstree/csstree/issues/164#issuecomment-1223111277
It doens't have a support for min/max functions and the issue is open since 2021

**Comment by TrySound** [comment]
It is supported by parse but not supported by lexer. Specifically for advanced panel I suggest whenever invalid value is entered try to parse with builtin parser and if can be parsed put into "unparsed"

```js
    try {
      CSSStyleValue.parse(cssPropertyName, value);
      return true;
    } catch {
      return false;
    }
```
