### ISSUE TITLE
Use Remix routes for panels

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio#329]
We should use Remix routes for panels like Assets or Pages to reduce both data loading and bundle sizes. 

- Opening a panel should navigate to something like `/designer/{projectId}/pages-panel`
- Closing the panel should navigate back to `/designer/{projectId}/`

**Comment by rpominov** [comment]
This should be considered together with #360 . Because if we won't use Remix loaders, the only reason to use routes for panels is optimising bundles, but that can be done easier with dynamic imports.

**Comment by kof** [comment]
I think you don't want to loose automatic bundle splitting. I think we only want to optimize the initial load by not inlining the data. We should be able to bail out of inlining the data on initial render, I even think this is trivial to do.
