### ISSUE TITLE
Box shadow is set but isn't listed in the layers

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3294]
Here is a repro https://apps.webstudio.is/builder/7bdea1b5-202f-43dd-8891-579b7e9803e4?authToken=bed1507d-8217-4844-b998-728e598beb6c&mode=preview

You can copy it into local  env to work on it locally

1. Click on Use Case container
2. Select Neon Card token
3. See box shadow is there but its not being listed in the layers

<img width="263" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/12da2770-39bd-4da9-bfb4-6bc53ef1a254">

**Comment by JayaKrishnaNamburu** [comment]
Can you help with the steps to copy the project into local please, never tried it before. Would be very helpful for future too.

**Comment by kof** [comment]
Just copy/paste the instance

**Comment by JayaKrishnaNamburu** [comment]
Oh, that's cool. Didn't know it works like that 🔥

**Comment by JayaKrishnaNamburu** [comment]
<img width="792" alt="Screenshot 2024-05-06 at 17 05 27" src="https://github.com/webstudio-is/webstudio/assets/11075561/d2648c44-ee92-404d-b23c-0d714cf7ecda">

The `Neon Card` card somehow seems to saved `unparsed` value. And that's the reason box-shadow is showing as `blue`. I tried reproducing a multiple times but could'nt. Are there any specific steps to reproduce the same by any chance.

**Comment by JayaKrishnaNamburu** [comment]
I think i might have a hunch on why this is happening. When users add values from the `Advanced Tab` they are being saved as `unparsed`. But the style-panel at the same time, parses them and stores as internal data representation using `layers` / `tuple`.

So ideally, we should not allow users to add values for elements that have controls in style panel. Or allow users to add them, but parse them to data-layer but show using `toValue` in the advanced panel for the UI

cc @kof , @TrySound

**Comment by kof** [comment]
> So ideally, we should not allow users to add values for elements that have controls in style panel.
Hmm, yeah all complex values in Advanced panel are unparsed, basically its all encoded in StyleValueInput

I see 2 options:
1. obviously parsing when possible correctly is the best (question is how fast can we add that)
2. even if it got an unparsed value, it probably shouldn't lead to "broken" ui state, so an additional check in the corresponding section might be required too

**Comment by JayaKrishnaNamburu** [comment]
Ideally, we need both the things. Because, lets' see users are already adding `backdrop-filter` from the advanced tab. And we added it in the style-panel down the line. Then the projects that already used the feature from advanced tab will still have issues. Will try to make a quick PR adding those two. Will be a good fix to go inside before `background-filter` and `text-shadow` goes in.
