### ISSUE TITLE
Script tag in Project Settings doesn't get compiled

### ISSUE THREAD

**Issue by dvago** [webstudio-is/webstudio#3378]
I'm trying to install the Google Tag in my project as per the following screen:

![project-settings](https://github.com/webstudio-is/webstudio/assets/5074033/05b670b3-cacf-4597-9936-b4018f165491)

I suspect there is a bug because when syncing the project using npx webstudio and deploying it with npx vercel, the entire content of the Project Settings is wiped out.

Could you please provide a solution that doesn't involve hacking the script tag into the body tag?

Thanks.

**Comment by kof** [comment]
Just checked out your website https://www.davidevago.com/ - love it

**Comment by dvago** [comment]
> Just checked out your website https://www.davidevago.com/ - love it

Thanks @kof, just started a few weeks ago from one of your templates, nothing major but good enough :-)

**Comment by TrySound** [comment]
https://github.com/webstudio-is/webstudio/issues/3188
