### ISSUE TITLE
[Bug] Missing action for asset manipulation

### ISSUE THREAD

**Issue by bali3355** [webstudio-is/webstudio#3382]
The Webstudio app UI don't make asset delete action real, only acts a placeholder. To be able to delete the item, you have to delete it from 'Asset' page.

To remake this, just place an image, go to the settings, then try to delete asset from the 'Choose source' option.
![image](https://github.com/webstudio-is/webstudio/assets/12228795/d7842361-9619-4765-9738-603802826b6b)

**Comment by kof** [comment]
Assets can be deleted from asset manager, image instance on canvas is not the asset, its the instance using the asset, hope this makes sense.
