### ISSUE TITLE
Equal tokens shouldn't be duplicated

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3417]
From the [chat](https://discord.com/channels/955905230107738152/955905231227609158/1243699225267798047):
 
> I have a master project where I add new tokens. Then, I start a blank project and copy a few things I've created (for example, a call-to-action). The CTA will have tokens like "flex," "margin-xl," etc. If I now copy another item from my master file, it copies the "flex" token in again if I've reused it. 

We could check if the token with exact same name and properties already exists and not duplicate it but use an existing one

Currently we compare them by id, so if the copied token is from the same origin, it will have the same id, otherwise its possible to have identical token but different ids and so they would get duplicated

**Comment by johnsicili** [comment]
Closing in favor of https://github.com/webstudio-is/webstudio/issues/3490

Reopen if you disagree
