### ISSUE TITLE
Visiting Marketplace template URL throws unexpected error for unauthenticated users

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3446]
As a user I want to preview a marketplace template and may be logged out/not a user because I stumbled on this in documentation or a video.

1. Go to Marketplace
2. View details about the project
3. Copy the Open Project URL
4. Paste in incognito window

Here's one: https://apps.webstudio.is/builder/d606d380-194b-4824-ac13-14250cebb67d

<img width="982" alt="error" src="https://github.com/webstudio-is/webstudio/assets/93934362/3c8a0dd8-0095-446c-838e-a7547611f988">

_Marking as Prio 1 because I'm linking to this in public facing docs/videos_

**Comment by istarkov** [comment]
Fixed on dev https://github.com/webstudio-is/webstudio/pull/3460
