### ISSUE TITLE
Default Collection box can't have components inserted

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3473]
https://github.com/webstudio-is/webstudio/assets/93934362/94efde6c-9d0e-4bd7-85f4-38b01675a704

Repro:
1. Add a collection
2. Try adding a component to one of the default boxes (I tried both heading and paragraph – both failed)
3. Note the error: heading cannot be inserted in heading

It will work if you delete the default box and add a new box

**Comment by TrySound** [comment]
Looks like it is because Box is text container and collection item is not a real element. But even with the fix for collection item it would put inserted instance after the box not inside of it. Should we use this structure instead?
```
Collection
  Box
    Text {Collection Item}
```
