### ISSUE TITLE
Tooltip delay removed when doing things other than hovering over tooltip trigger

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3477]
I've finally narrowed down some odd behavior where tooltips "randomly" trigger when the cursor moves over them (no delay).

https://github.com/webstudio-is/webstudio/assets/93934362/8aeb02d3-9aa3-4248-8ded-ba8a3f089d98

1. Open a binding
2. Hover over the Info icon in the binding
3. Zero delay

It's not just the binding tooltip though...
1. Open a binding
2. Close the binding
4. Hover over any tooltip (info icon or no info icon)
5. Zero delay

And it doesn't need to be in that order...

https://github.com/webstudio-is/webstudio/assets/93934362/1b16fa74-8308-4dfc-bdcb-8cde5fe56817

1. Open a binding
2. Close the binding
3. **Click around on the canvas**
4. Hover over any tooltip
5. Zero delay

**Comment by kof** [comment]
I have a feeling it has to do with portal

**Comment by johnsicili** [comment]
Here is another example:

- Open page settings
- Click into field
- See no delay

https://github.com/webstudio-is/webstudio/assets/93934362/d44b85c2-8d5b-428a-bd17-f7961c9cbe0f

**Comment by johnsicili** [comment]
Ah actually I'm wrong about the above!! It's triggered because hovering over the input field for x amount of seconds (whatever the delay is) triggers it!! Maybe same thing with bindings... being in the field for 5 seconds make it think you are hovering over the tooltip!

**Comment by johnsicili** [comment]
Another scenario

- Open pages
- Quickly hover over page setting icons
- Removes delay

https://github.com/webstudio-is/webstudio/assets/93934362/a4df8475-8c9e-4dc4-9059-24df9ca0078c

**Comment by johnsicili** [comment]
This video is a good demonstration of how frequently this issue happens in regular day use

https://github.com/webstudio-is/webstudio/pull/3961#issuecomment-2295373759

**Comment by kof** [comment]
setting prio:1, I think our tooltips are very annoying and we need to not only fix these bugs but also increase the delays when they actually work correctly to stop seeing them unintentionally.
