### ISSUE TITLE
Support Markdown as Content Embed

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3485]
Markdown allows to turn any text field into rich text, so every database  or backend suddenly becomes a CMS with a decent content editing experience.

Alternatively it could be a separate component e.g. Markdown

**Comment by paulrudy** [comment]
Could we expect this to work with markdown content that includes image links or html embeds such as `<video>`?

If so, it would be great to also be able to easily use links or embeds for assets within the Webstudio site, when applicable.

**Comment by 360Creators** [comment]
For the time being this might help until it's supported.
https://www.youtube.com/watch?v=PAoxZjICd7o
