### ISSUE TITLE
Backgrounds panel issues

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3511]
- [ ] jump when switching between image and gradient https://share.descript.com/view/gRPo8AORr7N
- [x] when choosing an image after having a url, url is normally being reset, so you don't have both, now I managed to have both 
    ![image](https://github.com/webstudio-is/webstudio/assets/52824/aafe8bd1-1df4-498c-9017-214d9e4b3a49)
- [ ] shouldn't all properties land in the Code area? not just the url()?
- [x] Code area label should be Code

**Comment by johnsicili** [comment]
Another thing

- [ ] Gap is missing between the image and field on a smaller screen (height). Bogdan says because `flex-shrink: 0` is missing

<img width="492" alt="image-gap" src="https://github.com/webstudio-is/webstudio/assets/93934362/ae04232e-97bc-44bf-b402-b8be076a0a89">

**Comment by JayaKrishnaNamburu** [comment]
Hey @johnsicili this is fixed in https://github.com/webstudio-is/webstudio/pull/3512 yet to reach release 👍
