### ISSUE TITLE
favicon.ico not matching project icon?

### ISSUE THREAD

**Issue by abustany** [webstudio-is/webstudio#3521]
I have a webstudio cloud project deployed to https://www.rapmed.net , but the favicon is somehow not the correct one but the stock webstudio one. The "icon" link inside the source code is fine however... I tried hacking around with a redirect (hosting favicon.ico somewhere else), but that also didn't work... Is this a bug or a feature?

**Comment by kof** [comment]
We are already aware and investigating the issue.

**Comment by kof** [comment]
fixed by https://github.com/webstudio-is/webstudio/pull/3527

releasing soon
