### ISSUE TITLE
Assets don't delete when pressing delete from certain areas

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3524]
Assets deletion works fine in the asset panel but not in other areas such as image components or site settings.

https://github.com/webstudio-is/webstudio/assets/93934362/05d40243-882d-449c-bd3c-221b62df9959

1. Make sure asset panel is closed
2. Go to img component
3. Click source
4. Try deleting asset

Observations:
1. Deleting from non-asset panel while asset panel is open makes images delete first try
2. Sometimes they delete with two clicks, other times they won't delete at all.

Areas to check:
- [ ] Asset panel
- [ ] Image component
- [ ] Favicon upload and management
- [ ] Background image
Maybe others too.

**Comment by istarkov** [comment]
Already fixed
