### ISSUE TITLE
Incorrect Current Page link state on dynamic pages

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3560]
Original report https://discord.com/channels/955905230107738152/1250819202961510500

When using a dynamic page with a slug, Current Page is not matching the page

## Steps
1. create a dynamic page /test/:slug
2. create a link with Current Page state styles on it and link it to /test
3. publish, go to the /test/anything
4. see link doesn't have Current Page styles

**Comment by istarkov** [comment]
This is remix router behavior, not sure what we need to do
https://github.com/remix-run/react-router/issues/8696
