### ISSUE TITLE
Save only transition longhands in style panel

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio#3567]
We rely on longhand style properties to generate atomic styles without collisions.
When save both shorthand and longhand it's not deterministic what overrides the other
especially in visual builder where you can't just move code.

So we need to switch "transitions" in style panel to longhand properties.
- accept both shorthand and longhands in transitions section
- always write longhands into data
- give longhands more priority

Longhands is either single common value or multiple values per animation name. When amount of values not matching animation name list it is considered invalid.

This way we gracefully migrate to longhands without huge migration.

**Comment by JayaKrishnaNamburu** [comment]
Well, i understood the requirement. But it's going to be little tricky for the changes. According to the UI for users it should be a individual layers. But when the save them, We should be saving them independently.
Eg:
Currently when users add
![Screenshot 2024-06-17 at 11 21 23 AM](https://github.com/webstudio-is/webstudio/assets/11075561/c6482c34-1a02-4608-9ee9-e17963defeba)
gets saved as 
```css
transition:  opacity 200ms ease, width 200ms cubic-bezier(0.12,0,0.39,0)
```
So, we parse the `opacity 200ms ease` or `width 200ms cubic-bezier(0.12,0,0.39,0)` individually and show them in the UI. But now the panel should be doing it like 

```css
transition-property: opacity, width;
transition-duration: 200ms, 200ms;
transition-timing: ease, cubic-bezier(0.12,0,0.39,0)
```
 And then we parse and save it in the UI using the indexes right.
