### ISSUE TITLE
Validate dot in the property name

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3573]
A user used "x-on:click.prevent" and it broke jsx compiler because it doesn't support it. Now the only way to compile to jsx is to use object spread.

**Comment by TrySound** [comment]
Dots should be validated away in ui. We cant support other feameworks

**Comment by kof** [comment]
Turns out dot is invalid in attributes in HTML5, so we will not support it too.  What we need is to validate it and not let it through.
