### ISSUE TITLE
Log in with Auth secret for Developers.

### ISSUE THREAD

**Issue by alpiyev99** [webstudio-is/webstudio#3576]
Can't log in with Auth secret for Developers

I just put 2a631fa293dbef1f3fef2d8e565bd8f434cf980b2b5c0ce4b2221402b9e5000d in Auth secret form
![Снимок экрана 2024-06-16 в 20 04 47](https://github.com/webstudio-is/webstudio/assets/124505479/2a0e1e5d-918c-4c16-8f9d-8d049de78940)

<img width="623" alt="Снимок экрана 2024-06-16 в 20 07 27" src="https://github.com/webstudio-is/webstudio/assets/124505479/f301d35a-e8e8-4235-8403-ab33f5d4daa7">

**Comment by kof** [comment]
use first 4 chars (we know this is bs solution)

**Comment by alpiyev99** [comment]
It is still not working
![Uploading Снимок экрана 2024-06-17 в 15.25.29.png…]()

**Comment by kof** [comment]
I can't tell much more than it should work, given the information you presented.

**Comment by kof** [comment]
We use it every day.

**Comment by kof** [comment]
Check that you use either .env or .env.development
