### ISSUE TITLE
Test Edge Workers against changes in designer

### ISSUE THREAD

**Issue by andrasbacsai** [webstudio-is/webstudio#358]
We need to make sure if we change something in the designer's repository, it won't break the edge version.

## Steps for manually testing
1. Publish Edge version automatically based on git changes: [PR](https://github.com/webstudio-is/webstudio-saas/pull/15) 
2. Every time a new PR is opened in this (designer) repository, notify Saas repository with a `repository_dispatch` github actions event. This should trigger a build & deploy step of the `edge-preview & edge-worker` apps.
3. Be able to publish unfinished (rc) versions of our packages, so they can be used in the edge version.

## Open questions
1. The Designer should have a hardcoded sub-domain for the published sites. We could reuse `VERCEL_URL` env variable, parse the random Id generated by Vercel, and set the published site's subdomain to be for example: 

`webstudio-designer-3tua6no8u-webstudio-is.vercel.app` -> published sites subdomain should be `*.3tua6no8.wstd.work`, so all published sites would be below this subdomain. Example: `andras-working.3tua6no8u.wstd.work`

Is this a good way to do it?

2. As all PR's will have a separate worker, we need to clean up old workers. We can do it by sending an event in case  `pull_request:closed` is triggered. 

Not sure if we will know all information for the cleanup.

## Steps for automated tests
1. We need automated (shared) tests for the shared components, so we can import them in SaaS repository and run them.

**Comment by andrasbacsai** [comment]
@kof Updated the description, could you please take a look?

**Comment by kof** [comment]
> This should trigger a build & deploy step of the edge-preview & edge-worker apps.

Would trigger a separate worker that is only used for preview, right? I think its worth mentioning maybe along with a link to worker impl

**Comment by kof** [comment]
>  We can do it by sending an event in case pull_request:closed is triggered.

Is there a way to have optionally a max lifetime in case the pr closed hook fails for whatever reason?

**Comment by istarkov** [comment]
MB Cloudflare pages for preview deployments are a better choice.
They are +-same as workers and support any amount of deployments to be active. Using wrangler we can set up aliases etc 
```      
wrangler pages publish \
--project-name ${project} \
--branch ${SUBDOMAIN} \
--commit-hash ${commit_sha} \
--commit-message "blabla" \
./build
```
No need in cleanup as its so easy to fail on cleanup, and can be deployed for every commit.
The only issue with pages is no runtime variables - all must be build time.

**Comment by andrasbacsai** [comment]
> > We can do it by sending an event in case pull_request:closed is triggered.
> 
> Is there a way to have optionally a max lifetime in case the pr closed hook fails for whatever reason?

No, but we can do a cleanup with a script.



> MB Cloudflare pages for preview deployments are a better choice. They are +-same as workers and support any amount of deployments to be active. Using wrangler we can set up aliases etc
> 
> ```
> wrangler pages publish \
> --project-name ${project} \
> --branch ${SUBDOMAIN} \
> --commit-hash ${commit_sha} \
> --commit-message "blabla" \
> ./build
> ```
> 
> No need in cleanup as its so easy to fail on cleanup, and can be deployed for every commit. The only issue with pages is no runtime variables - all must be build time.

I'm not sure how this would help in our case. We need to test the edge-worker + edge-preview along with any changes in the designer, so we can test if we broke something and we need exactly the same worker as in production, otherwise we cannot fully test everything.

**Comment by istarkov** [comment]
Pages worker has the same api as workers and basically, it's a worker. Has KV and DurableObjects. Also PR previews can be a little bit different vs production, but here they will not. Same code, but a different deployment target. Instead of workers allows having under same name any amount of deployments.

Also the allows to deploy static assets and process them without any need of worker code like reading assets from KV (or from ASSETS in worker) and that assets are really fast.
https://developers.cloudflare.com/pages/platform/functions/routing/#creating-a-_routesjson-file

Has caching, don't need cleanups. The only issue is runtime env variables. Probably not that bad to use on production too.

**Comment by kof** [comment]
closing, seems outdated
