### ISSUE TITLE
Improve the help widget

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3681]
<img width="226" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/2b5485c2-20f5-4745-ad4c-a3249a57f3ec">

- [ ] Put bug report inside
- [ ] Add contact us button, show some kind of that explains the user that we don't answer questions around "how to build xyz", only questions around problems with their account or a bug/problem with the builder itself. Basically things where we are at fault.  
- [ ] reuse the contents with the Resources panel, so we can have the same things there as well.

**Comment by Venu005** [comment]
Hey!! I am excited to work on this feature -
Enhance the user experience by displaying a "Contact Us" button and a note when the bug icon is hovered over. This note should specify that the button is intended for reporting account-related issues or bugs within the builder.

Hover Effect:
When the user hovers over the bug icon, a "Contact Us" button should appear.
A note should also become visible, clarifying that this option is for account-related issues or builder bugs only.

Design Requirements:
The "Contact Us" button should be prominently displayed and easy to click.
The accompanying note should be visible but not intrusive, ensuring it doesn't block other content.
