### ISSUE TITLE
Variable bindings on Class don't show on live site

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3683]
1. Create string var like "Hi" (or a resource or any other var)
2. Bind the var to the Class Name field on any component such as heading
3. View in the builder dom it outputs
4. Publish and view in the live site it does NOT output

Notes:
- Works fine with IDs and custom attributes
- Works fine if I enter a static value
- Seems to only be an issue with classes + variables

https://github.com/webstudio-is/webstudio/assets/93934362/083609f4-fa89-4712-bc48-ac92c0318f4b

**Comment by kof** [comment]
Short-term workaround: use data- attributes.
