### ISSUE TITLE
How to fix this, and how to deploy locally? Error "webstudio build"

### ISSUE THREAD

**Issue by alpiyev99** [webstudio-is/webstudio#3690]
How can I deploy project?

![Снимок экрана 2024-07-06 в 19 05 27](https://github.com/webstudio-is/webstudio/assets/124505479/3e26e402-35b5-4a8e-9dea-8d20cbedf220)
![Снимок экрана 2024-07-06 в 19 10 31](https://github.com/webstudio-is/webstudio/assets/124505479/af003e1a-8bcd-4ad1-8d0b-c62c6f70de53)

**Comment by kof** [comment]
Please provide a full detailed explanation from 0 to 100% of what needs to be done to get the error you are experiencing.

**Comment by alpiyev99** [comment]
1. I started webstudio in visual studio code
2. write pnmp dev
3. create website
4. want to export website
