### ISSUE TITLE
XML Node with title tag nested in any other XML Node breaks document

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3715]
An XML with title tag works fine until you nest it in another XML node of any title, then it breaks the doc. See attached.

Repro:
1. Add page of type xml and some URL like rss.xml
2. Add XML Node and give it any tag like `something`
3. Nest an XML Node within it and call it `title`

<img width="496" alt="webstudio" src="https://github.com/user-attachments/assets/312464c7-7d91-415b-a24e-d4dac7ba0444">
<img width="1386" alt="livesite" src="https://github.com/user-attachments/assets/4c45b240-4594-4bab-93dc-20fa18496e92">

Use case: Creating RSS feed.

**Comment by istarkov** [comment]
Wow really, feels like some React issue

**Comment by johnsicili** [comment]
Bumping to prio 1 as more people are requesting an RSS feed https://discord.com/channels/955905230107738152/1260933621800243201

Confirmed it's still an issue
