### ISSUE TITLE
DOMContentLoaded not firing when directly going to the URL

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3724]
DOMContentLoaded works if you click a link in the app that brings you to a page with that listener. However, it does not work if you go to the URL directly.

1. Add an HTML embed with client only enabled
2. Add a DOMContentLoaded listener with a console log
3. Publish
4. Go to the page directly in the browser
5. Optionally add links to and from the test page and navigate them to see DOMContentLoaded working

https://github.com/user-attachments/assets/cf23427c-7a3d-49fa-a2cf-0dc5941c68bf

```
<script type="module">
  document.addEventListener("DOMContentLoaded", (event) => {
    console.log("DOM fully loaded");
  });
</script>
```

**Comment by istarkov** [comment]
it works without issues without `type="module"`
```html
<script>
document.addEventListener("DOMContentLoaded", (event) => {
    console.log("DOM fully loaded");
  });
</script>
```

**Comment by kof** [comment]
@istarkov wow ,that's unexpected, any idea howe that happened? Sounds like a bug to me

**Comment by istarkov** [comment]
Investigating, had similar issue with inlined type="module" on zaraz few days ago

**Comment by kof** [comment]
Turns out its not a bug, type=module just like attribute async turns the script into async and won't be able to guarantee DOMContentLoaded event, because it can be delayed.

So either don't use type module or place the script at the end of the page

**Comment by istarkov** [comment]
Fixed see corresponding PR for details

**Comment by kof** [comment]
So it turned out our problem, not a standard behavior
