### ISSUE TITLE
Don't use label as a trigger for switch in settings

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3751]
it is too easy to misclick the setting unintentionally.

**Comment by TrySound** [comment]
What switch are you talking exactly?

**Comment by kof** [comment]
<img width="251" alt="image" src="https://github.com/user-attachments/assets/e504d5bc-2e03-4fea-9547-588152a96a2b">

We currently toggle using the label too, which can lead to accidental clicks
