### ISSUE TITLE
Increased width of navigator

### ISSUE THREAD

**Issue by 360Creators** [webstudio-is/webstudio#3760]
I know I can horizontally scroll. Still it'd be nice to be able to have a larger navigator so I don't need to scroll at all.
Currently I can not extend it, or I don't know how to.
![image](https://github.com/user-attachments/assets/889bb5b7-5e7b-498b-9287-238568354fbc)

**Comment by kof** [comment]
duplicate of https://github.com/webstudio-is/webstudio/issues/236
