### ISSUE TITLE
SSG (Static site generation) export

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio#3763]
As a user I want to export my site as html/css/js and host on any static hosting without complex server runtime setup.

Not intended to be supported
- dynamic pages
- redirects
- statuses
- client navigation
- webhook form
- image optimization
- no robots.txt
- not sitemap.xml

**Comment by BenAlanSouthall** [comment]
Hi, just a comment on the output of this.

For my usecase, the generated HTML and assets are still more complicated than I'd need them to be. I also find my website is unpredictable with the scripts at the bottom (`entry-server-routing......js`, `entries/pages_.....js` and `chunks/chunk-.....js`) that seem to be doing some sort of hot-reloading or something - when I delete something in the web inspector, it gets added back again. The scripts I have in my page are also firing twice and blowing up, so I have to comment that out. There also seems to be a lot in the javascript files under entries, chunks, etc., and the routing files are still included, but not sure if these are needed. 

Understand WS is a work in progress right now! But over time it'd be nice to have a static export that's closer to e.g. one HTML and CSS file per page (with common styles in their own file, etc.). I'm using WebStudio less for generating a whole site or an app, more as a good UI for designing individual pages, that will need to slot into a larger site, or may just be standalone HTML for a project. So the ability to generate really straightforward output would help a lot in integrating and deploying those. I'm also version-controlling the output, so just outputting to straightforward filenames without the unique hash on the end also would help. I guess this could potentially cause caching issues, but for me that's I would rather be managing in my deployment process and the server config.

**Comment by kof** [comment]
@BenAlanSouthall I don't think generated output right now is for your use case. This is currently meant to be used as is and served with Remix. This is how we use it and that's the tested path.

For standalone reusable html/css generation we willl have in the future components and a different way of generating things that is meant to be reusable and even importable directly.

**Comment by BenAlanSouthall** [comment]
Cool! That sounds great.

I learned about components recently and was wondering if they might feature eventually, so looking forward to seeing how they turn out
