### ISSUE TITLE
Primevue UI Components support

### ISSUE THREAD

**Issue by adolfusadams** [webstudio-is/webstudio#3781]
Are there any plans to include [Primevue](https://primevue.org/) UI components? If not, it should be, then please consider it as a feature request.

**Comment by kof** [comment]
1. its a different framework, so it's blocked on vue support
2. we have not opened up yet ability to add your own custom components

Short version - this specific library not anytime soon. React-based libraries - rather sooner, one will be able to configure bindings for existing libraries for react and use them in their projects + publish them in the marketplace.

**Comment by adolfusadams** [comment]
I would like to be able to use Primevue as I am in the Vuejs ecosystem, even if as a custom component in Webstudio. Roughly when would the ability to add custom components be available?

**Comment by kof** [comment]
I can tell that this year its not gonna happen if this helps.
