### ISSUE TITLE
Generate human readable class for component preset

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio#3787]
We currently rely on data-ws-component attribute to apply preset styles.
We need to replace it with class name, something like `ws-p-link` or `ws-p-link-1` if conflicts with other component library. Should work for both atomic and regular styles.
<img width="414" alt="image" src="https://github.com/user-attachments/assets/69269079-0cdf-4405-a10e-5a72a6d386f1">

**Comment by kof** [comment]
Should atomic be an option within export dialog? because compiler settings right now are in project settings

<img width="304" alt="image" src="https://github.com/user-attachments/assets/9e625ed0-b153-4334-aa02-522ed93db201">

**Comment by kof** [comment]
What should we generate as a selector for local styles, since unique and accurate labels aren't really guaranteed?

**Comment by TrySound** [comment]
Another issue https://github.com/webstudio-is/webstudio/issues/3788
