### ISSUE TITLE
All elements are outlined on prod

### ISSUE THREAD

**Issue by JaumeRF** [webstudio-is/webstudio#3801]
I don't know when it happened, but today I've noticed that my website and the webstudio website only on Arc Browser. I've already tried to clear cache and cookies but it didn't work. 

This is how I see the websites
<img width="1467" alt="Captura de pantalla 2024-07-27 a las 10 44 22" src="https://github.com/user-attachments/assets/d5a4c44c-2acc-4061-ad2c-27423ad64769">

I think the problem is that the css is full of:
        box-sizing: border-box;
        border-top-width: 1px;
        border-right-width: 1px;
        border-bottom-width: 1px;
        border-left-width: 1px;
        outline-width: 1px

**Comment by kof** [comment]
Arc is chromium ... It's more likely that your browser settings do this

**Comment by TrySound** [comment]
Do you have any users styles enabled?

**Comment by JaumeRF** [comment]
Only webs made with webstudio appears to have the outlined problem

I'm searching for the settings that you are talking, but I don't have any page with users styles enabled.


When looking into the css I see this:
<img width="1494" alt="Captura de pantalla 2024-07-27 a las 11 28 07" src="https://github.com/user-attachments/assets/5e364537-00f5-49fe-98fd-6d6e586bac49">

<img width="1483" alt="Captura de pantalla 2024-07-27 a las 11 30 28" src="https://github.com/user-attachments/assets/a59bbea4-a029-4ca8-a7fe-1df0026c9529">

**Comment by TrySound** [comment]
@JaumeRF did you resolve the issue?

**Comment by kof** [comment]
tested in arc, no problems
