### ISSUE TITLE
CSS Root Variables

### ISSUE THREAD

**Issue by imraanalam** [webstudio-is/webstudio#3804]
Please enable the ability to add and manage CSS root variables for spacing, typography, colors, and more. This feature is the main barrier preventing my switch to Webstudio. As a WordPress user, I can effortlessly define variables in core wp or using themes like Bricks.

Below is the screenshot of bricks builder variables and class management modal window.
![Screenshot_1](https://github.com/user-attachments/assets/56570fab-5059-4df0-85cc-11298d1e42aa)

**Comment by TrySound** [comment]
On the roadmap
https://github.com/webstudio-is/webstudio/issues/3399

**Comment by kof** [comment]
global variables manager https://github.com/webstudio-is/webstudio/issues/3686

**Comment by imraanalam** [comment]
Thank you, will wait for that feature to release.
