### ISSUE TITLE
Allow scrolling of the background panel

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3815]
On a screen with relatively little height, this is what the panel could look like

<img width="524" alt="image" src="https://github.com/user-attachments/assets/9163d420-92e2-40e0-b289-19da591360dd">

## Todo
- [ ] use ScrollArea inside floating panel like we do in variable-popover.tsx

<img width="487" alt="image" src="https://github.com/user-attachments/assets/ca6e08db-45a0-480e-81a0-6a49bcc6340e">

**Comment by johnsicili** [comment]
Does not appear to be an issue anymore.

<img width="1394" alt="Screenshot 2024-09-18 at 6 06 58 AM" src="https://github.com/user-attachments/assets/d037a979-a3c8-4eeb-a7dc-28d5b3816257">
