### ISSUE TITLE
Latest Build issues

### ISSUE THREAD

**Issue by bdot-real** [webstudio-is/webstudio#3896]
pnpm migrations migrate failing on the 
  
20240807000548_deleted-project-free-domain

Error: Command failed with exit code 1: prisma db execute --file /home/ubuntu/webstudio/packages/prisma-client/prisma/migrations/20240807000548_deleted-project-free-domain/migration.sql --schema /home/ubuntu/webstudio/packages/prisma-client/prisma/schema.prisma
Error: ERROR: schema "extensions" does not exist

I can run pnpm dev but i get an issue when i try to create a new project

trpc-client.ts:123 TRPC ERROR TRPCClientError
    at _TRPCClientError.from (@trpc_client.js?v=013d1fd6:129:14)
    at @trpc_client.js?v=013d1fd6:469:46

**Comment by TrySound** [comment]
Did you use docker compose to setup database? Any other way may not work
https://github.com/webstudio-is/webstudio/blob/main/.devcontainer/docker-compose.yml

**Comment by bdot-real** [comment]
Hmm. was using an external postgres and postgrest for about 2 weeks but
switching to the supplied docker fixed it. that fixed it. thanks
