### ISSUE TITLE
Default Checked not working on Radix Checkbox

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3903]
As a user, I need a way to preserve the state of my checkbox filters. The user filters content and submits, and all selected filters go away, making it hard to understand what is currently filtered.

https://github.com/user-attachments/assets/ffa90c7a-669f-4965-9b14-6957fbe9b661

In other components, I'm able to use the `system.search.fieldName` and bind it to some default value, but it's not working on the checkbox.

Demo: https://www.tella.tv/video/preserving-button-states-ev33
Original discussion: https://discord.com/channels/955905230107738152/1270871878973653022
Radix: https://www.radix-ui.com/primitives/docs/components/checkbox

Blocker for the new cms finder page.

**Comment by kof** [comment]
fixed
