### ISSUE TITLE
Getting error cloning repo on windows

### ISSUE THREAD

**Issue by cadamsdev** [webstudio-is/webstudio#3923]
Looks like the file name
 fixtures/webstudio-remix-vercel/public/assets/DALL_E_2023-10-30_12.39.46_-_Photo_logo_with_a_bold_cat_silhouette_centered_on_a_contrasting_background_designed_for_clarity_at_small_32x32_favicon_resolution_00h6cEA8u2pJRvVJv7hRe.png

is too long

![image](https://github.com/user-attachments/assets/ff5fbe93-5094-4d12-bcae-5dd3b6f2b167)

Steps to reproduce
 On Windows run command
```
git clone https://github.com/webstudio-is/webstudio.git
```

**Comment by istarkov** [comment]
https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
Please fix your git config or change git client ;-)
