### ISSUE TITLE
Hidden background image is rendered on canvas

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio#3935]
Seems like hiding background layers broke at some point

<img width="1404" alt="image" src="https://github.com/user-attachments/assets/e14ea32f-0559-49e0-8687-175339992e4d">

**Comment by JayaKrishnaNamburu** [comment]
Are there any specific steps or case where it is failing @TrySound. I tried to reproducing it, but seems to work fine in the deployed version and local.

![bg-image](https://github.com/user-attachments/assets/c292a892-2294-4334-b9d9-b8b4dd9f38e7)

**Comment by kof** [comment]
@TrySound why is it closed?

**Comment by JayaKrishnaNamburu** [comment]
@kof because, it was coming from the `backgrond-color` and not background-image.
<img width="716" alt="Screenshot 2024-08-15 at 7 44 25 PM" src="https://github.com/user-attachments/assets/9653582e-ae9b-45b3-b601-71862973e032">
