### ISSUE TITLE
Changing transition property requires clicking it in dropdown, even if it shows a check

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3958]
When changing the transition property, for example, from the default opacity to height, height isn't selected until you click on it – even though height has a check before it, and I hit enter.

1. Add transition
2. Click into it and edit the property
3. Type `height`
4. See it checked, also try hitting enter
5. Click out of the transition and see opacity still there

https://github.com/user-attachments/assets/c155543e-7ed8-461d-a565-4a746d8321e8

**Comment by johnsicili** [comment]
Additionally, if you type `width`, it's not scrolled into position, even though it's checked.

**Comment by JayaKrishnaNamburu** [comment]
@johnsicili fixed it in #3968. Can you please check once and confirm if the new behaviour is as expected.
