### ISSUE TITLE
Make it easy to find the right property in transition properties list

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [webstudio-is/webstudio#3982]
We are adding transforms section under #3411 

Among the transform properties `translate`, `scale` are applied on elements using the individual properties [translate](https://developer.mozilla.org/en-US/docs/Web/CSS/translate) and [scale](https://developer.mozilla.org/en-US/docs/Web/CSS/scale). But `skew` and `rotate` and managed using the [transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) property as functions. So, when users want to apply css transitions using the `transform` as `transition-property` like this

<img width="242" alt="Screenshot 2024-08-21 at 9 14 14 PM" src="https://github.com/user-attachments/assets/f3bc6c34-9f4d-46bb-8e90-f29d6489d35a">

It applies only for `rotate` and `skew`. Because `translate` and `scale` are not added under the `transform` property. This behaviour is because we are managing `translate` and `scale` using the individual property behind the scenes when applied under the Transform section.

Here is a detailed explanation of the same from @johnsicili 
https://www.tella.tv/video/troubleshooting-transform-ui-4anv

## Proposal

After some discussion with @kof. The most sensible way to avoid such things seemed to show the list of properties that are already applied on the element that are effected by transition property.

 Which makes this list to be from this.

![image](https://github.com/user-attachments/assets/79e79f8f-b49d-4360-9404-817b6704a78a)
 
 to this
 
![image](https://github.com/user-attachments/assets/cc05fefe-9f7d-4d79-b554-35d0ed42b9fa)

cc @kof @TrySound

**Comment by kof** [comment]
exactly !

**Comment by kof** [comment]
- [ ] If defined list is empty, we should not show the categoty

**Comment by johnsicili** [comment]
This is a good idea. Though it's still a little confusing that if I apply transform scale, I use scale transition, but if I apply transform rotate, I use transform transition.

## Ideas 

We either handle the transform transition behind the scenes (e.g., convert transform transition to scale) or give them each property in transition, like rotate and convert it behind the scenes. Idk though.

Or next to Transform transition we add (Rotate and Skew) in parenthesis.

**Comment by kof** [comment]
Lets imagine user sets translate and rotate. While rotate is via transform and translate is separate property.

Now what if user only wants to transition translate or only rotate? In this case if we do magic there, they won't have any control.

The property selection actually allows you to control the transition timing of each property so we somehow need to be able to control them individually.

My hope is by showing them in the list, we make it obvious enough that user can select those and they will see scale or translate in the list.

**Comment by johnsicili** [comment]
Good point. How about my second idea then, which is adding (Rotate and Skew) in parenthesis next to Transform?

**Comment by kof** [comment]
Hmm, @JayaKrishnaNamburu if it is not too complicated, it would be benefitial indeed to show "Transform (Rotate, Skew)" in the list

**Comment by kof** [comment]
One thing that we are getting from using scale/translate individual properties is that now its possible to transition them at different speeds, while before that you would only transition them all together with the same speed and easing.

**Comment by JayaKrishnaNamburu** [comment]
> One thing that we are getting from using scale/translate individual properties is that now its possible to transition them at different speeds, while before that you would only transition them all together with the same duration and easing.

Actually it's pretty good to have too. Gives users so much more control over the effects.
