### ISSUE TITLE
Export error locally

### ISSUE THREAD

**Issue by ethaka** [webstudio-is/webstudio#4032]
I'm running the builder locally with VS Code, when I'm trying to export the website as static site, the following error keeps showing:
Not implemented, use buildId=10ac7283-7dc7-4089-8c25-1bb181d2d092

![export-error](https://github.com/user-attachments/assets/4845a5e5-23a0-4b4f-8431-ca5916f1882e)

Is it due to missing configuration or does the export functionality not work locally?

**Comment by TrySound** [comment]
Publishing and exporting is our cloud feature. Only cli is supported locally.

**Comment by kof** [comment]
Its not that its hidden, but you need to connect the publish url and your publisher, which uses the cli to build the export ... so local development environment for exporting - you need to either connect these things yourself or use the cli directly
