### ISSUE TITLE
Add folders support to pages

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio#404]
- Folders should be used just for organising, they don't affect path etc.
- Adding a folder and editing its settings should work similar to pages (although the only setting is the folder name, so maybe worth simplifying somehow)

<img width="216" alt="Screenshot 2022-11-07 at 12 39 18" src="https://user-images.githubusercontent.com/825702/200264063-9a9fb734-a883-44d1-84f7-8b8d081c1449.png">

<img width="334" alt="Screenshot 2022-11-07 at 12 39 49" src="https://user-images.githubusercontent.com/825702/200264180-fa98af5c-70f8-4891-9787-07341a213900.png">

## Remaining Todos
- [x] ensure unique slug within nested folder after reparenting folders
- [x] ensure unique slug within nested folder
- [x] parent folder select for the page, root is default
- [x] compute page path with folder slug
- [x] ensure changing a slug reflects on all children, including nested once
- [x] ensure generator uses slug too on the build
- [x] render href on canvas with nested path
- [x] switch pages on canvas with nested path
- [x] collapsible folders
- [x] highlight the nested folder in pages list
- [x] confirm deletion when not empty and delete all pages inside
- [x] display nesting in link page select as well as page select in page settings
- [ ] ~allow setting a page as an index~ - decided to go with wf model for now - if you want an index page you just create a page with the same name as folder

**Comment by kof** [comment]
done
