### ISSUE TITLE
Unexpected end of JSON input in Webhook Form

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4050]
When sending a webhook form to https://tapeapp.com webhook, we get "Unexpected end of JSON input" error.

I assume we either expect a json but get something else or there are wrong headers being sent from the app. Repro in dm

https://test-2h51i.wstd.io/

submit the form, see network response

Either way we should tolerate wrong headers and wrong responses in the webhook. We basically only care if its some http error code or 200 and we don't really need to parse the response

**Comment by lomaymi** [comment]
I reported this issue on Discord. Tapeapp is receiving the webhook data correctly. 

![Screen Shot 2024-09-02 at 09 50 31](https://github.com/user-attachments/assets/4570092f-8a4f-42c7-a5ec-9826bdbebdc7)

Let me know if I can help with this issue.
