### ISSUE TITLE
SEO Launch

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio#408]
- [x] Ability to edit title and description
- [x] Title and description should appear in the corresponding meta tags
- [ ] "Noindex" checkbox (need to research how to implement it in terms of [meta tags](https://developers.google.com/search/docs/crawling-indexing/block-indexing) / robots.txt?)
- [ ] Search results preview  
- [x] Favicon https://github.com/webstudio-is/webstudio/issues/1915

<img width="420" alt="Screenshot 2022-11-07 at 13 37 30" src="https://user-images.githubusercontent.com/825702/200277197-9c8241cd-b381-43eb-9578-b1f557ac503d.png">

**Comment by kof** [comment]
Can we split this? Add title and description now, I think this is relatively fast, and move the Search result preview to "after beta"?

**Comment by rpominov** [comment]
Yeah, good idea. Will do

**Comment by itsNintu** [comment]
SEO Launch script WIP: https://www.notion.so/webstudiois/SEO-Launch-Script-bec2b132b59b4af48fb65dd2d179858d?pvs=4
