### ISSUE TITLE
Canvas instance selection bugs

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4095]
The canvas has seemed to become buggy. I'm noticing several issues.

1. ~When quickly selecting different instances, the instance is not selected. It only selects them when you don't click quickly.~ https://github.com/webstudio-is/webstudio/pull/4370
2. ~~The navigator closes when slightly dragging an instance (see here https://github.com/webstudio-is/webstudio/issues/4095#issuecomment-2338814814)~~ New issue opened https://github.com/webstudio-is/webstudio/issues/4158
3. ~When you click into an instance to edit it, such as a paragraph, the hover outline no longer shows when you hover over other instances. Only in the navigator does the hover show.~ https://github.com/webstudio-is/webstudio/pull/4368
4. Dragging spacing is not working unless you click and hold for a second then drag. While this is not a canvas bug, it may be solved with code from item 1.
5. ~~The navigator sometimes shows the state as if an instance is being dragged but no instance is being dragged.~~ Fixed (issue was clicking on the icon in instance)

Item 4 issue:
https://github.com/user-attachments/assets/a6334cb7-1c0c-4332-a127-cd752aa32135

Instance selection issues:
https://github.com/user-attachments/assets/edbb1e74-bb2f-4981-b942-8a02220e3bd1
https://github.com/user-attachments/assets/4d0bf08c-6309-45c2-aea5-ce1d6a2f9977

_Sorry about movie format, was trying a new setup_

**Comment by johnsicili** [comment]
The navigator closing happens twice in this video. Hoping other eyes or the code will shed light on the "why"
https://github.com/user-attachments/assets/9fb82131-7775-413e-b1e8-5b6e2d010603

**Comment by johnsicili** [comment]
Repro! Slightly drag the instance, navigator opens/closes

https://github.com/user-attachments/assets/57c6bef0-f057-4d58-81e9-377e0d858ce0

**Comment by johnsicili** [comment]
6. No outline shows when selecting instances. (No repro yet)

https://github.com/user-attachments/assets/10043991-a70b-446b-9993-2fb31e3fa529

**Comment by istarkov** [comment]
Can't reproduce other bugs, are they still relevant? cc @johnsicili

**Comment by johnsicili** [comment]
Looks like just 4 was left and it does not seem to be an issue anymore. Thanks so much for fixing these. They really improve editing experience on canvas.

Also sorry about format of this issue... It started with just one or two then grew and became jumbled
