### ISSUE TITLE
Template vanilla is not available

### ISSUE THREAD

**Issue by AlexBeemer** [webstudio-is/webstudio#4105]
When I try to use the CLI to export a Vanilla js app I get this error: 

■  Template vanilla is not available
│  Please check webstudio --help for more details

It seems to work fine for a Static Site however.

**Comment by JayaKrishnaNamburu** [comment]
Fixed it here #4107 👍

**Comment by AlexBeemer** [comment]
Amazing! Thank you for the quick turn around!
