### ISSUE TITLE
Windows can't scroll body on canvas without background color

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4128]
Apparently on windows body can not be scrolled if there is no background color

https://discord.com/channels/955905230107738152/1284521003061350564

**Comment by johnsicili** [comment]
I accessed a Windows machine and could not repo with Chrome 129 or Edge

https://github.com/user-attachments/assets/8ce5a6ce-82a7-42c3-bc2f-add7d0560efe

My steps:
1. Add new page
2. Set height to 5000px
3. Scroll canvas using wheel and trackpad (worked)
