### ISSUE TITLE
Invalid header value.

### ISSUE THREAD

**Issue by marcellov7** [webstudio-is/webstudio#4133]
Hi
we are experiencing a problem after publication
“Invalid header value.”
how can it be fixed? we don't see debug information.
https://teyuto-qzmzu.wstd.io 500 (Internal Server Error)

thanks

**Comment by kof** [comment]
We will look into it shortly. At first sight it seems like something bad is being returned form an api that you are trying to use. Feel free to DM me in discord with shared project link so we can look into your data.
