### ISSUE TITLE
Webhook forms not submitting in Brave with Block fingerprinting on

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4139]
Brave Block fingerprinting is causing the submission to not work due to spam protection.

1. submit form
2. See network error `{"success":false,"errors":["Form bot value invalid jsdom"]}`

https://github.com/user-attachments/assets/a66c6622-01a2-4979-a035-38e689b1a288

**Comment by kof** [comment]
![image](https://github.com/user-attachments/assets/0958667a-bed1-48a0-9391-e54cd843e521)

**Comment by kof** [comment]
Brave thinks we are fingerprinting. Where we are generating a token, to fight bots ...

**Comment by kof** [comment]
closing this for now, not sure we can do anything about it cc @istarkov pls reopen if you disagree
