### ISSUE TITLE
Radix Component Typography Menu: Missing font family dropdown & weird layout

### ISSUE THREAD

**Issue by jakobsturm** [webstudio-is/webstudio#4146]
I have added the accordion radix component to a page, when I want to edit the font family of the "Item Trigger" the typography menu is weird. There is no font family dropdown and the overall layout seems broken.

This is how it looks:
![CleanShot 2024-09-23 at 10 59 00](https://github.com/user-attachments/assets/3954775d-05a0-4bfc-9c7c-a4b83695dc4a)

This only happens for Radix components, it works fine for other elements.

**Comment by kof** [comment]
Got it reproduced, thank you

**Comment by johnsicili** [comment]
Also on Navigation Menu > Button

<img width="1341" alt="Screenshot 2024-09-23 at 6 34 17 PM" src="https://github.com/user-attachments/assets/6b370d2a-dbfd-4267-a78e-3b3dbc3ad802">

**Comment by johnsicili** [comment]
More info on this... it looks like it lazy loads for a lack of better words on all instances.

https://github.com/user-attachments/assets/704ed403-f6d9-4fe8-87fa-84941ada992d

**Comment by kof** [comment]
releasing fix now
