### ISSUE TITLE
DNS copy buttons don't trigger/show tooltips like "Copied"

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4152]
There used to be confirmations when you click the copy buttons next to DNS records but they are gone.

Copy works, there's just no visual indication.

1. Click copy button
2. See no tooltip (expect some visual indication that it's copied)

https://github.com/user-attachments/assets/8d19f1fd-be95-4e86-828c-100c0699008d

**Comment by johnsicili** [comment]
Maybe due to this https://github.com/webstudio-is/webstudio/pull/4088

**Comment by kof** [comment]
When we are working on fixing it,please also make a generic copy to clipboard button that encapsulates all that functionality inlcuding tooltip and allows consumer to provide either icon or text as child.
