### ISSUE TITLE
Switching between builder and preview results in rate limiter block

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4164]
After a 5-10 switches we can see rate limiter jumping on. Its reproducible on multiple projects

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/ebe19009-5c06-4a2f-86e3-b7977cdde547">

**Comment by istarkov** [comment]
Increased rate-limits for auth users to 40/s 
before auth users was't detected well and IP was used.

**Comment by kof** [comment]
this was fixed, can be closed?
