### ISSUE TITLE
Navigation collapses itself when toggling and un-toggling preview

### ISSUE THREAD

**Issue by pausak** [webstudio-is/webstudio#4176]
**Issue:**

Left hand nav collapses expanded elements when you toggle and then un-toggle the preview.

See video below.

https://github.com/user-attachments/assets/5894d3a3-b609-4f8a-908f-a63e3043a25d

**Steps:**

1. Add a the radix navigation component to the canvas
2. Expand all block elements within the navigator
3. Toggle the preview
4. Un-toggle the preview

**Expected**

The navigation remains expanded

**Actual**

The navigation is collapsed when un-toggling the preview

**Comment by TrySound** [comment]
Just fixed it with new tree implementation. We will release soon.
