### ISSUE TITLE
Background image not displaying

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4232]
When adding a background image, the image isn't displaying after reloading the builder.

Also, default size is custom. It's that way on prod too but wasn't sure if that is intentional.

https://github.com/user-attachments/assets/b2d2e1d9-6bd9-466f-ae49-2962142188ab

**Comment by TrySound** [comment]
I think it's more this issue
https://github.com/webstudio-is/webstudio/issues/4244

**Comment by johnsicili** [comment]
Ah you're right my bad
