### ISSUE TITLE
codespace 

### ISSUE THREAD

**Issue by vishnu5104** [webstudio-is/webstudio#4263]
Hi,

When I run the project locally and try to log in with my GitHub credentials using the first four letters of my username as "scee" (e.g., if the username is "sceeent"), I get a "user not found" error. My .env.development file contains the following:
DEV_LOGIN=true
AUTH_SECRET="arandomvalue"

I followed this doc for locally run in vs code : https://docs.webstudio.is/contributing/contributing-for-developers

**Comment by istarkov** [comment]
codespaces.
<img width="699" alt="image" src="https://github.com/user-attachments/assets/4ba9b14f-8b3f-4f96-bb3c-ee6197f4dcdf">

**Comment by istarkov** [comment]
No issues with login on newly created env I see
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/1ffea29e-b542-447a-a334-5a914d043b93">

**Comment by vishnu510412** [comment]
> No issues with login on newly created env I see <img alt="image" width="1055" src="https://private-user-images.githubusercontent.com/5077042/375486162-1ffea29e-b542-447a-a334-5a914d043b93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1ODQxNTksIm5iZiI6MTcyODU4Mzg1OSwicGF0aCI6Ii81MDc3MDQyLzM3NTQ4NjE2Mi0xZmZlYTI5ZS1iNTQyLTQ0N2EtYTMzNC01YTkxNGQwNDNiOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMTgxMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjIxODBlZWEyZTY3YzlkNWQ4MDgwYWY5OWJiMTAxMjljNTMzNGY2N2RhYWQ4YWNiMTdjNWZmOTUwNzhhMzkzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SNu3LkUIVg1HJOHzbtz_U0RdnlArhsGsNoPdme24Ku8">

How did u logon like using GitHub secret ? What value u passed in login? For me it shows user not found (I tried in locally vs code env)

**Comment by istarkov** [comment]
Since this seems to be your issue, could you please explain step-by-step what you’re doing?

For example, you mentioned:

> When I run the project locally and try to log in with my GitHub credentials using the first four letters of my username.

However, I don’t see any mention of using the first four letters in the GitHub login documentation:

<img width="718" alt="image" src="https://github.com/user-attachments/assets/dd7dde08-e91f-4f6e-87cf-acc3eb54b84c">

**Comment by vishnu510412** [comment]
> Since this seems to be your issue, could you please explain step-by-step what you’re doing?
> 
> For example, you mentioned:
> 
> > When I run the project locally and try to log in with my GitHub credentials using the first four letters of my username.
> 
> However, I don’t see any mention of using the first four letters in the GitHub login documentation:
> 
> <img alt="image" width="718" src="https://private-user-images.githubusercontent.com/5077042/375498838-dd7dde08-e91f-4f6e-87cf-acc3eb54b84c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1ODUyOTYsIm5iZiI6MTcyODU4NDk5NiwicGF0aCI6Ii81MDc3MDQyLzM3NTQ5ODgzOC1kZDdkZGUwOC1lOTFmLTRmNmUtODdjZi1hY2MzZWI1NGI4NGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMTgyOTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDAwNGI0NDI5MDBkZDQ4ODUwYjQyYTRhMzM1OTk2MmVkNDBlYzgzZTM3Y2Q0NTNhYzUyOTM0NmI5NGIyZWI4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TNsG-Sdf-jl5OJ5aXcTrY1W1wsqOVB8_CGp_QZ4Mk3E">

The 4 letter I mean on dev github login

**Comment by istarkov** [comment]
Doc

<img width="725" alt="image" src="https://github.com/user-attachments/assets/c1ab73b1-faf6-4efb-ab97-58acfa1f7e74">


This.

> To login in the app click on the "Dev Login" button and paste the first four characters of your AUTH_SECRET in the input

No words about username :-)

if `AUTH_SECRET="arandomvalue"` then pass is `aran`

Moreover I think your error was

<img width="278" alt="image" src="https://github.com/user-attachments/assets/4f9432bb-648a-4904-90ba-912fecf1ffc1">

And not the `User not found`


I will not answer again without step-by-step what you’re doing with screenshots etc. As it looks like miscommunication without.

**Comment by vishnu5104** [comment]
> ink your erro

yes this one this error I got

**Comment by vishnu5104** [comment]
btw how did u login ?

**Comment by vishnu5104** [comment]
@TrySound why did u closed this ?

**Comment by SantoshSrinivas79** [comment]
> No issues with login on newly created env I see <img alt="image" width="1055" src="https://private-user-images.githubusercontent.com/5077042/375486162-1ffea29e-b542-447a-a334-5a914d043b93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4OTUxMTQsIm5iZiI6MTczMjg5NDgxNCwicGF0aCI6Ii81MDc3MDQyLzM3NTQ4NjE2Mi0xZmZlYTI5ZS1iNTQyLTQ0N2EtYTMzNC01YTkxNGQwNDNiOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjlUMTU0MDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTZiMTQ0MjhhOTRmOTNjMTIwODQ0Y2ZjZmZkMzVjOD
U2YmY4ZWMwYjBlZDRlN2ZiMDA3NmQ5MjA4MWY2NGI4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3Rs0nV-v4xmCo0SAJcSX-lxVQNzh6A5eQRbDzn6X30k">

After this I am able to create a project. But, when I click on the project, I am taken to a error page. 

![CleanShot 2024-11-29 at 21 14 06@2x](https://github.com/user-attachments/assets/370df910-2ffe-4c0b-99a4-b797647bd6ee)

**Comment by kevin-folo** [comment]
Same issue solved, the database migration failed during the initialization process, so you need to migrate again using "pnpm migrations migrate".
