### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by vishnu5104** [webstudio-is/webstudio#4265]
Doc

<img width="725" alt="image" src="https://github.com/user-attachments/assets/c1ab73b1-faf6-4efb-ab97-58acfa1f7e74">

This.

> To login in the app click on the "Dev Login" button and paste the first four characters of your AUTH_SECRET in the input

No words about username :-)

if `AUTH_SECRET="arandomvalue"` then pass is `aran`

Moreover I think your error was

<img width="278" alt="image" src="https://github.com/user-attachments/assets/4f9432bb-648a-4904-90ba-912fecf1ffc1">

And not the `User not found`

I will not answer again without step-by-step what you’re doing with screenshots etc. As it looks like miscommunication without.

_Originally posted by @istarkov in https://github.com/webstudio-is/webstudio/issues/4263#issuecomment-2405796636_

**Comment by vishnu5104** [comment]
@istarkov https://github.com/webstudio-is/webstudio/issues/4264

i detailed my issue also added screenshot and how did u run it ? like on codespace when I create a project it not even open the no code editor for me

**Comment by kevin-folo** [comment]
I solved this issue by moving the .env files in the root folder of the project.
