### ISSUE TITLE
Input arrow up and down pulls up autocomplete now instead of incrementing

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4287]
When clicking into an input like width and trying to arrow up or down to increment, the autocomplete shows instead of incrementing.

https://github.com/user-attachments/assets/cfb3c223-81f5-4aa3-be2b-bd06fb62b1f7

**Comment by istarkov** [comment]
To reproduce there also should be root variables like `--size-10`  etc so if 10 is entered there would be autocomplete
