### ISSUE TITLE
After using expression editor, canvas loses focus

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4293]
After I use the expression editor, I can't scroll on the canvas until I click on it again.

1. Ensure the page has some room to scroll (eg 200vh)
2. Open expression editor
3. Click out of the expression editor, including clicking canvas directly
4. Try scrolling canvas
5. See no scroll 🙈 

https://github.com/user-attachments/assets/3a1ef1b6-cb5c-479c-9765-f9dd1777aed9

Borderline P2 bug. If too much effort maybe it's P2.

**Comment by istarkov** [comment]
This occurs after every dialog we have, i.e. publish etc.
This is because of Dialog's backdrops. Click is not occured on canvas but on invisible backdrop.

I don't know how to fix this.
