### ISSUE TITLE
Mobile WebKit and Chromium browser support (iPadOS)

### ISSUE THREAD

**Issue by aeonoea** [webstudio-is/webstudio#4313]
Hi all, currently doing 99% of my work on my iPad Pro and WebKit-based browsers, such as Orion or Safari. Rarely I will use Firefox, Chrome or Brave when some app requires it. Now, when trying to sign up and build my first Webstudio project none of the browsers I have installed on my iPad are allowed to enter the holy grail of Webstudio :) Even though it will say Chromium browsers are supported. Are you also filtering by operating system by chance?

**Comment by kof** [comment]
Webstudio is not ready for touch devices like Ipad.

**Comment by aeonoea** [comment]
After spoofing the user agent with Orion I can report that everything works so far. Should also have specified that I don't use the iPad Pro in my hand as touch device, but as a regular laptop with keyboard and mouse.

Happy to test and report further. As Orion is WebKit-based like Safari the feedback will be placed in the Safari threads.

**Comment by kof** [comment]
cool, the trouble is that there is a lot more to test and you will definitely see bugs, but we are right now not investing into other platforms for running builder, beyond chromium based. What you can do to help later discover the bugs once we are working on expanding browsers support is to document them all in this issue  https://github.com/webstudio-is/webstudio/issues/1818

**Comment by johnsicili** [comment]
BTW Chrome on iPad still uses WebKit. Apple enforces it. Though I think that's changing in the EU.
