### ISSUE TITLE
XML tags are allowed to have a colon but currently validation strips it

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4343]
![image](https://github.com/user-attachments/assets/be2fbaef-8d66-450d-a908-0ac33df5973e)

**Comment by istarkov** [comment]
What the usecase? Sitemap has predefined schema without attributes and namespaces with colons

**Comment by mrtnblv** [comment]
Build a sitemap for multilingual website, like that :
`<url>
    <loc>https://website-ebrei.wstd.io/contact</loc>
    <xhtml:link rel="alternate" hreflang="fr" href="https://websitee-ebrei.wstd.io/contact"/>
    <xhtml:link rel="alternate" hreflang="en" href="https://website-ebrei.wstd.io/en/contact"/>
    <xhtml:link rel="alternate" hreflang="es" href="https://website-ebrei.wstd.io/es/contact"/>
    <xhtml:link rel="alternate" hreflang="x-default" href="https://website-ebrei.wstd.io/contact"/>
</url>`

**Comment by mrtnblv** [comment]
Because it seems that it’s not (yet?) possible to add something like this in the `<head>` of an individual page:
`<link rel="alternate" hreflang="fr" href="http://www.website.com/fr">`

**Comment by istarkov** [comment]
> Because it seems that it’s not (yet?) possible to add something like this in the <head> of an individual page:
<link rel="alternate" hreflang="fr" href="http://www.website.com/fr">

Yes, impossible.

Will look today, what we can do. Both cases are relevant xml namespaces and per page links.
