### ISSUE TITLE
Facing issue in getting the builder deployed to vercel

### ISSUE THREAD

**Issue by Vaib215** [webstudio-is/webstudio#4362]
Hi, a newbie learner here.

I was exploring this project and trying to deploy it on production to vercel. Although, I could make it run on development, but could not figure out how to run the build generated after `pnpm run build`. Even on vercel, the platform is first identified as Vite, and the deployment is failed due to unrecognized build output directory, when I mentioned it as `/apps/builder/build`, the project did manage to get built successfully and deployed but the output was this screen:

![image](https://github.com/user-attachments/assets/606c2c53-57fc-441e-965c-7445ee00f010)

I even tried changing the platform from 'Vite' to 'Remix JS', just to arrive at this error:
```
Error: Could not determine server runtime. Please install one of the following: @remix-run/deno, @remix-run/cloudflare, or @remix-run/node
```

It would be a great help if anyone of you could help me deploy it.

**Comment by istarkov** [comment]
Anyway this does not mean that this is impossible, we are small team and just have more priority tasks.  Check our publish actions https://github.com/webstudio-is/webstudio/blob/main/.github/actions/vercel/action.yaml

**Comment by Vaib215** [comment]
@istarkov isn't there a way to deploy it on an ec2 or docker image?
