### ISSUE TITLE
Select the page when opening the page settings

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4372]
When opening page settings, that page should also be selected.

Say if you are on page A, then open Pages and select the three dots on page B; page A is still selected even though page B settings are open.

Two reasons this is confusing:
1. The selected page is still blue even though you are working on a different page settings
2. When clicking out of it, you would think you're working on the page you were just modifying the settings for

https://github.com/user-attachments/assets/60be7cfb-da97-433f-bef7-8c94fc8a12a1

https://discord.com/channels/955905230107738152/1303264411477217323

**Comment by TrySound** [comment]
What to do when select folder?
<img width="687" alt="image" src="https://github.com/user-attachments/assets/8d840154-0dde-4c96-8fc4-1838e8aeacc2">

**Comment by johnsicili** [comment]
Hm I don't have ideas besides just keep the current logic
