### ISSUE TITLE
UX: Use a Tabbed View for Style Sources

### ISSUE THREAD

**Issue by stellarpower** [webstudio-is/webstudio#4379]
Hi,

As a new user, and someone not experienced with web development, I am finding the Style panel really confusing to follow. I get the concepts behind tokens. But when I am editing things in the style panel, if I don't use tokens, and edit a single element, things go blue when I change them. I understand this.

But if I try using tokens though, maybe it's just me, I then really struggle to follow what it is that I am editing. There are lots of different colours (grey, blue, orange, red, purple), and when I copy-paste an element the colours seem to be different on identical versions. According to Murphy's law, if I try to change a property on all elements with the token, just that element changes. If I want to change it on just that element, they all do.

## User Story

If I click the drop-down and select convert to token, I presume that all the things that were blue up to that point (I.e. I changed them from the defaults) are now part of the token. But I would expect those properties now to go purple to match the token, but nothing in the panel does. If I change something, am I now editing the token or am I editing the original element? The token is listed in the style sources, but based on some youtube videos, I think previous versions of WebStudio listed the local style as a source, but the current version does not. So I don't know how to switch between editing the token or the element alone. If I change a property that wasn't originally set (i.e. is grey) when I converted to token, is this affecting the token or the single element? How can I see what is in the token versus what is on the element? I assume that red means I have overridden something that otherwise would be set by a source. Things also appear in orange, and without the best memory for a tool I don't use often, it's then not clear what that means. 

![image](https://github.com/user-attachments/assets/50120fcd-494b-4c84-b8ee-75fd5038e03e)

If I go to an element for example, colour appears in white. To me, that means I have set it on just that element:
![image](https://github.com/user-attachments/assets/b89531b6-c3c7-409a-9cd2-7d72d2b731b3)
If I hover over it, it says "style has come from" Base, and the token, and the element itself:
![image](https://github.com/user-attachments/assets/252a05ab-2599-41b9-93c5-3db1367fa898)
This implies to me that it must be white in all three, even though it appears in blue, which is what I am used to meaning means I've set it manually on that element. If I click the reset button, it then goes back to black. Apart from not knowing if I'm resetting the property for the token or the single element, if it's in Base and the token as white, and I hit reset, and the value goes to black, which implies it wasn't set in either of those three. So then I'm not sure what source I'm resetting and what I'm resetting it to.

I assume there is an answer to all these questions - but I'm listing them more as rhetorical rather than looking for answers here. I.e. whilst there must be a logical set of things going on here and I could spend more time learning, as a new user (and someone who isn't a long-term web designer but someone who just needs to build a few pages every so often and get them working ASAP) I'm not finding this easy to follow myself.

## Potential Improvement
Maybe the way this works is intuitive and easy to follow for others, but either it's not for me, or I would need to spend a lot more time learning and practising to be able to follow it. And I have been using WebStudio for maybe 30+ hours now.  

Thinking about it for a few minutes however, personally I would approach this by using a tabbed section in the style area. I think it could make it a lot clearer to follow how tokens are being applied if instead of having multiple different values in the same view with different colours, each style source were given a separate full set of option in its own tab, only displaying the styles as they apply to that source. I am picturing something a bit like this very crude mockup:

![image](https://github.com/user-attachments/assets/59954e13-f5e3-4dba-9a7f-6e6dabbacf94)

I only added the purple highlight for Foo and Bar, but the rest could have the same background highlight as they currently do.

This way, to edit something on one element only, I simply click on the element tab and change the value. If I want to change the token, I select the token, and I know any values I add, edit, or remove, will affect all elements with that token - whilst with the current setup, I am never sure if this is the case or not. Rather than "convert to token", I could perhaps right-click any tab, and select something like "create new token from this", which would mean that I know what it is that is copied, and then select that tab to edit the set of what was copied.

It would still be possible to colour items in a similar way to the existing manner to indicate what is overriding what else. However, I think this makes it more evident what it is I am changing when I do so. It could also be possible to filter in the UI only those variables/sections that are set on that source. E.g. if I have a token that is all about colour schemes, I could select a tickbox to filter out only the properties or sections of properties that are set on that token - so anything  like flexbox children, alignment, padding, etc. could be collapsed, and I can quickly find the values I would want to tweak.

Would this be something others would find helpful?

Cheers

**Comment by kof** [comment]
I understand the concern and the desire to simplify. As with all simplification there comes a downside, in this case with tabbed approach is that it doesn't explain that the final style is a combination of all style sources in that order.

I am not sure how to improve the clarity from where we are today, but I don't think tabs is the solution.

**Comment by stellarpower** [comment]
Of course, understand it's never that simple :).

I was thinking about this, but I don't know WS well enough to know if it was the case or not that they are being combined in order. If styles are applied in order, can the tabs be ordered, e.g. right-to-left, with right being the base and left being manual changes to the element? And then I could scroll through from base style to overriding style

Another option would be something like the "computed" view in most browsers' web inspectors. Then I could edit the style source on its own, and use this tab (probably uneditable) to see what the final result is. Or alternatively, the tab for the element on its own could show the combination of style sources before it, and then anything I edit there would be a manual override on that element only.

As an intermediate fix, I think when I hover, I can see the list of sources:
![image](https://github.com/user-attachments/assets/23a60a99-671f-47cd-a229-8dc88135f9f0)
Even if I could click on one of those, and "get" to that style source in order to change the settings (e.g. click on Vertical Button right Text to see the styles on that token), I think that would help make the experience a lot more usable.

**Comment by kof** [comment]
This is all actually well thought out, style sources merge from left to right. Color coding is well explained  in the videos and in the docs. For now I will close this issue. If you have ideas that can improve it, we are happy to listen

**Comment by stellarpower** [comment]
Well, I've been using the tool here and there for a few months. Watched several videos on youtube etc. over that time, I do feel some jump in a bit quickly to an example website and using things in situ before explaining how they work. Lots of zooming the recording in and out when I find it helps to explain why you are clicking on something. Maybe there is one just going over in more detail how the UI works, but I haven't seen it come up in my search results yet. So if not, it'd be nice to have one or and to an existing one explaining the functionality of how the picker at the top works a bit more. I've been scrubbing through those and searching several times for text documentation trying to get an idea of what I'm not doing.

It's only just now I realise if I click the little blue bullseye icon it means the palette is switching between the two, the greying out felt more like the style is being unapplied or overridden. I guess what I was suggesting is happening when I do that, I didn't realise I could. For me, tabs make sense, I tend to like the conventional desktop metaphor a lot of the time. But if that's not desirable, I think maybe adding some accent colours would help provide that feedback. A purple outline or shading to the background colour and I think it would give the visual indication that I'm editing the token. Also using purple so it matches rather than blue highlighting of properties would help differentiate between local or token changes. I realised early on that I was presumably editing something on that token and the blue didn't mean the element on its own, but couldn't see why sometimes it was the element and other times it was the token. To my mind it resembles a list of tags that can be toggled on or off, as opposed to mutually-exclusive sources I can select between that will change what is in the palette. From some videos I have seems it looks that previous versions had "local" as a separate blue element in the token list, and to me it makes more sense to have this, and the drop-down as a separate menu I can click on.

It'd also be helpful to have an orange highlight in the popup that shows explaining the reason for the colour:
![image](https://github.com/user-attachments/assets/c1c841ba-66f4-4eef-bf1e-5d3a3077acc7)
I.e. highlight "Value comes from a different source" in the same orange, and "Reset value" maybe in the same blue, so that the relationship between those two is clearer.

Those would be my thoughts anyway.
