### ISSUE TITLE
Style panel tooltips should have a link to mdn

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4383]
Every style panel tooltip for a property or value should have a link icon that leads user to mdn. All these links can be built at runtime since mdn has structured urls.

**Comment by JayaKrishnaNamburu** [comment]
Here is the two variations we can connect these links, any suggestions on which looks better ?

<img width="236" alt="Screenshot 2024-11-11 at 8 51 37 AM" src="https://github.com/user-attachments/assets/988a8020-301d-4e4a-8001-4b084e802a8a">
<img width="233" alt="Screenshot 2024-11-11 at 8 55 30 AM" src="https://github.com/user-attachments/assets/48c65e12-6a86-4e2b-9484-52b437d260ca">

**Comment by kof** [comment]
Another option is top right corner on the same level as title, making sure title would be shortened with ellipsis if it is too long

**Comment by kof** [comment]
And using external link icon

**Comment by JayaKrishnaNamburu** [comment]
![external_link](https://github.com/user-attachments/assets/6e3fda8a-ced8-49da-9ac4-1d238574b963)
<img width="545" alt="Screenshot 2024-11-12 at 7 27 46 PM" src="https://github.com/user-attachments/assets/e5362f93-307d-4ff7-be54-741ad9e6ef0f">

**Comment by kof** [comment]
also noticed - cursor should be pointer on external links

**Comment by kof** [comment]
Just checked, we actually failed to use an anchor element for external link icon-buttons probably because we don't have a link icon button component in the design system

**Comment by JayaKrishnaNamburu** [comment]
Will take care of all the things, placement wise and integration wise. Looking fine ?

**Comment by kof** [comment]
Yeah, I think placement looks fine to me
