### ISSUE TITLE
Reset a single sizing option resets the all of it

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4411]
Repro:

- [ ] create flex child
- [ ] open sizing advanced
- [ ] set any value in grow and shrink
- [ ] try to reset only grow or only shrink

<img width="482" alt="image" src="https://github.com/user-attachments/assets/8bf85865-706b-4957-922d-1e17fb166aa1">

**Comment by JayaKrishnaNamburu** [comment]
Looks like its working fine now 👍 

![reset-flex-child-properties](https://github.com/user-attachments/assets/51dffab5-c155-441d-83e7-d935f40c4ab0)

**Comment by kof** [comment]
Try option+click on the label

**Comment by JayaKrishnaNamburu** [comment]
> Try option+click on the label

Yup, looks like using the shortcut is resetting everything, will take care of it 👍
