### ISSUE TITLE
Flex child options tooltip doesn't contain the value

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4412]
Repro

1. create a flex child
2. hover over any values
3. see tooltip doesn't say what the value is, it repeats the property name

<img width="261" alt="image" src="https://github.com/user-attachments/assets/af2727c5-67bd-4eae-ba3b-91f774cb3e1c">

**Comment by TrySound** [comment]
What is the problem here? Tooltip shows hovered value.

**Comment by kof** [comment]
I got confused, maybe its ok, but for a second I expected the title to contain the value, where the value is only in the css string. Maybe that's ok though, because somehow we need to show both the property and the value

**Comment by JayaKrishnaNamburu** [comment]
While just looking for it, i found that we can still improve the descriptions for these items. Currently we are using static text here. Can be improved by assigning them to the AI generated ones.
https://github.com/webstudio-is/webstudio/blob/main/apps/builder/app/builder/features/style-panel/sections/flex-child/flex-child.tsx#L74
https://github.com/webstudio-is/webstudio/commit/e82ae1c0d5c995a94d63101c5781219fc178885e
