### ISSUE TITLE
Page title field becomes unfocused after entering one character

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4435]
Try changing the page title field and you can only type in one character then have to click in again for another character.

1. Click into page title field
2. Try typing hello
3. See only "h"

https://github.com/user-attachments/assets/a72d3de2-1e48-4e1d-a8e4-049de13fe400

Maybe the result of tooltip delay fixes? 🤷 Only other thing I can think of was the change where clicking into Page Settings makes that page active.

**Comment by istarkov** [comment]
Fixed as fast fix at https://github.com/webstudio-is/webstudio/pull/4428
