### ISSUE TITLE
Use accept language header to auto select preferred lang

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4447]
As a user, I want the locale to be auto selected based on the users preferences.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

May need some more research for this.

https://discord.com/channels/955905230107738152/1296213734871666758

**Comment by kof** [comment]
To be more precise, I think we will need to expose request this information via system variable, so that the user can use it to choose the language if they prefer to. Something like: `system.acceptedLanguages = ['en', 'de' ]`

**Comment by istarkov** [comment]
It is like some rule engine
```
if:
pathname eq `/` AND cookie[user-language] is empty AND header['accepted-languages'] intersects ['fr', 'de']
then:
redirect(`/${intersect(header, ['fr', 'de'])[0]}`)
```

**Comment by istarkov** [comment]
Libraries to help 
https://www.npmjs.com/package/accepts
or this https://www.npmjs.com/package/negotiator

**Comment by istarkov** [comment]
Anyway client side we have 
`navigator.languages` and `navigator.language` and having amount of possible logic I will recomment to use them for redirects.
After redirect headers is not needed because of SEO see above.

IMO can be closed.

**Comment by johnsicili** [comment]
@kof Up to you. I'm not knowledgeable on this but makes sense to me

**Comment by kof** [comment]
I guess in this case the question is if we should automate the redirect for the user. Technically they can redirect on the client with a script, but ...

**Comment by istarkov** [comment]
redirect on the server can be non fixable, i.e permanent redirects. Not sure we want to give such power to the User. The only way this can be done serverside only if we will have some opinionated localization solution.

**Comment by kof** [comment]
ok, then I am closing this issue for now, for future references, the decision is to add your redirect logic in the script on the client depending on how it needs to be done in terms of preferences
