### ISSUE TITLE
Cannot upload CJK fonts

### ISSUE THREAD

**Issue by technatkly** [webstudio-is/webstudio#4459]
<img width="335" alt="SCR-20241122-bqng" src="https://github.com/user-attachments/assets/292433bc-aa44-48c4-b5c0-10f19d23629e">

When I upload a Traditional Chinese font (NotoSansTC), it shows that asset cannot be larger than 4.5MB. However, most of the CJK fonts are larger than 10MB, which means we can't customise our sites with these fonts at all. 

I would very much appreciate if the system could
1) allow larger font assets upload (up to e.g. 20MB), or 
2) integrate Google Fonts which allows many other languages as well. 

Thanks a lot!

**Comment by kof** [comment]
Hi, we have an issue that should solve this https://github.com/webstudio-is/webstudio/issues/417

Be careful with those 10mb fonts, if you upload this, it means your visitors will have to download that font on every visit.
