### ISSUE TITLE
Empty description space for color-inputs in the combobox

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [webstudio-is/webstudio#4585]
Colors don't have descriptions unlike other properties. So, it looks odd in the UI to see the empty space.

<img width="243" alt="Screenshot 2024-12-14 at 9 04 24 AM" src="https://github.com/user-attachments/assets/ea7c9877-49c4-482b-b51b-4d8c1a44ced5" />

<img width="246" alt="Screenshot 2024-12-14 at 9 04 53 AM" src="https://github.com/user-attachments/assets/8092a1e6-6186-4f9f-b14a-b129415be723" />

**Comment by JayaKrishnaNamburu** [comment]
We can fix it, by adding a check here
https://github.com/webstudio-is/webstudio/blob/e703bf89267c488c3a061e6df3c6feec56bee6c5/packages/design-system/src/components/combobox.tsx#L123-L130

But the only doubt i have is, what happens if an option in the list has a description and the other doesn't. The list might jump around.
Eg: `static` has a description, but `relative` doesn't and again `absolute` has a description like that. 
But, we do make sure we generate values for all the options at the time of description generation though. So, i don't think it will be an issue.

**Comment by kof** [comment]
> what happens if an option in the list has a description and the other doesn't.

Always have a default text as a description

**Comment by istarkov** [comment]
Fixed here #4591
