### ISSUE TITLE
Shift P causes Publish to open when naming instance

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4638]
1. Edit instance label
2. Use Shift P to type something like "Page"
3. See publish dialog open

https://github.com/user-attachments/assets/2dafd4a1-f038-406a-8440-dca59fae1f77

**Comment by johnsicili** [comment]
Also other places like commands https://discord.com/channels/955905230107738152/1320167585840496640/1320167585840496640

**Comment by kof** [comment]
fixed
