### ISSUE TITLE
Copy-paste from Webflow

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio#492]
Should be possible as they use Clipboard API. We'll have to convert from their data format to ours though.

Before we can do that, we need:
- [ ] Linked CSS Editor https://github.com/webstudio-is/webstudio-builder/issues/34 (so we can support grid etc even though we don't have a visual ui for it yet)
- [ ] ideally it should come as a plugin https://github.com/webstudio-is/webstudio-builder/issues/1526

**Comment by kof** [comment]
https://jsfiddle.net/7zj56veg/

**Comment by kof** [comment]
TBC in https://github.com/webstudio-is/webstudio/issues/2647
