### ISSUE TITLE
Rename the "migrations" executable as it may pollute executables namespace

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio#611]
https://github.com/webstudio-is/webstudio-designer/blob/23a19b682e1cc95d8827db19f93f1b0e4748186e/packages/prisma-client/package.json#L16-L18

If `@webstudio-is/prisma-client` will become a dependency in some user's project (even indirect) our "migrations" bin may clash with some of their executables as it's a common name.

https://discord.com/channels/955905230107738152/1051832063457755136

**Comment by kof** [comment]
this way every package we have must have unique names in bin

**Comment by kof** [comment]
something like `wstd-migrations`
