### ISSUE TITLE
Focus link href property when link is being added to the canvas

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#66]
When a link is either added from the menu or from the overlay there is no way to change the link settings.

At minimum there should be a way to add a URL in the properties, and the properties panel should open and highlight when a link is first created.

In the future links need:
- settings overlay that can be opened from the canvas
- a unique section in the properties that shows conditionally when a link element is selected

Those settings need to enable the user to:
- add different types of links: email, phone, URL, section links, or internal page links
- the page link option should show all pages in the current project as a dropdown
- the URL link option should have a "open in a new tab" checkbox
- the section link option could show all elements with a section tag, plus a hint to add a section tag (with unique ID?) to enable the option to link to a section

Screenshot examples from Webflow UI
<img width="276" alt="Screen Shot 2022-06-14 at 7 39 53 AM" src="https://user-images.githubusercontent.com/86495896/173605317-4225284d-635e-49bd-8367-7e24bc84c7e1.png">

<img width="238" alt="Screen Shot 2022-06-14 at 7 42 26 AM" src="https://user-images.githubusercontent.com/86495896/173605898-4864c227-de00-4cea-b5af-beb14432b278.png">

## Waiting for

- [x] https://github.com/webstudio-is/webstudio-designer/issues/24

**Comment by kof** [comment]
We also need to focus src property when image was added, so we basically need to have a mechanism for all components to express a goto when component was added to the canvas

**Comment by kof** [comment]
tbc in https://github.com/webstudio-is/webstudio/issues/2355
