### ISSUE TITLE
Selected instance and hovered instance outlines may overlap

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#69]
![image](https://user-images.githubusercontent.com/52824/173866874-fdd35727-c41b-487c-a473-c7c23398ed20.png)

This bug is also a problem at Webflow

![image](https://user-images.githubusercontent.com/52824/173866766-b473bb99-abe2-4f59-9a5e-167de7dd43d7.png)

**Comment by taylornowotny** [comment]
The way we are handling this is not bad, but we need to distinguish the hovered and the selected element in some way.

Maybe a different color, maybe an outlined box instead of a solid box. Will come back to this
