### ISSUE TITLE
More style panel controls

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#879]
## Todo

- [x] cursor
- [x] opacity
- [x] pointer events
- [x] Blend Mode
- [x] user select
- [ ] transition
- [ ] filters

**Comment by taylornowotny** [comment]
+ Blend Mode

I am tracking the Effects sections and it will be done soon, it's just behind some other features on my to-do list like Position Section. I will update this issue with any questions or further discussion.

**Comment by darindimitroff** [comment]
I think all of these would end up in the Effects section, correct?

**Comment by taylornowotny** [comment]
Yes but most or all of these will be individual sections. 

See [the WIP designs in figma here](https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=4512-49938) 

<img width="275" alt="Screenshot 2023-06-23 at 8 56 41 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/8a8f54dc-90bf-443b-af6e-76664b935cfd">

**Comment by taylornowotny** [comment]
<img width="582" alt="Screenshot 2023-06-23 at 8 58 23 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/e2988df1-00dd-4837-84fe-8c51baa9c916">

@darindimitroff notice that for properties like box-shadows, backgrounds, and Transitions, we have a pattern where the section title has an Add (+) button so the user can add multiple values for that property and arrange their order. This design uses the [CSS Value List Item component](https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=2002%3A6155&t=N1E9gl5gEc6NOqP1-1). 

Let me know if you have questions about this design pattern or if you think Transitions would be better with a different pattern.

**Comment by kof** [comment]
closing this one, transition and filters are separate issues
