### ISSUE TITLE
Auth: Trying to login using GitHub results in an error

### ISSUE THREAD

**Issue by okonet** [webstudio-is/webstudio#95]
I see 

```json
{"message":"Missing state on session."}
```

on screen.

**Comment by kof** [comment]
@SaraVieira  do you know what this is?

**Comment by SaraVieira** [comment]
Do you have the envs?

Also that's always what shows in the screen, can you show me the url it redirects you to?

**Comment by kof** [comment]
@SaraVieira can we make it show a better error message even if the env wasn't correctly configured?

**Comment by SaraVieira** [comment]
That's what's the other MR is for

**Comment by okonet** [comment]
@SaraVieira I was trying to access https://webstudio-designer-git-lexical-webstudio-is.vercel.app

**Comment by SaraVieira** [comment]
Oh sorry i don't think i said but PR branches don't work with GitHub login
because it requires a specific callback url and url of these branches is
never the same
