### ISSUE TITLE
Simplify packages publishing

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio#986]
Right now to publish packages we manually bump all versions, push and then action publish these packages. Though string-replace sometimes fails and it's easy to miss some package if edit each package.json. We need some automation, for example with changesets. So bumping could be just one command, commit and push.

Semantic versioning is not required so changes could always bump minor version.

**Comment by Andarist** [comment]
I love Changesets - but it requires you to create "release intents" (with messages for changelog entries + the desired minimum bump type). This is great for matured projects but I think that you might want to "move fast" for now - please correct me if I'm wrong.

So given that, I propose a script that would do this:
1. crawl the history for the last release commit
2. diff between that and HEAD
3. generate bumps with minor for everything that changed in this diff
4. commit+release+push

The additional question is - should this be a script that you want to execute manually? or do you want to automate this (for example through PRs)?

cc @webstudio-is/core

**Comment by kof** [comment]
@Andarist I agree that we want to move fast and I don't have experience with changesets, so I didn't know it would make us slow.

@TrySound what do you think?

**Comment by TrySound** [comment]
Yeah, we want to commit bump manually and publish with action

**Comment by Andarist** [comment]
> @Andarist I agree that we want to move fast and I don't have experience with changesets, so I didn't know it would make us slow.

Slow is an exaggeration here - it's just something to consider here. The main benefit of Changesets are the produced CHANGELOGs and **I think** (could be wrong) that you don't exactly need them right now.

---

I'll cook something up for you - but it might be next week or something.

**Comment by kof** [comment]
@Andarist I am fine with releasing using the release UI from github, its actually quite nice, the problem seem to be publishing and bumping versions is very manual. 

I think we could hook in the publishing process into github release. Probably don't need changesets for this since with github release UI we are defining the version etc.

**Comment by TrySound** [comment]
Nothing yet
