### ISSUE TITLE
NumericInput doesn't work in Safari

### ISSUE THREAD

**Issue by okonet** [webstudio-is/webstudio#99]
Currently, the `pointerLock` API which is used in the NumericInput causes Safari to show a special banner

https://user-images.githubusercontent.com/11071/176870343-9077ca47-7a47-487e-b5c7-3e337ae28eb3.mp4

I think we should not use this API since it's not clear how it's going to behave in different browsers. Also [from the docs](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) I read it's for games etc. which isn't our use case IMO.

**Comment by kof** [comment]
Oh shit ... @thysultan didn't know there is such a banner in safari, how does figma do it?

**Comment by kof** [comment]
@natlusyht is there an easy way around this?

**Comment by kof** [comment]
sounds reasonable to just disable infinite cursor for safari since it doesn't let you do that properly

**Comment by okonet** [comment]
I'd say vertical direction should do it without infinite scrolling. But we should make the primitive usable IMO.

**Comment by kof** [comment]
add `isInfinite` option so one can configure it
