### ISSUE TITLE
Props panel: description of a property in a tooltip

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio#995]
<img width="255" alt="Screenshot 2023-02-10 at 17 16 00" src="https://user-images.githubusercontent.com/825702/218101376-79b6a42d-3ef7-448c-9472-52683ea1a83b.png">

@taylornowotny We talked with @kof about an ability to have description for any property: allow developers of the components to define description that should be show in the UI.

What do you think? Can we show an icon like this near any label when description is defined? Can we change this icon to something more general like `(!)`?

**Comment by taylornowotny** [comment]
Go for it 👍

I’ll change the icon in the design.

Notice that our Label component has the ability to show/hide an icon in
component props and that’s the info icon by default.
